import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "FishMaryland Angler, Expert & Master Awards | Fish the Fifty",
  description: "Follow Maryland DNR's FishMaryland Species Awards and three, five, and ten-species milestones with eligibility sizes and submission guidance.",
};

const links = {
  program: "https://dnr.maryland.gov/fisheries/Pages/FishMaryland/index.aspx",
  submit: "https://dnr.maryland.gov/fisheries/Pages/FishMaryland/directions.aspx",
  records: "https://dnr.maryland.gov/fisheries/Pages/state_records/sr_main.aspx",
  licenses: "https://dnr.maryland.gov/Pages/service_fishing_license.aspx",
};

const examples = [
  ["Brook trout", "Nontidal", "12 in."], ["Brown trout", "Nontidal", "21 in."],
  ["Rainbow trout", "Nontidal", "20 in."], ["Largemouth bass", "Nontidal", "21 in."],
  ["Crappie", "Nontidal or Chesapeake", "15 in."], ["Yellow perch", "Nontidal or Chesapeake", "14 in."],
  ["White perch", "Nontidal or Chesapeake", "13 in."], ["Striped bass", "Catch and release", "40 in."],
  ["Red drum", "Catch and release", "36 in."], ["Blue catfish", "Invasive; harvest only", "40 in."],
] as const;

export default function MarylandChallengePage() {
  return <main>
    <header className="nav-shell"><div className="nav-wrap"><a className="brand" href="/">FISH THE FIFTY</a><nav aria-label="Main navigation"><a href="/states">States</a><a href="/#challenges">Challenges</a><a href="/members">My Progress</a></nav></div></header>
    <div className="breadcrumb"><a href="/states">States</a><span aria-hidden="true"> / </span><span>Maryland</span></div>
    <section className="page-hero challenge-hero"><div className="page-hero-inner"><p className="eyebrow">MARYLAND · FISHMARYLAND</p><h1>Three. Five. Ten.<br />Master Angler.</h1><p className="lead">Earn FishMaryland Species Awards for different trophy-sized fish. Maryland DNR recognizes three species with an Angler milestone, five with Expert Angler, and ten with Master Angler.</p><div className="state-facts"><span>3 · Angler</span><span>5 · Expert</span><span>10 · Master</span></div><div className="actions"><a className="btn primary" href="#milestones">Explore the milestones ↓</a><a className="btn secondary" href={links.program} target="_blank" rel="noreferrer">Official FishMaryland program ↗</a></div></div></section>
    <section className="section challenge-layout" id="milestones"><div><p className="eyebrow">THE OFFICIAL PATH</p><h2>Build a ten-species story.</h2><ol className="challenge-steps"><li><strong>Earn a Species Award.</strong><span>Legally catch a fish from Maryland’s eligible list at its category’s minimum size. The program spans Atlantic Coast, Chesapeake Bay, nontidal, catch-and-release, and invasive categories.</span></li><li><strong>Register each qualifying catch.</strong><span>Measure as directed, photograph the fish on a measuring device, submit the online application, and email the photo separately to Maryland DNR.</span></li><li><strong>Collect different approved species.</strong><span>Three distinct Species Awards unlock Angler, five unlock Expert Angler, and ten unlock Master Angler. DNR automatically awards milestone certificates after verification.</span></li></ol><a className="btn primary" href={links.submit} target="_blank" rel="noreferrer">How to submit a catch ↗</a></div><aside className="challenge-side"><p className="eyebrow">MILESTONE AWARDS</p><h2>Each level counts.</h2><p><strong>Angler · 3 species</strong><br />Certificate and yellow milestone sticker.</p><p><strong>Expert · 5 species</strong><br />Certificate and red milestone sticker.</p><p><strong>Master · 10 species</strong><br />Certificate and black milestone sticker; eligibility for a Bass Pro Shops gift card.</p><p>DNR counts Species Awards for catches after January 1, 2019; each milestone is awarded once per angler.</p><a className="btn secondary" href={links.program} target="_blank" rel="noreferrer">Read milestone details ↗</a></aside></section>
    <section className="section qualification-section alabama-size-section" id="sizes"><div className="section-heading"><p className="eyebrow">SELECT SPECIES AWARD SIZES</p><h2>Choose your next species.</h2><p>These are examples from Maryland DNR’s current list. Rules, measurement methods, and categories differ by fish; confirm the full official list before applying.</p></div><div className="qualification-table-wrap alabama-table-wrap"><table><caption className="visually-hidden">Selected FishMaryland Species Award minimum lengths</caption><thead><tr><th scope="col">Species</th><th scope="col">Category</th><th scope="col">Minimum</th></tr></thead><tbody>{examples.map(([species, category, size]) => <tr key={species}><th scope="row">{species}</th><td>{category}</td><td>{size}</td></tr>)}</tbody></table></div><div className="actions"><a className="btn primary" href={links.program} target="_blank" rel="noreferrer">All eligible species and sizes ↗</a></div></section>
    <section className="section"><div className="section-heading"><p className="eyebrow">KEEP THE ENTRY ELIGIBLE</p><h2>Check the rules behind the photo.</h2><p>FishMaryland requires a legal catch and clear size evidence. Most eligible species must be caught on a manually operated rod and reel, with the angler hooking and fighting the fish. Read the category-specific exceptions before fishing.</p></div><div className="card-grid"><article className="challenge-card"><span className="state-pill">RELEASE</span><h3>Release-only species</h3><p>Red drum, sharks, marlins, and sailfish must be released alive for a Species Award. Released entries must also be released alive.</p><a href={links.program} target="_blank" rel="noreferrer">DNR release rules ↗</a></article><article className="challenge-card"><span className="state-pill">INVASIVE</span><h3>Harvest required</h3><p>Blue catfish, flathead catfish, and Chesapeake channa (northern snakehead) are eligible only if killed; the submitted photo must show this.</p><a href={links.program} target="_blank" rel="noreferrer">DNR invasive rules ↗</a></article><article className="challenge-card"><span className="state-pill">SUBMIT</span><h3>Photo and application</h3><p>Use the online registration, then email a clear fish-on-measure photo to the address provided by DNR. Verified entries receive their award.</p><a href={links.submit} target="_blank" rel="noreferrer">Submission directions ↗</a></article></div></section>
    <section className="section challenge-layout"><div><p className="eyebrow">ANOTHER OFFICIAL PATH</p><h2>Maryland state fish records.</h2><p>Maryland DNR also maintains sport fish records and awards a plaque for a new qualifying record or newly established species category. Record claims have separate weighing, verification, and application rules; review them promptly if you catch a contender.</p><a className="btn primary" href={links.records} target="_blank" rel="noreferrer">Explore Maryland records ↗</a></div><aside className="challenge-side"><p className="eyebrow">BEFORE YOU GO</p><h2>Check your license.</h2><p>Maryland’s fishing license and saltwater registration requirements depend on the water and angler. Check current regulations and any exemptions before a trip.</p><a className="btn secondary" href={links.licenses} target="_blank" rel="noreferrer">Maryland fishing licenses ↗</a></aside></section>
    <section className="section final-cta challenge-final"><p className="eyebrow">READY TO START?</p><h2>Pick a species. Earn the first award.</h2><p>Compare Maryland’s live size list, measure and photograph your catch, then submit each species through the official FishMaryland process.</p><div className="actions"><a className="btn primary" href={links.program} target="_blank" rel="noreferrer">Open FishMaryland ↗</a><a className="btn secondary" href="/states">Back to all states</a></div></section>
    <footer><strong>FISH THE FIFTY</strong><span>Built for anglers who want to fish farther.</span></footer>
  </main>;
}
