export const floridaLifeListSpecies = [
  "African pompano",
  "Almaco jack",
  "Atlantic croaker",
  "Atlantic sharpnose shark",
  "Atlantic spadefish",
  "Banded rudderfish",
  "Black drum",
  "Black grouper",
  "Black sea bass",
  "Blackfin snapper",
  "Blackfin tuna",
  "Blacknose shark",
  "Blacktip shark",
  "Blue marlin",
  "Blue runner",
  "Bluefish",
  "Bonefish",
  "Bonnethead shark",
  "Bull shark",
  "Cero",
  "Common thresher shark",
  "Cobia",
  "Crevalle jack",
  "Cubera snapper",
  "Dog snapper",
  "Dolphinfish",
  "Florida pompano",
  "Gafftopsail catfish",
  "Gag",
  "Gray (mangrove) snapper",
  "Gray triggerfish",
  "Great barracuda",
  "Greater amberjack",
  "Gulf flounder",
  "Gulf kingfish (whiting)",
  "Hardhead catfish",
  "Hogfish",
  "Horse-eye jack",
  "King mackerel",
  "Lane snapper",
  "Ladyfish",
  "Lesser amberjack",
  "Little tunny",
  "Mutton snapper",
  "Northern kingfish",
  "Palometa",
  "Permit",
  "Queen snapper",
  "Red drum",
  "Red grouper",
  "Red porgy",
  "Red snapper",
  "Sailfish",
  "Scamp",
  "Schoolmaster",
  "Sheepshead",
  "Silk snapper",
  "Snook",
  "Southern flounder",
  "Southern kingfish (whiting)",
  "Spanish mackerel",
  "Spinner shark",
  "Spotted seatrout",
  "Swordfish",
  "Tarpon",
  "Tripletail",
  "Vermilion snapper",
  "Wahoo",
  "Warsaw grouper",
  "Weakfish",
  "White grunt",
  "White marlin",
  "Yellow jack",
  "Yellowfin tuna",
  "Yellowtail snapper",
] as const;

export const floridaReelBigFish = [
  { name: "African pompano", adult: 36, youth: 27, measure: "fork length" },
  { name: "Almaco jack", adult: 30, youth: 22, measure: "fork length" },
  { name: "Black drum", adult: 36, youth: 27, measure: "total length" },
  { name: "Black sea bass", adult: 17, youth: 13, measure: "total length" },
  { name: "Bluefish", adult: 27, youth: 20, measure: "fork length" },
  { name: "Catfish", adult: 22, youth: 16, measure: "total length" },
  { name: "Cobia", adult: 45, youth: 33, measure: "fork length" },
  { name: "Crevalle jack", adult: 32, youth: 24, measure: "fork length" },
  { name: "Florida pompano", adult: 17, youth: 13, measure: "fork length" },
  { name: "Flounder", adult: 21, youth: 16, measure: "total length" },
  { name: "Gag", adult: 36, youth: 27, measure: "total length" },
  { name: "Gray (mangrove) snapper", adult: 24, youth: 18, measure: "total length" },
  { name: "Gray triggerfish", adult: 19, youth: 14, measure: "fork length" },
  { name: "Greater amberjack", adult: 50, youth: 37, measure: "fork length" },
  { name: "Hogfish", adult: 24, youth: 18, measure: "fork length" },
  { name: "King mackerel", adult: 45, youth: 33, measure: "fork length" },
  { name: "Ladyfish", adult: 22, youth: 16, measure: "fork length" },
  { name: "Mutton snapper", adult: 24, youth: 18, measure: "total length" },
  { name: "Permit", adult: 31, youth: 23, measure: "fork length" },
  { name: "Red drum", adult: 30, youth: 22, measure: "total length" },
  { name: "Red grouper", adult: 30, youth: 22, measure: "total length" },
  { name: "Red porgy", adult: 20, youth: 15, measure: "total length" },
  { name: "Scamp", adult: 27, youth: 20, measure: "total length" },
  { name: "Sheepshead", adult: 21, youth: 16, measure: "total length" },
  { name: "Snook", adult: 36, youth: 27, measure: "total length" },
  { name: "Spanish mackerel", adult: 24, youth: 18, measure: "fork length" },
  { name: "Spotted seatrout", adult: 24, youth: 18, measure: "total length" },
  { name: "Tripletail", adult: 24, youth: 18, measure: "total length" },
  { name: "Vermilion snapper", adult: 17, youth: 13, measure: "total length" },
  { name: "Yellowtail snapper", adult: 20, youth: 15, measure: "total length" },
] as const;

export const floridaGrandSlams: { name: string; species: string; note?: string }[] = [
  { name: "Small Fry", species: "Pinfish, catfish, and grunt or drum", note: "Anglers age 15 and under" },
  { name: "Nearshore", species: "Cobia, great barracuda, and king mackerel" },
  { name: "Blue Water", species: "Dolphinfish, sailfish, and wahoo" },
  { name: "Reefs & Rubble", species: "Gray (mangrove) snapper, gag, and triggerfish" },
  { name: "Shoreline", species: "Sheepshead, Florida pompano, and whiting" },
  { name: "Bay & Estuary", species: "Bluefish, Spanish mackerel, and ladyfish" },
  { name: "Florida", species: "Bonefish, permit, and tarpon" },
  { name: "Inshore", species: "Red drum, spotted seatrout, and flounder or snook" },
  { name: "Family", species: "Any three fish in the same scientific family" },
];
