import type { Metadata } from "next";
import DelawareTracker from "./tracker";
import { freshwater, saltwater, type Fish } from "./species";

export const metadata: Metadata = { title: "Delaware Sport Fishing Tournament & Elite Angler | Fish the Fifty", description: "Plan Delaware's five-species Elite Angler goal and review official adult and youth tournament sizes." };
const base = "https://dnrec.delaware.gov/fish-wildlife/fishing/tournament/";
function Sizes({ heading, fish }: { heading: string; fish: Fish[] }) {
  return <div><h3>{heading}</h3><div className="qualification-table-wrap alabama-table-wrap"><table><caption className="visually-hidden">Delaware {heading.toLowerCase()} adult and youth minimum tournament sizes</caption><thead><tr><th scope="col" rowSpan={2}>Species</th><th scope="colgroup" colSpan={2}>Adult</th><th scope="colgroup" colSpan={2}>Youth 15 and under</th></tr><tr><th scope="col">Weight · lb</th><th scope="col">Release · in</th><th scope="col">Weight · lb</th><th scope="col">Release · in</th></tr></thead><tbody>{fish.map(f => <tr key={f.name}><th scope="row">{f.name}</th><td>{f.adultWeight}</td><td>{f.adultLength}</td><td>{f.youthWeight}</td><td>{f.youthLength}</td></tr>)}</tbody></table></div></div>;
}
export default function DelawareChallengePage() {
  return <main>
    <header className="nav-shell"><div className="nav-wrap"><a className="brand" href="/">FISH THE FIFTY</a><nav aria-label="Main navigation"><a href="/states">States</a><a href="/#challenges">Challenges</a><a href="/#progress">My Progress</a></nav></div></header>
    <div className="breadcrumb"><a href="/states">States</a><span aria-hidden="true"> / </span><span>Delaware</span></div>
    <section className="page-hero challenge-hero"><div className="page-hero-inner"><p className="eyebrow">DELAWARE · DIVISION OF FISH AND WILDLIFE</p><h1>Delaware Sport<br />Fishing Tournament.</h1><p className="lead">Earn citations for qualifying freshwater or saltwater catches. Adult anglers who receive citations for five different species in a calendar year can earn Delaware Elite Angler recognition.</p><div className="state-facts"><span>January 1 – December 31</span><span>5 species for Elite</span><span>Adult and youth divisions</span></div><div className="actions"><a className="btn primary" href="#elite">Plan your Elite goal ↓</a><a className="btn secondary" href={base} target="_blank" rel="noreferrer">Official tournament ↗</a></div></div></section>
    <section className="section challenge-layout"><div><p className="eyebrow">OFFICIAL PATH TO ELITE</p><h2>Five different species. One year.</h2><ol className="challenge-steps"><li><strong>Choose freshwater, saltwater, or both.</strong><span>Any combination of tournament citations can count toward the adult Elite Angler goal.</span></li><li><strong>Meet the correct size.</strong><span>Weighed entries use the published weight and an official Tournament Weigh Station. Live-release entries use the published length and an actual-measurement witness.</span></li><li><strong>Receive five species citations.</strong><span>All five different species must be cited within the same calendar year; no more than two can be Live Release Awards.</span></li><li><strong>Follow submission deadlines.</strong><span>Weighed entry forms must be received by January 31 of the following year. Live-release entries must be sent within 30 days of the catch.</span></li></ol><a className="btn primary" href={`${base}rules/`} target="_blank" rel="noreferrer">Read tournament rules ↗</a></div><aside className="challenge-side"><p className="eyebrow">CITATIONS &amp; AWARDS</p><h2>Every qualifying fish counts.</h2><p>The tournament is free to enter. Anglers can receive multiple species citations, while award pins are limited to one freshwater and one saltwater award per tournament year. DNREC also recognizes the largest qualifying fish of each species with its annual Big Fish Award.</p><p>Elite recognition includes a plaque and is a once-in-a-lifetime accomplishment.</p><a className="btn secondary" href={base} target="_blank" rel="noreferrer">Explore awards ↗</a></aside></section>
    <section className="section" id="elite"><div className="section-heading"><p className="eyebrow">YOUR PRIVATE PLANNER</p><h2>Build a five-species list.</h2><p>Keep potential adult citations in this browser. Confirm each catch and citation with DNREC; this planner does not submit an entry.</p></div><DelawareTracker /></section>
    <section className="section qualification-section alabama-size-section"><div className="section-heading"><p className="eyebrow">DNREC MINIMUM TOURNAMENT SIZES</p><h2>Check the size before you enter.</h2><p>Weights are in pounds and require an official weigh station; lengths are in inches and apply only to live-release citations. A dash means DNREC lists no value in that category.</p></div><Sizes heading="Freshwater fish" fish={freshwater} /><Sizes heading="Saltwater fish" fish={saltwater} /><p className="alabama-threshold-note">¹ Smallmouth bass has special water and size conditions. ² It is illegal to transport invasive species alive. ³ Federal handling rules and prohibited species restrictions apply. DNREC’s official table and tournament rules control all entries; review its species notes before fishing. Some fish have special measurement methods.</p><div className="actions"><a className="btn primary" href={`${base}sizes/`} target="_blank" rel="noreferrer">Check official sizes and notes ↗</a></div></section>
    <section className="section challenge-layout"><div><p className="eyebrow">WEIGHED CATCH</p><h2>Find an official station.</h2><p>Bring an eligible catch to a Delaware Sport Fishing Tournament Weigh Station and mail the official entry form. Potential state records require additional inspection by DNREC.</p><a className="btn primary" href={`${base}weigh-stations/`} target="_blank" rel="noreferrer">Find weigh stations ↗</a></div><aside className="challenge-side"><p className="eyebrow">LIVE RELEASE &amp; YOUTH</p><h2>Measure and release promptly.</h2><p>A witness must verify the length and immediate live release. DNREC also offers a youth division for anglers 15 and younger, with its own minimum sizes and awards.</p><div className="actions"><a className="btn secondary" href={`${base}live-release-form/`} target="_blank" rel="noreferrer">Live release entry ↗</a><a className="btn secondary" href={`${base}youth-division/`} target="_blank" rel="noreferrer">Youth division ↗</a></div></aside></section>
    <section className="section final-cta challenge-final"><p className="eyebrow">READY TO START?</p><h2>Pick a species and review the official rules.</h2><p>Confirm current fishing limits, qualifying sizes, special species notes, and the correct entry process before your trip.</p><div className="actions"><a className="btn primary" href={base} target="_blank" rel="noreferrer">Delaware tournament home ↗</a><a className="btn secondary" href="/states">Back to all states</a></div></section>
    <footer><strong>FISH THE FIFTY</strong><span>Built for anglers who want to fish farther.</span></footer>
  </main>;
}
