import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "South Carolina Fish Records | Fish the Fifty",
  description: "Explore South Carolina freshwater and saltwater state fish records, affidavit requirements, certified weighing, and SCDNR verification.",
};

const fresh = "https://www.dnr.sc.gov/fish/freshrecs/records.html";
const salt = "https://dnr.sc.gov/fish/saltrecs/records.html";
const saltRules = "https://dnr.sc.gov/fish/saltrecs/fishrecrules.html";
const licenses = "https://www.dnr.sc.gov/licensing.html";
const tagging = "https://www.dnr.sc.gov/marine/tagfish/index.html";

export default function SouthCarolinaChallengePage() {
  return <main>
    <header className="nav-shell"><div className="nav-wrap"><a className="brand" href="/">FISH THE FIFTY</a><nav aria-label="Main navigation"><a href="/states">States</a><a href="/#challenges">Challenges</a><a href="/members">My Progress</a></nav></div></header>
    <div className="breadcrumb"><a href="/states">States</a><span aria-hidden="true"> / </span><span>South Carolina</span></div>
    <section className="page-hero challenge-hero"><div className="page-hero-inner"><p className="eyebrow">SOUTH CAROLINA · SCDNR RECORD FISH</p><h1>From inland lakes<br />to Atlantic waters.</h1><p className="lead">Choose a freshwater or saltwater species, compare its standing South Carolina record, and learn the documentation steps before a potential record fish is on the line.</p><div className="state-facts"><span>Freshwater records</span><span>Saltwater records</span><span>SCDNR verification</span></div><div className="actions"><a className="btn primary" href="#paths">Explore record paths ↓</a><a className="btn secondary" href={fresh} target="_blank" rel="noreferrer">Freshwater records ↗</a></div></div></section>
    <section className="section challenge-layout" id="paths"><div><p className="eyebrow">FRESHWATER RECORDS</p><h2>Plan for the affidavit.</h2><p>SCDNR publishes standing freshwater records by fish family, including bass, sunfish, trout, catfish and others. Its record page provides the official freshwater game fish affidavit and says the completed affidavit must reach SCDNR within 45 days of the catch.</p><ol className="challenge-steps"><li><strong>Check the current species record.</strong><span>Use SCDNR's live record table before your trip; a standing weight can change.</span></li><li><strong>Follow the record instructions.</strong><span>Open the official affidavit before fishing so you know what evidence and verification to collect.</span></li><li><strong>Submit within 45 days.</strong><span>Complete the affidavit in full and return it as directed by SCDNR.</span></li></ol><a className="btn primary" href={fresh} target="_blank" rel="noreferrer">Freshwater records &amp; affidavit ↗</a></div><aside className="challenge-side"><p className="eyebrow">SALTWATER RECORDS</p><h2>Certified weight and two witnesses.</h2><p>Saltwater record entries require a state-certified scale, two witnesses unrelated to the catch, and inspection by an SCDNR marine fisheries biologist. A qualifying fish must be caught legally on conventional rod and reel and played by one angler.</p><p>New records and ties receive certificates. SCDNR applies minimum weight margins to decide whether a catch is a new record or a tie.</p><a className="btn secondary" href={saltRules} target="_blank" rel="noreferrer">Read saltwater record rules ↗</a></aside></section>
    <section className="section"><div className="section-heading"><p className="eyebrow">OFFICIAL RESOURCES</p><h2>Check the fish and the rules.</h2></div><div className="card-grid"><article className="challenge-card"><span className="state-pill">FRESHWATER</span><h3>Record table</h3><p>Compare bass, trout, catfish, panfish and other listed freshwater species against SCDNR's current records.</p><a href={fresh} target="_blank" rel="noreferrer">Browse records ↗</a></article><article className="challenge-card"><span className="state-pill">SALTWATER</span><h3>Marine record table</h3><p>Review the standing marine records and special notes. Some historic records cannot be challenged under current retention rules.</p><a href={salt} target="_blank" rel="noreferrer">Browse marine records ↗</a></article><article className="challenge-card"><span className="state-pill">CONSERVATION</span><h3>Marine fish tagging</h3><p>SCDNR's separate catch-and-release tagging program supports fish research. Check current participation details and its waitlist before applying.</p><a href={tagging} target="_blank" rel="noreferrer">Explore tagging ↗</a></article></div></section>
    <section className="section final-cta challenge-final"><p className="eyebrow">BEFORE YOU CAST</p><h2>Know what can be kept.</h2><p>Check current licensing, harvest and possession rules for your target species and water. A record listing does not override present-day protections or size limits.</p><div className="actions"><a className="btn primary" href={licenses} target="_blank" rel="noreferrer">SCDNR licensing &amp; regulations ↗</a><a className="btn secondary" href="/states">Back to all states</a></div></section>
    <footer><strong>FISH THE FIFTY</strong><span>Built for anglers who want to fish farther.</span></footer>
  </main>;
}
