import type { Metadata } from "next";
import { accessAreas, appleMapSearch, checkedDate, checkedLabel, googleMapSearch, sources } from "./guide-data";

export const metadata: Metadata = {
  title: "Blue River Oklahoma Fishing Guide | Fish the Fifty",
  description: "Plan a Blue River Public Fishing and Hunting Area trip with official access, seasonal trout stocking, warmwater species, and current area rules.",
};

export default function BlueRiverPage() {
  return (
    <>
      <a className="skip-link" href="#guide-content">Skip to river guide</a>
      <header className="nav-shell"><div className="nav-wrap"><a className="brand" href="/">FISH THE FIFTY</a><nav aria-label="Main navigation"><a href="/states">States</a><a href="/winter-trout">Winter Trout</a><a href="/#challenges">Challenges</a><a href="/#progress">My Progress</a></nav></div></header>
      <main id="guide-content" className="river-guide">
        <div className="breadcrumb"><a href="/states">States</a><span aria-hidden="true"> / </span><a href="/states/oklahoma">Oklahoma</a><span aria-hidden="true"> / </span><span>Blue River</span></div>
        <section className="page-hero river-hero"><div className="page-hero-inner river-hero-grid"><div><p className="eyebrow">OKLAHOMA · WATER GUIDE 05</p><h1>Blue River.</h1><p className="lead">A 3,367-acre public fishing area near Tishomingo where wadable stream water, seasonal rainbow trout, smallmouth bass, and channel catfish share the same adventure.</p><div className="actions"><a className="btn primary" href="#access">Find access</a><a className="btn secondary" href="#fishing">Plan your fishing</a></div></div><aside className="river-brief" aria-label="River at a glance"><p className="eyebrow">AT A GLANCE</p><dl><div><dt>Where</dt><dd>Johnston County</dd></div><div><dt>Nearest town</dt><dd>8 mi northeast of Tishomingo</dd></div><div><dt>Stream access</dt><dd>6.25 wadable miles</dd></div><div><dt>Seasonal focus</dt><dd>Rainbows Nov–mid-March</dd></div></dl><a href={sources.area.url}>ODWC area listing <span aria-hidden="true">↗</span></a></aside></div></section>

        <div className="guide-shell">
          <aside className="stocking-notice" aria-labelledby="season-heading"><p className="eyebrow">SEASONAL UPDATE · <time dateTime={checkedDate}>{checkedLabel}</time></p><h2 id="season-heading">Trout in winter, warmwater all year.</h2><p>ODWC designates Blue River as a trout area from November through mid-March and stocks rainbow trout weekly during that period. In spring and summer, channel catfish are regularly stocked, while the area’s bass and stream habitat keep the rest of the year interesting.</p><a className="text-link" href={sources.area.url}>Read the current ODWC listing <span aria-hidden="true">↗</span></a></aside>
          <nav className="guide-jump-links" aria-label="On this page"><a href="#access">Access & maps</a><a href="#fishing">Species & tactics</a><a href="#rules">Season & rules</a><a href="#conditions">Before you go</a><a href="#sources">Sources</a></nav>

          <section id="access" className="guide-section"><div className="guide-section-heading"><div><p className="eyebrow">01 / GET TO THE WATER</p><h2>Choose your approach.</h2></div><a className="text-link" href={sources.map.url}>Area map (PDF) <span aria-hidden="true">↗</span></a></div><p className="guide-intro">Blue River is an ODWC-managed public fishing and hunting area with primitive campgrounds, latrines, and 6.25 miles of wadable stream access. Map buttons search the named approach; use the official map and posted signs to confirm the boundary.</p><div className="access-grid">{accessAreas.map((area, index) => <article className="access-card" key={area.id}><div className="access-card-top"><span className="state-pill">{area.type}</span><span className="access-number" aria-hidden="true">0{index + 1}</span></div><h3>{area.name}</h3><p>{area.description}</p><p className="access-note">{area.note}</p><div className="map-links"><a href={googleMapSearch(area.mapQuery)} aria-label={`Search Google Maps for ${area.name}`}>Google Maps <span aria-hidden="true">↗</span></a><a href={appleMapSearch(area.mapQuery)} aria-label={`Search Apple Maps for ${area.name}`}>Apple Maps <span aria-hidden="true">↗</span></a></div></article>)}</div></section>

          <section id="fishing" className="guide-section fishing-grid"><div><p className="eyebrow">02 / PLAN YOUR FISHING</p><h2>Small water, multiple seasons.</h2><p className="guide-intro">ODWC identifies smallmouth, spotted, and largemouth bass, channel catfish, and rainbow trout as species of interest. The official report describes bass around brush, channels, rocks, shorelines, and weed beds, with channel catfish using similar structure.</p><div className="species-list">{["Rainbow trout", "Smallmouth bass", "Spotted bass", "Largemouth bass", "Channel catfish"].map((fish) => <span key={fish}>{fish}</span>)}</div><p className="source-note"><a href={sources.area.url}>ODWC species & report notes <span aria-hidden="true">↗</span></a></p><div className="tackle-note"><h3>Fish the Fifty starting setup</h3><p>For your fly-focused walk-and-wade days, start with the 5-weight: a 7½-foot 4X leader, foam spiders or small poppers around warmwater cover, then a Woolly Bugger, Hare’s Ear, or small streamer when trout or bass are looking down. Keep the approach quiet and cover pools, riffles, rocks, and wood before moving.</p><a className="text-link" href={sources.trail.url}>TravelOK Blue River notes <span aria-hidden="true">↗</span></a></div></div><div className="season-notes"><article><span className="eyebrow">NOVEMBER → MID-MARCH</span><h3>Follow the trout season</h3><p>Rainbow trout are stocked weekly during the designated trout season, but stocking schedules and catch conditions can change. Check the current area page before traveling.</p></article><article><span className="eyebrow">SPRING & SUMMER</span><h3>Switch to warmwater</h3><p>ODWC regularly stocks channel catfish in the warmer months. Bass remain a practical fly target around rocks, channels, brush, and shoreline cover.</p></article><article><span className="eyebrow">WALK & WADE</span><h3>Read the water</h3><p>Blue River is a public, wadable stream area—not a single paved access point. Carry a simple plan for moving between legal access, shade, and deeper pools.</p></article><div className="resource-links"><a href={sources.trail.url}>Oklahoma Fishing Trail ↗</a><a href={sources.reports.url}>ODWC fishing reports ↗</a><a href={sources.usgs.url}>USGS water data ↗</a></div></div></section>

          <section id="rules" className="guide-section"><p className="eyebrow">03 / SEASON & RULES</p><h2>Know the area restrictions.</h2><div className="rules-grid"><article className="rule-card special-rule"><span className="eyebrow">TROUT SEASON</span><h3>One rod per person</h3><p>During trout season, ODWC lists one rod and reel or one pole and line per person. Snagging is closed, and trout regulations include no culling.</p><a className="text-link" href={sources.troutRules.url}>Read trout regulations ↗</a></article><article className="rule-card special-rule"><span className="eyebrow">CATFISH & CRAPPIE</span><h3>Six combined per day</h3><p>The Blue River area listing gives a combined daily limit of six channel and/or blue catfish, and six combined crappie with no size limit.</p><a className="text-link" href={sources.area.url}>Verify area limits ↗</a></article><article className="rule-card"><h3>Department-area rules</h3><p>All users need a fishing or hunting license or a Wildlife Conservation Passport unless exempt. Vehicular access is closed from 10 p.m. to 6 a.m.; camping is limited to designated areas and 14 days in a 30-day period.</p><div className="resource-links"><a href={sources.areaRules.url}>Area restrictions ↗</a><a href={sources.license.url}>Oklahoma license ↗</a></div></article><article className="rule-card"><h3>Nonresident check-in</h3><p>ODWC says nonresidents accessing certain public fishing areas must check in and out. The process has no additional cost and no annual check-in limit.</p><div className="resource-links"><a href={sources.checkIn.url}>Check-in instructions ↗</a><a href={sources.area.url}>Blue River listing ↗</a></div></article></div></section>

          <section id="conditions" className="guide-section conditions-section"><p className="eyebrow">04 / BEFORE YOU LEAVE</p><h2>Check the current report.</h2><p className="guide-intro">Blue River conditions can change quickly with season, rain, temperature, and access. ODWC links a current area report and USGS water data; use those sources together with the area map and your own assessment of footing and water level.</p><div className="condition-grid"><a className="condition-card" href={sources.area.url}><span>AREA REPORT</span><h3>ODWC Blue River PFHA <span aria-hidden="true">↗</span></h3><p>Review the current report, species notes, contacts, stocking season, and regulations.</p></a><a className="condition-card" href={sources.usgs.url}><span>WATER DATA</span><h3>USGS Blue River <span aria-hidden="true">↗</span></h3><p>Open the official monitoring location near Connerville before wading.</p></a><a className="condition-card" href={sources.map.url}><span>BOUNDARIES</span><h3>ODWC area map <span aria-hidden="true">↗</span></h3><p>Use the map to confirm entrances, public boundaries, and designated access.</p></a></div><p className="condition-footnote">ODWC Blue River fisheries management: (580) 920-5773 · Johnston County wardens are listed on the official area page.</p></section>

          <section id="sources" className="guide-section source-section"><div><p className="eyebrow">OFFICIAL SOURCES</p><h2>Plan with current information.</h2><p>Guide checked <time dateTime={checkedDate}>{checkedLabel}</time>. Stocking, reports, regulations, and access conditions can change. The fly setup above is a Fish the Fifty starting point, not an official regulation.</p></div><ul>{[sources.area, sources.map, sources.troutRules, sources.areaRules, sources.checkIn, sources.license, sources.reports, sources.trail, sources.usgs].map((source) => <li key={source.url}><a href={source.url}>{source.label} <span aria-hidden="true">↗</span></a></li>)}</ul></section>
          <div className="guide-return"><a className="btn primary" href="/states/oklahoma">← Back to Oklahoma</a><a className="text-link" href="/states">Explore all 50 states →</a></div>
        </div>
      </main>
      <footer><strong>FISH THE FIFTY</strong><span>Built for anglers who want to fish farther.</span></footer>
    </>
  );
}
