import type { Metadata } from "next";
import MontanaTracker from "./tracker";
export const metadata: Metadata = { title: "Montana Fish Records | Fish the Fifty", description: "Plan a Montana state record fish attempt with official FWP weighing, identification, fishing access, and restriction resources." };
const links = {
  records: "https://fwp.mt.gov/fish/anglingData/records",
  fish: "https://fwp.mt.gov/fish",
  rules: "https://fwp.mt.gov/fish/regulations",
  restrictions: "https://fwp.mt.gov/news/current-closures-restrictions/waterbody-closures",
  license: "https://fwp.mt.gov/fish/license/",
};
export default function MontanaChallengePage() {
  return <main><header className="nav-shell"><div className="nav-wrap"><a className="brand" href="/">FISH THE FIFTY</a><nav aria-label="Main navigation"><a href="/states">States</a><a href="/#challenges">Challenges</a><a href="/members">My Progress</a></nav></div></header>
    <div className="breadcrumb"><a href="/states">States</a><span aria-hidden="true"> / </span><span>Montana</span></div>
    <section className="page-hero challenge-hero"><div className="page-hero-inner"><p className="eyebrow">MONTANA · FISH, WILDLIFE &amp; PARKS</p><h1>Montana Fish<br />Records.</h1><p className="lead">Pick a species, compare Montana’s standing record, and plan a legal fishing trip. If you land a potential record, preserve the fish, obtain a witnessed certified weight, and have FWP verify the species.</p><div className="state-facts"><span>Official state record table</span><span>Certified weight</span><span>FWP species identification</span></div><div className="actions"><a className="btn primary" href="#record-path">Plan a record attempt ↓</a><a className="btn secondary" href={links.records} target="_blank" rel="noreferrer">Current Montana records ↗</a></div></div></section>
    <section className="section challenge-layout" id="record-path"><div><p className="eyebrow">FWP RECORD PROCESS</p><h2>Know what to do when it counts.</h2><ol className="challenge-steps"><li><strong>Check the live record table.</strong><span>Compare the current weight for your species. Records can change, so check again before your trip.</span></li><li><strong>Keep the fish cool and intact.</strong><span>FWP says not to clean or freeze a potential record; keep it on ice and take a photograph.</span></li><li><strong>Get a witnessed certified weight.</strong><span>Use a certified scale, obtain a weight receipt and an affidavit from store personnel if an FWP official is not present. Measure length and girth.</span></li><li><strong>Contact FWP for identification.</strong><span>A Fisheries Biologist or Manager must positively identify the species. Complete and send the official Fish Record Form.</span></li></ol><a className="btn primary" href={links.records} target="_blank" rel="noreferrer">Official records and form ↗</a></div><aside className="challenge-side"><p className="eyebrow">BEFORE YOU CAST</p><h2>Check the exact water.</h2><p>Montana’s fishing rules vary by water and species. FWP also posts current closures and daily time restrictions, including “hoot owl” periods on affected waters.</p><p>Confirm the required licenses and Aquatic Invasive Species Prevention Pass. If the species must be released, follow its current handling rules; the record process described here involves a fish retained for certified weighing and verification.</p><div className="actions"><a className="btn secondary" href={links.rules} target="_blank" rel="noreferrer">Fishing regulations ↗</a><a className="btn secondary" href={links.restrictions} target="_blank" rel="noreferrer">Current restrictions ↗</a></div></aside></section>
    <section className="section"><div className="section-heading"><p className="eyebrow">THREE USEFUL OFFICIAL RESOURCES</p><h2>Research the fish and the water.</h2></div><div className="card-grid"><article className="challenge-card"><span className="state-pill">RECORDS</span><h3>Standing fish records</h3><p>FWP’s live table includes species, length, weight, catch date, and water. Use it as the current benchmark.</p><a href={links.records} target="_blank" rel="noreferrer">Compare species ↗</a></article><article className="challenge-card"><span className="state-pill">ACCESS</span><h3>FishMT resources</h3><p>Explore Montana fishing access, waters, and angling resources through FWP.</p><a href={links.fish} target="_blank" rel="noreferrer">Explore fishing ↗</a></article><article className="challenge-card"><span className="state-pill">RULES</span><h3>Licenses and regulations</h3><p>Confirm your license, species limits, and special rules for the water you plan to fish.</p><a href={links.license} target="_blank" rel="noreferrer">License basics ↗</a></article></div></section>
    <section className="section" id="tracker"><div className="section-heading"><p className="eyebrow">YOUR PRIVATE WATCH LIST</p><h2>Choose species to research.</h2><p>Keep target fish in this browser, then compare each with FWP’s current record table and local rules.</p></div><MontanaTracker /></section>
    <section className="section final-cta challenge-final"><p className="eyebrow">READY TO PLAN?</p><h2>Start with Montana’s current records.</h2><p>Find your species, check the water’s rules and closures, and keep FWP’s record instructions handy if you land an exceptional fish.</p><div className="actions"><a className="btn primary" href={links.records} target="_blank" rel="noreferrer">Open Montana Fish Records ↗</a><a className="btn secondary" href="/states">Back to all states</a></div></section><footer><strong>FISH THE FIFTY</strong><span>Built for anglers who want to fish farther.</span></footer>
  </main>;
}
