import type { Metadata } from "next";
import IowaTracker from "./tracker";
import { species } from "./species";
export const metadata: Metadata = { title: "Iowa Master Angler & First Fish | Fish the Fifty", description: "Explore Iowa's Master Angler length standards, Silver and Gold milestones, Species Specialist, and First Fish recognition." };
const official = "https://www.iowadnr.gov/things-do/fishing/master-angler-first-fish";
const portal = "https://programs.iowadnr.gov/masterangler";
export default function IowaChallengePage() {
  return <main><header className="nav-shell"><div className="nav-wrap"><a className="brand" href="/">FISH THE FIFTY</a><nav aria-label="Main navigation"><a href="/states">States</a><a href="/#challenges">Challenges</a><a href="/#progress">My Progress</a></nav></div></header>
    <div className="breadcrumb"><a href="/states">States</a><span aria-hidden="true"> / </span><span>Iowa</span></div>
    <section className="page-hero challenge-hero"><div className="page-hero-inner"><p className="eyebrow">IOWA · DEPARTMENT OF NATURAL RESOURCES</p><h1>Iowa Master<br />Angler.</h1><p className="lead">Catch a fish that meets Iowa’s published species length to earn Master Angler recognition. Keep exploring for Silver, Gold, or a five-catch Species Specialist award.</p><div className="state-facts"><span>{species.length} listed species groups</span><span>5 species · Silver</span><span>10 species · Gold</span></div><div className="actions"><a className="btn primary" href="#sizes">Find a qualifying size ↓</a><a className="btn secondary" href={official} target="_blank" rel="noreferrer">Official Iowa DNR rules ↗</a></div></div></section>
    <section className="section"><div className="section-heading"><p className="eyebrow">FOUR WAYS TO RECOGNITION</p><h2>Choose your next milestone.</h2></div><div className="card-grid"><article className="challenge-card"><span className="state-pill">1 QUALIFYING FISH</span><h3>Master Angler</h3><p>One fish meeting its species’ minimum length earns a certificate with picture and a car or boat decal.</p></article><article className="challenge-card"><span className="state-pill">5 DIFFERENT SPECIES</span><h3>Silver Master Angler</h3><p>Qualifying catches from five different species earn a certificate, Silver Medallion, and decal.</p></article><article className="challenge-card"><span className="state-pill">10 DIFFERENT SPECIES</span><h3>Gold Master Angler</h3><p>Qualifying catches from ten different species earn a certificate, Gold Medallion, and decal.</p></article><article className="challenge-card"><span className="state-pill">5 OF ONE SPECIES</span><h3>Species Specialist</h3><p>Five fish of the same species meeting the minimum length earn a species-specific certificate.</p></article></div></section>
    <section className="section challenge-layout"><div><p className="eyebrow">OFFICIAL ENTRY RULES</p><h2>Photograph the measurement.</h2><ol className="challenge-steps"><li><strong>Fish legally with a valid Iowa license.</strong><span>Follow current regulations for the water and species. A released fish may still qualify.</span></li><li><strong>Meet the species minimum.</strong><span>Measure from snout tip to tail tip, with special fork-length methods for paddlefish and sturgeon.</span></li><li><strong>Take both required photos.</strong><span>Show the angler with the catch and the fish on a flat surface beside a standard ruler or measuring tape with the length visible.</span></li><li><strong>Submit to Iowa DNR.</strong><span>The agency rejects entries without a length photo or those using AI-based measuring devices. A potential new state record must be verified by a DNR Fisheries official.</span></li></ol><a className="btn primary" href={portal} target="_blank" rel="noreferrer">Submit a Master Angler catch ↗</a></div><aside className="challenge-side"><p className="eyebrow">FIRST FISH</p><h2>Celebrate the beginning.</h2><p>Iowa’s First Fish program offers a frameable certificate to commemorate an angler’s first successfully landed fish. Species, fish size, and angler age do not matter.</p><a className="btn secondary" href={portal} target="_blank" rel="noreferrer">First Fish certificate ↗</a></aside></section>
    <section className="section qualification-section alabama-size-section" id="sizes"><div className="section-heading"><p className="eyebrow">OFFICIAL MASTER ANGLER LENGTHS</p><h2>Compare all {species.length} listed groups.</h2><p>Minimum total lengths are shown in inches. Check Iowa DNR’s live table before submitting a catch; special measurement methods apply to paddlefish and sturgeon.</p></div><div className="qualification-table-wrap alabama-table-wrap"><table><caption className="visually-hidden">Iowa Master Angler minimum qualifying lengths by species</caption><thead><tr><th scope="col">Species</th><th scope="col">Minimum length</th></tr></thead><tbody>{species.map(([name, inches]) => <tr key={name}><th scope="row">{name}</th><td>{inches} inches</td></tr>)}</tbody></table></div><p className="alabama-threshold-note">Some rows group more than one species under one DNR criterion, including goldeye/mooneye and selected sucker species. The official DNR table controls identification and awards.</p><a className="btn primary" href={official} target="_blank" rel="noreferrer">Review Iowa’s current criteria ↗</a></section>
    <section className="section" id="tracker"><div className="section-heading"><p className="eyebrow">YOUR PRIVATE CHECKLIST</p><h2>Track your species and repeat catches.</h2><p>Mark catches that appear to meet the published length. The list saves only in this browser and does not submit an application.</p></div><IowaTracker /></section>
    <section className="section final-cta challenge-final"><p className="eyebrow">READY TO START?</p><h2>Choose one species and take a ruler.</h2><p>Check the current fishing rules, record a clear measurement, and submit a qualifying catch through Iowa DNR.</p><div className="actions"><a className="btn primary" href={portal} target="_blank" rel="noreferrer">Open Iowa’s angler portal ↗</a><a className="btn secondary" href="/states">Back to all states</a></div></section><footer><strong>FISH THE FIFTY</strong><span>Built for anglers who want to fish farther.</span></footer>
  </main>;
}
