import type { Metadata } from "next";
import { accessAreas, appleMapSearch, checkedDate, checkedLabel, googleMapSearch, sources } from "./guide-data";

export const metadata: Metadata = {
  title: "Lower Mountain Fork River Fishing Guide | Fish the Fifty",
  description: "Plan a Lower Mountain Fork River trout trip near Broken Bow, Oklahoma with official access, regulations, stocking, and park resources.",
};

export default function LowerMountainForkPage() {
  return (
    <>
      <a className="skip-link" href="#guide-content">Skip to river guide</a>
      <header className="nav-shell"><div className="nav-wrap"><a className="brand" href="/">FISH THE FIFTY</a><nav aria-label="Main navigation"><a href="/states">States</a><a href="/#challenges">Challenges</a><a href="/#progress">My Progress</a></nav></div></header>
      <main id="guide-content" className="river-guide">
        <div className="breadcrumb"><a href="/states">States</a><span aria-hidden="true"> / </span><a href="/states/oklahoma">Oklahoma</a><span aria-hidden="true"> / </span><span>Lower Mountain Fork</span></div>
        <section className="page-hero river-hero">
          <div className="page-hero-inner river-hero-grid">
            <div><p className="eyebrow">OKLAHOMA · WATER GUIDE 02</p><h1>Lower Mountain<br />Fork River.</h1><p className="lead">A cold-water trout tailwater below Broken Bow Lake, flowing through Beavers Bend State Park and the Ouachita foothills.</p><div className="actions"><a className="btn primary" href="#access">Find public access</a><a className="btn secondary" href="#fishing">Plan your fishing</a></div></div>
            <aside className="river-brief" aria-label="River at a glance"><p className="eyebrow">AT A GLANCE</p><dl><div><dt>Where</dt><dd>Broken Bow, Oklahoma</dd></div><div><dt>Designated trout reach</dt><dd>12 miles</dd></div><div><dt>Reach boundaries</dt><dd>Spillway → US 70</dd></div><div><dt>Access in this guide</dt><dd>{accessAreas.length} named areas</dd></div></dl><a href={sources.troutAreas.url}>ODWC area information <span aria-hidden="true">↗</span></a></aside>
          </div>
        </section>

        <div className="guide-shell">
          <aside className="stocking-notice" aria-labelledby="stocking-heading"><p className="eyebrow">TRIP PLANNING UPDATE · <time dateTime={checkedDate}>{checkedLabel}</time></p><h2 id="stocking-heading">Year-round trout area, changing conditions</h2><p>ODWC lists year-round stocking for Mountain Fork at Beavers Bend, but stocking is tentative. Water temperature, dissolved oxygen, flooding, fish availability, and road conditions can change the schedule.</p><a className="text-link" href={sources.troutInfo.url}>Read ODWC stocking guidance <span aria-hidden="true">↗</span></a></aside>
          <nav className="guide-jump-links" aria-label="On this page"><a href="#access">Access & maps</a><a href="#fishing">Species & seasons</a><a href="#rules">Licenses & rules</a><a href="#conditions">Conditions</a><a href="#sources">Sources</a></nav>

          <section id="access" className="guide-section"><div className="guide-section-heading"><div><p className="eyebrow">01 / GET TO THE WATER</p><h2>Choose your access.</h2></div><a className="text-link" href={sources.troutAreas.url}>ODWC trout map & details <span aria-hidden="true">↗</span></a></div><p className="guide-intro">ODWC identifies these public access areas along the designated reach. Map buttons search the named place; use the agency’s description, park rules, and posted signs to locate the public entrance.</p><div className="access-grid">{accessAreas.map((area, index) => <article className="access-card" key={area.id}><div className="access-card-top"><span className="state-pill">{area.type}</span><span className="access-number" aria-hidden="true">0{index + 1}</span></div><h3>{area.name}</h3><p>{area.description}</p><p className="access-note">{area.note}</p><div className="map-links"><a href={googleMapSearch(area.mapQuery)} aria-label={`Search Google Maps for ${area.name}`}>Google Maps <span aria-hidden="true">↗</span></a><a href={appleMapSearch(area.mapQuery)} aria-label={`Search Apple Maps for ${area.name}`}>Apple Maps <span aria-hidden="true">↗</span></a></div></article>)}</div></section>

          <section id="fishing" className="guide-section fishing-grid"><div><p className="eyebrow">02 / PLAN YOUR FISHING</p><h2>Rainbows, browns, and mountain water.</h2><p className="guide-intro">ODWC identifies rainbow and brown trout as the main introduced trout species. Browns are stocked in the Lower Mountain Fork below Broken Bow Dam when available.</p><div className="species-list">{["Rainbow trout", "Brown trout", "Largemouth bass", "Smallmouth bass", "Spotted bass", "Sunfish"].map((fish) => <span key={fish}>{fish}</span>)}</div><p className="source-note"><a href={sources.troutInfo.url}>ODWC trout information & stocking notes <span aria-hidden="true">↗</span></a></p><div className="tackle-note"><h3>Match the hatch</h3><p>ODWC’s Lower Mountain Fork table includes caddis, midges, mayflies, and other patterns. Treat it as a starting point, then match the water and current conditions.</p><a className="text-link" href={sources.troutInfo.url}>View the official fly table <span aria-hidden="true">↗</span></a></div></div><div className="season-notes"><article><span className="eyebrow">YEAR-ROUND DESIGNATION</span><h3>Stocking is not a guarantee</h3><p>The area is designated for year-round trout stocking, but ODWC says schedules are tentative and may be curtailed by temperature, oxygen, floods, roads, or fish availability.</p></article><article><span className="eyebrow">PARK WATER</span><h3>Start at Beavers Bend</h3><p>About five miles of the designated trout stream lie within the state park, where bank access, camping, and cabins are available.</p></article><article><span className="eyebrow">CLEAN YOUR GEAR</span><h3>Help prevent didymo spread</h3><p>ODWC reports didymo in the Lower Mountain Fork. Clean and dry waders and fishing equipment after fishing this river.</p></article><div className="resource-links"><a href={sources.troutTips.url}>ODWC trout fishing tips ↗</a><a href={sources.reports.url}>Official fishing reports ↗</a><a href={sources.park.url}>Beavers Bend State Park ↗</a></div></div></section>

          <section id="rules" className="guide-section"><p className="eyebrow">03 / KNOW THE RULES</p><h2>Special trout-area limits.</h2><div className="rules-grid"><article className="rule-card"><h3>License & tackle</h3><p>A fishing license is required unless exempt. The Lower Mountain Fork trout area requires barbless hooks, allows bait, and prohibits cast netting. General trout rules also limit anglers to one rod and reel or pole and line.</p><div className="resource-links"><a href={sources.license.url}>Buy an Oklahoma license ↗</a><a href={sources.troutRules.url}>Official trout regulations ↗</a></div></article><article className="rule-card special-rule"><span className="eyebrow">AREA 1</span><h3>Spillway to Old State Park Dam</h3><p>ODWC lists a daily aggregate limit of three trout. Only one may be a rainbow trout over 25 inches, and only one may be a brown trout over 30 inches.</p><a className="text-link" href={sources.troutAreas.url}>Verify the current area map ↗</a></article><article className="rule-card special-rule"><span className="eyebrow">AREA 2</span><h3>Old State Park Dam to US 70</h3><p>ODWC lists a one-fish daily limit for rainbow trout over 25 inches and a one-fish daily limit for brown trout over 30 inches. These count toward the aggregate area limit.</p><a className="text-link" href={sources.troutAreas.url}>Verify the current area map ↗</a></article><article className="rule-card"><h3>Respect the park</h3><p>Camping and cabins are available in Beavers Bend State Park. Confirm current park fees, reservations, access, and closures before your trip.</p><a className="text-link" href={sources.park.url}>Park information ↗</a></article></div></section>

          <section id="conditions" className="guide-section conditions-section"><p className="eyebrow">04 / BEFORE YOU LEAVE</p><h2>Check current conditions.</h2><p className="guide-intro">The official sources below are the right place to check changing stocking plans, regulations, reports, and park conditions. Fish the Fifty does not display live flow readings or certify wading safety.</p><div className="condition-grid"><a className="condition-card" href={sources.troutInfo.url}><span>STOCKING</span><h3>ODWC trout updates <span aria-hidden="true">↗</span></h3><p>Review the current stocking guidance and the weekly reports.</p></a><a className="condition-card" href={sources.reports.url}><span>RECENT REPORTS</span><h3>Fishing reports <span aria-hidden="true">↗</span></h3><p>Check the report date before treating a catch note as current.</p></a><a className="condition-card" href={sources.park.url}><span>PARK STATUS</span><h3>Beavers Bend <span aria-hidden="true">↗</span></h3><p>Confirm current park access, facilities, reservations, and closures.</p></a></div></section>

          <section id="sources" className="guide-section source-section"><div><p className="eyebrow">OFFICIAL SOURCES</p><h2>Plan with current information.</h2><p>Guide checked <time dateTime={checkedDate}>{checkedLabel}</time>. Regulations, stocking notices, and park conditions can change. The linked agencies provide the latest information.</p></div><ul>{[sources.troutAreas, sources.troutInfo, sources.troutRules, sources.troutTips, sources.reports, sources.park, sources.license].map((source) => <li key={source.url}><a href={source.url}>{source.label} <span aria-hidden="true">↗</span></a></li>)}</ul></section>
          <div className="guide-return"><a className="btn primary" href="/states/oklahoma">← Back to Oklahoma</a><a className="text-link" href="/states">Explore all 50 states →</a></div>
        </div>
      </main>
      <footer><strong>FISH THE FIFTY</strong><span>Built for anglers who want to fish farther.</span></footer>
    </>
  );
}
