import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Hawaii Island Waters Challenge | Fish the Fifty",
  description: "A self-guided Hawaii fishing checklist with official DAR marine and freshwater rules and the independently maintained Hawaii Fishing News records.",
};

const links = {
  rules: "https://dlnr.hawaii.gov/dar/fishing/fishing-regulations/",
  permits: "https://dlnr.hawaii.gov/dar/fishing/licenses-and-permits/",
  freshwater: "https://dlnr.hawaii.gov/dar/fishing/freshwater-fishing/",
  sportFish: "https://dlnr.hawaii.gov/dar/fishing/freshwater-fishing/introduced-sport-fishes/",
  records: "https://www.hawaiifishingnews.com/records.html",
};

export default function HawaiiChallengePage() {
  return <main>
    <header className="nav-shell"><div className="nav-wrap"><a className="brand" href="/">FISH THE FIFTY</a><nav aria-label="Main navigation"><a href="/states">States</a><a href="/#challenges">Challenges</a><a href="/#progress">My Progress</a></nav></div></header>
    <div className="breadcrumb"><a href="/states">States</a><span aria-hidden="true"> / </span><span>Hawaii</span></div>
    <section className="page-hero challenge-hero"><div className="page-hero-inner"><p className="eyebrow">HAWAII · ISLAND WATERS</p><h1>Hawaii Island<br />Waters Challenge.</h1><p className="lead">Explore two sides of island fishing: a legal marine outing and a freshwater sport fish outing. This is a self-guided Fish the Fifty checklist, not an award administered by Hawaii’s Division of Aquatic Resources (DAR).</p><div className="state-facts"><span>2 water types</span><span>Self-guided checklist</span><span>Check current DAR rules</span></div><div className="actions"><a className="btn primary" href="#checklist">Explore the checklist ↓</a><a className="btn secondary" href={links.rules} target="_blank" rel="noreferrer">Official fishing rules ↗</a></div></div></section>
    <section className="section challenge-layout" id="checklist"><div><p className="eyebrow">YOUR TWO-WATER CHECKLIST</p><h2>Fish the coast. Explore fresh water.</h2><ol className="challenge-steps"><li><strong>Plan a marine fishing outing.</strong><span>Choose a legal location and method, identify your target species, and check the area rules, seasons, size limits, and license requirements before casting.</span></li><li><strong>Try an introduced freshwater sport fish.</strong><span>DAR lists bass, tucunare, catfish, trout, and other introduced sport fish. Check the water’s access and rules, and obtain the required Freshwater Game Fishing License.</span></li><li><strong>Record your own progress.</strong><span>Note the island, water, species, date, and a photo of each catch. There is no Fish the Fifty submission or state-issued certificate for this checklist.</span></li></ol><a className="btn primary" href={links.freshwater} target="_blank" rel="noreferrer">Explore DAR freshwater fishing ↗</a></div><aside className="challenge-side"><p className="eyebrow">BEFORE YOU FISH</p><h2>Rules vary by place and species.</h2><p>DAR publishes statewide species rules and regulated-area provisions. Public access is separate from fishing regulations; confirm permission to reach and fish a particular shore or freshwater site.</p><p>Licenses and permits depend on the activity. DAR requires a Freshwater Game Fishing License to take introduced freshwater sport fish and lists a nonresident recreational marine license among its permit types.</p><a className="btn secondary" href={links.permits} target="_blank" rel="noreferrer">Check licenses and permits ↗</a></aside></section>
    <section className="section"><div className="section-heading"><p className="eyebrow">CHOOSE YOUR WATER</p><h2>Start with the official guides.</h2><p>Use DAR’s current pages when choosing a fish, a method, and a place. Requirements can change, so revisit the rules immediately before your trip.</p></div><div className="card-grid"><article className="challenge-card"><span className="state-pill">MARINE</span><h3>Ocean rules</h3><p>Review regulated species, methods, and area-specific restrictions for your planned marine outing.</p><a href={links.rules} target="_blank" rel="noreferrer">DAR regulations ↗</a></article><article className="challenge-card"><span className="state-pill">FRESHWATER</span><h3>Introduced sport fish</h3><p>Explore DAR species profiles and choose a legal freshwater target suited to your trip.</p><a href={links.sportFish} target="_blank" rel="noreferrer">DAR species guide ↗</a></article><article className="challenge-card"><span className="state-pill">PERMITS</span><h3>License check</h3><p>Confirm which current licenses apply to your residency, water, and intended fishing activity.</p><a href={links.permits} target="_blank" rel="noreferrer">DAR permits ↗</a></article></div></section>
    <section className="section challenge-layout"><div><p className="eyebrow">SEPARATE RECORD PATH</p><h2>Chase a published Hawaii record.</h2><p>Hawaii Fishing News maintains a Hawaii State Record Fish listing and provides an application. This is an independently run publication’s record program, separate from the self-guided checklist above and from a DAR award. Check its current records and application instructions directly before planning a submission.</p><a className="btn primary" href={links.records} target="_blank" rel="noreferrer">Hawaii Fishing News records ↗</a></div><aside className="challenge-side"><p className="eyebrow">KEEP IT LEGAL</p><h2>A record never overrides the rules.</h2><p>Check DAR’s current species, area, gear, and license provisions before targeting or retaining a fish. The publisher’s record listing does not grant fishing access or permission to keep a catch.</p><a className="btn secondary" href={links.rules} target="_blank" rel="noreferrer">Review DAR regulations ↗</a></aside></section>
    <section className="section final-cta challenge-final"><p className="eyebrow">READY TO PLAN?</p><h2>Pick a water. Check the rules. Go fish.</h2><p>Build your own Hawaii checklist with a marine and freshwater outing, and use DAR’s live resources for the details that matter at your chosen site.</p><div className="actions"><a className="btn primary" href={links.rules} target="_blank" rel="noreferrer">Open Hawaii fishing rules ↗</a><a className="btn secondary" href="/states">Back to all states</a></div></section>
    <footer><strong>FISH THE FIFTY</strong><span>Built for anglers who want to fish farther.</span></footer>
  </main>;
}
