import type { Metadata } from "next";
import NewYorkTracker from "./tracker";
import { species } from "./species";
export const metadata: Metadata = { title: "New York Angler Achievement Awards | Fish the Fifty", description: "Explore New York DEC adult and youth freshwater award lengths, state-record rules, and a private species checklist." };
const official = "https://dec.ny.gov/things-to-do/freshwater-fishing/angler-achievement-awards-program";
const rules = "https://dec.ny.gov/things-to-do/freshwater-fishing/regulations";
export default function NewYorkChallengePage() {
  return <main><header className="nav-shell"><div className="nav-wrap"><a className="brand" href="/">FISH THE FIFTY</a><nav aria-label="Main navigation"><a href="/states">States</a><a href="/#challenges">Challenges</a><a href="/members">My Progress</a></nav></div></header>
    <div className="breadcrumb"><a href="/states">States</a><span aria-hidden="true"> / </span><span>New York</span></div>
    <section className="page-hero challenge-hero"><div className="page-hero-inner"><p className="eyebrow">NEW YORK · DEPARTMENT OF ENVIRONMENTAL CONSERVATION</p><h1>New York Angler<br />Achievement Awards.</h1><p className="lead">Catch a qualifying freshwater fish and earn a species-specific sticker. New York has separate adult and youth lengths, plus a state-record award for an all-time catch.</p><div className="state-facts"><span>40 eligible species</span><span>Adult and youth lengths</span><span>Enter within 30 days</span></div><div className="actions"><a className="btn primary" href="#lengths">See qualifying lengths ↓</a><a className="btn secondary" href={official} target="_blank" rel="noreferrer">Official DEC program ↗</a></div></div></section>
    <section className="section challenge-layout"><div><p className="eyebrow">ANGLER &amp; YOUTH AWARDS</p><h2>A memorable fish earns a sticker.</h2><ol className="challenge-steps"><li><strong>Fish legally during the open season.</strong><span>Use angling or ice fishing in New York waters and follow the current freshwater rules.</span></li><li><strong>Check the correct length.</strong><span>Measure nose to tail. Anglers 16 and older use adult standards; those under 16 use youth standards. Some species have water-specific thresholds.</span></li><li><strong>Photograph the fish.</strong><span>Take a side-view image of the entire fish and show it beside a ruler, tape, or other object of known size.</span></li><li><strong>Submit within 30 days.</strong><span>Use DEC’s official entry form. Sticker awards are limited to one per angler per species each year.</span></li></ol><a className="btn primary" href={official} target="_blank" rel="noreferrer">Official rules and entry form ↗</a></div><aside className="challenge-side"><p className="eyebrow">STATE RECORD PATH</p><h2>For an all-time fish.</h2><p>New York recognizes records for 39 eligible species. A new catch must exceed the standing record by at least one ounce, be weighed on a certified scale with an independent witness, and be kept for examination by a DEC Fisheries Biologist before cutting.</p><p>State-record entries require DEC’s printable form. Confirm the current record and arrange proper verification promptly.</p><a className="btn secondary" href={official} target="_blank" rel="noreferrer">Records and verification ↗</a></aside></section>
    <section className="section qualification-section alabama-size-section" id="lengths"><div className="section-heading"><p className="eyebrow">OFFICIAL MINIMUM QUALIFYING LENGTHS</p><h2>Compare all 40 species.</h2><p>Adult and youth lengths are in inches. For species with different water categories, the table states each applicable threshold; check DEC’s full rules for the exact water.</p></div><div className="qualification-table-wrap alabama-table-wrap"><table><caption className="visually-hidden">New York freshwater Angler Achievement Award minimum lengths</caption><thead><tr><th scope="col">Species</th><th scope="col">Adult · 16+</th><th scope="col">Youth · under 16</th></tr></thead><tbody>{species.map(([name, adult, youth]) => <tr key={name}><th scope="row">{name}</th><td>{adult}</td><td>{youth}</td></tr>)}</tbody></table></div><p className="alabama-threshold-note">The striped bass category here applies to inland Hudson and Delaware River waters. This table covers DEC’s freshwater Angler Awards; marine records and saltwater regulations are separate programs. Review DEC’s current official page before applying.</p><div className="actions"><a className="btn primary" href={official} target="_blank" rel="noreferrer">Official lengths and entry rules ↗</a></div></section>
    <section className="section" id="tracker"><div className="section-heading"><p className="eyebrow">YOUR PRIVATE CHECKLIST</p><h2>Keep your species goals organized.</h2><p>Track potential qualifying fish here, then submit each catch through DEC for official review.</p></div><NewYorkTracker /></section>
    <section className="section challenge-layout"><div><p className="eyebrow">FIRST FISH</p><h2>Mark the first catch, too.</h2><p>DEC offers printable My First Fish certificates for a beginner angler’s first fish. Choose an image-ready or stock-image format from its awards page.</p><a className="btn primary" href={official} target="_blank" rel="noreferrer">Find First Fish certificates ↗</a></div><aside className="challenge-side"><p className="eyebrow">PLAN THE WATER</p><h2>Check regulations first.</h2><p>Open seasons, size limits, and methods vary by water and species. A fish can meet an award length while still being subject to other fishing rules.</p><a className="btn secondary" href={rules} target="_blank" rel="noreferrer">New York freshwater rules ↗</a></aside></section>
    <section className="section final-cta challenge-final"><p className="eyebrow">READY TO START?</p><h2>Pick a species and keep a ruler handy.</h2><p>Document a legal catch clearly and submit the official entry within 30 days.</p><div className="actions"><a className="btn primary" href={official} target="_blank" rel="noreferrer">Open DEC awards program ↗</a><a className="btn secondary" href="/states">Back to all states</a></div></section><footer><strong>FISH THE FIFTY</strong><span>Built for anglers who want to fish farther.</span></footer>
  </main>;
}
