import type { Metadata } from "next";
import CaliforniaTracker from "./tracker";
import { heritageTrout, passportAwards } from "./trout-data";

export const metadata: Metadata = { title: "California Fishing Challenges | Fish the Fifty", description: "Track California's Heritage Trout Challenge and California Fishing Passport awards." };
const links = { heritage: "https://wildlife.ca.gov/Fishing/Inland/HTC", application: "https://wildlife.ca.gov/Fishing/Inland/HTC/Application", passport: "https://wildlife.ca.gov/Fishing/Passport/Awards", passportBook: "https://wildlife.ca.gov/Fishing/Passport", waters: "https://wildlife.ca.gov/Fishing/Inland/Trout-Waters", regulations: "https://wildlife.ca.gov/Regulations", license: "https://www.ca.wildlifelicense.com/InternetSales/" };

export default function CaliforniaChallengePage() { return <main>
  <header className="nav-shell"><div className="nav-wrap"><a className="brand" href="/">FISH THE FIFTY</a><nav><a href="/states">States</a><a href="/#challenges">Challenges</a><a href="/#progress">My Progress</a></nav></div></header><div className="breadcrumb"><a href="/states">States</a><span> / </span><a href="/states/california/challenge">California</a><span> / </span><span>Fishing Challenges</span></div>
  <section className="page-hero challenge-hero california-hero"><div className="page-hero-inner"><p className="eyebrow">CALIFORNIA · OFFICIAL CDFW PROGRAMS</p><h1>Six native trout.<br />Historic California waters.</h1><p className="lead">Complete the Heritage Trout Challenge by catching six different native trout forms in their historic drainages and documenting every fish with a clear photograph.</p><div className="state-facts"><span>11 eligible trout forms</span><span>Six needed</span><span>No time limit</span><span>Personalized certificate</span></div><div className="actions"><a className="btn primary" href={links.heritage}>Official Heritage Trout rules ↗</a><a className="btn secondary" href={links.passport}>Fishing Passport awards ↗</a></div></div></section>
  <section className="section california-tracker-section"><CaliforniaTracker /><div className="challenge-note"><strong>Planning tools only.</strong><p>Your progress remains in this browser. CDFW determines historic-range eligibility, species identification, documentation, and award approval.</p></div></section>
  <section className="section challenge-layout"><div><p className="eyebrow">HOW THE TROUT CHALLENGE WORKS</p><h2>Document six distinct forms.</h2><ol className="challenge-steps"><li><strong>Research historic drainage.</strong><span>A native trout stocked outside its historic watershed does not qualify.</span></li><li><strong>Fish legally.</strong><span>Check the open season, gear restrictions and water-specific regulations before every trip.</span></li><li><strong>Photograph the entire fish.</strong><span>CDFW must be able to identify the trout form clearly; the angler does not need to appear.</span></li><li><strong>Record every detail.</strong><span>Save the species, water, county, date and gear, then submit six documented catches.</span></li></ol><a className="btn primary" href={links.application}>Online Heritage Trout application ↗</a></div><aside className="challenge-side"><p className="eyebrow">WHAT YOU EARN</p><h2>A personalized native-trout certificate.</h2><p>The 16-by-20-inch certificate displays full-color artwork representing the six trout you caught, with their dates and locations. The program has no completion deadline, and qualifying older photographs may be used.</p><a className="btn secondary" href={links.waters}>Designated trout waters ↗</a></aside></section>
  <section className="section qualification-section"><div className="section-heading"><p className="eyebrow">ELEVEN NATIVE TARGETS</p><h2>Choose any six.</h2><p>Every fish must come from the form’s historic California drainage.</p></div><div className="california-trout-grid">{heritageTrout.map((trout) => <article className="challenge-card compact" key={trout.name}><span className="state-pill">{trout.group}</span><h3>{trout.name}</h3></article>)}</div></section>
  <section className="section california-passport-levels"><div className="section-heading"><p className="eyebrow">CALIFORNIA FISHING PASSPORT</p><h2>Four categories. Three achievement levels each.</h2><p>Document different qualifying California species in the official Passport and apply when you reach an award threshold.</p></div><div className="card-grid">{passportAwards.map((award) => <article className="challenge-card" key={award.category}><span className="state-pill">{award.category}</span><h3>{award.levels[0][0]} · {award.levels[1][0]} · {award.levels[2][0]}</h3><p>{award.levels.map(([count, name]) => `${count} species: ${name}`).join(" · ")}</p></article>)}</div><div className="texas-share-card california-supreme-card"><div><p className="eyebrow">THE TOP RECOGNITION</p><h2>California Supreme Master Angler</h2><p>Earn Master Angler status in at least two of the four Passport categories to receive an engraved plaque and a letter from the CDFW Director.</p></div><a className="btn secondary" href={links.passportBook}>Download the Fishing Passport ↗</a></div></section>
  <section className="section final-cta challenge-final"><p className="eyebrow">READY TO PLAN?</p><h2>Start with one historic drainage.</h2><p>Confirm access and current regulations, then photograph and record the fish before release.</p><div className="actions"><a className="btn primary" href={links.heritage}>Explore the Heritage Trout Challenge ↗</a><a className="btn secondary" href={links.license}>Buy a California license ↗</a></div></section><footer><strong>FISH THE FIFTY</strong><span>Built for anglers who want to fish farther.</span></footer>
  </main>; }
