"use client";

import { useEffect, useMemo, useState } from "react";
import { heritageTrout, passportAwards } from "./trout-data";

type TroutCatch = { species: string; date: string; water: string; county: string; gear: "Fly" | "Lure" | "Bait"; released: boolean; photo: boolean; historicRange: boolean };
const STORAGE_KEY = "fish-the-fifty-california-challenges-v1";
const emptyCatch = (): TroutCatch => ({ species: "", date: "", water: "", county: "", gear: "Fly", released: true, photo: false, historicRange: false });
const emptyCounts = () => ({ Warmwater: 0, Coldwater: 0, Ocean: 0, Shellfish: 0 });

export default function CaliforniaTracker() {
  const [catches, setCatches] = useState<TroutCatch[]>(Array.from({ length: 6 }, emptyCatch));
  const [counts, setCounts] = useState<Record<string, number>>(emptyCounts);
  const [saved, setSaved] = useState(false);
  useEffect(() => { try { const raw = localStorage.getItem(STORAGE_KEY); if (!raw) return; const value = JSON.parse(raw) as { catches?: TroutCatch[]; counts?: Record<string, number> }; if (Array.isArray(value.catches)) setCatches(Array.from({ length: 6 }, (_, i) => ({ ...emptyCatch(), ...(value.catches?.[i] ?? {}) }))); if (value.counts) setCounts({ ...emptyCounts(), ...value.counts }); } catch { /* Keep trackers usable. */ } }, []);
  const complete = useMemo(() => catches.filter((item, index) => item.species && item.date && item.water && item.county && item.photo && item.historicRange && catches.findIndex((other) => other.species === item.species) === index).length, [catches]);
  function update(index: number, field: keyof TroutCatch, value: string | boolean) { setSaved(false); setCatches((current) => current.map((item, i) => i === index ? { ...item, [field]: value } : item)); }
  function save() { try { localStorage.setItem(STORAGE_KEY, JSON.stringify({ catches, counts })); } catch { /* Continue without persistence. */ } setSaved(true); }
  function clear() { setCatches(Array.from({ length: 6 }, emptyCatch)); setCounts(emptyCounts()); setSaved(false); try { localStorage.removeItem(STORAGE_KEY); } catch { /* Nothing to clear. */ } }
  return <div className="california-trackers"><div className="tracker-card texas-tracker california-heritage-tracker"><div className="tracker-top"><div><p className="eyebrow">HERITAGE TROUT TRACKER</p><h3>Six native trout forms</h3></div><strong>{complete} / 6</strong></div><div className="tracker-track"><span style={{ width: `${complete * 16.667}%` }} /></div><p className="tracker-help">Each trout must be a different qualifying form, caught in its historic drainage, documented with a clear photo, and taken in compliance with current regulations.</p><div className="texas-slots">{catches.map((item, index) => { const duplicate = Boolean(item.species && catches.findIndex((other) => other.species === item.species) !== index); return <section className="texas-slot" key={index}><div className="texas-slot-heading"><strong>Trout {index + 1}</strong>{item.photo && item.historicRange && !duplicate && <span>Documented</span>}</div><label>Native trout form<select value={item.species} onChange={(e) => update(index, "species", e.target.value)}><option value="">Choose a trout…</option>{heritageTrout.map((trout) => <option key={trout.name}>{trout.name}</option>)}</select></label><div className="texas-slot-fields"><label>Catch date<input type="date" value={item.date} onChange={(e) => update(index, "date", e.target.value)} /></label><label>Gear<select value={item.gear} onChange={(e) => update(index, "gear", e.target.value)}><option>Fly</option><option>Lure</option><option>Bait</option></select></label></div>{duplicate && <p className="texas-below-minimum">The certificate requires six different trout forms; this one is already logged.</p>}<label>Stream or lake<input value={item.water} onChange={(e) => update(index, "water", e.target.value)} placeholder="Exact California water" /></label><label>County<input value={item.county} onChange={(e) => update(index, "county", e.target.value)} placeholder="California county" /></label><div className="california-checks"><label><input type="checkbox" checked={item.historicRange} onChange={(e) => update(index, "historicRange", e.target.checked)} /> Historic drainage confirmed</label><label><input type="checkbox" checked={item.photo} onChange={(e) => update(index, "photo", e.target.checked)} /> Clear fish photo ready</label><label><input type="checkbox" checked={item.released} onChange={(e) => update(index, "released", e.target.checked)} /> Released</label></div></section>; })}</div></div>
  <aside className="tracker-card california-passport"><div className="tracker-top"><div><p className="eyebrow">FISHING PASSPORT</p><h3>Award progress</h3></div></div><p className="tracker-help">Enter the number of different qualifying species fully documented in your official California Fishing Passport.</p><div className="california-award-counts">{passportAwards.map((award) => { const count = counts[award.category] || 0; const earned = [...award.levels].reverse().find(([minimum]) => count >= minimum); const next = award.levels.find(([minimum]) => count < minimum); return <section key={award.category}><div><strong>{award.category}</strong><span>{earned ? earned[1] : "Building toward first award"}</span></div><label>Documented species<input type="number" min="0" value={count} onChange={(e) => { setSaved(false); setCounts((current) => ({ ...current, [award.category]: Math.max(0, Number(e.target.value)) })); }} /></label><div className="tracker-track"><span style={{ width: `${Math.min(100, (count / award.levels[award.levels.length - 1][0]) * 100)}%` }} /></div><small>{next ? `${next[0] - count} more to ${next[1]}` : `${award.levels[award.levels.length - 1][1]} achieved`}</small></section>; })}</div><div className="california-supreme"><strong>Supreme Master Angler</strong><p>Earn Master status in at least two Passport categories.</p></div></aside>
  <div className="tracker-actions california-save"><button className="btn primary" type="button" onClick={save}>Save California progress</button><button className="tracker-clear" type="button" onClick={clear}>Clear California progress</button>{saved && <span className="tracker-saved">Saved in this browser.</span>}</div></div>;
}
