import type { Metadata } from "next";
export const metadata: Metadata = { title: "Virginia Angler Awards | Fish the Fifty", description: "Explore Virginia freshwater trophy citations, Master Angler I–VI, Expert Angler awards, and the separate saltwater citation program." };
const trophy = "https://dwr.virginia.gov/fishing/trophy-fish/";
const master = "https://dwr.virginia.gov/fishing/trophy-fish/master-angler-awards/";
const expert = "https://dwr.virginia.gov/fishing/trophy-fish/expert-angler-awards/";
const sizes = "https://dwr.virginia.gov/fishing/trophy-fish/size-chart/";
const salt = "https://mrc.virginia.gov/vswft/index.shtm";
const levels = [["I",5],["II",10],["III",15],["IV",20],["V",25],["VI",30]] as const;
const examples = [["Largemouth bass","8 lb","22 in"],["Smallmouth bass","5 lb","20 in"],["Brook trout","2 lb","16 in"],["Brown trout","5 lb","25 in"],["Rainbow trout","4 lb","22 in"],["Freshwater drum","6 lb","24 in"],["Common carp","20 lb","34 in"]] as const;
export default function VirginiaChallengePage() {
  return <main>
    <header className="nav-shell"><div className="nav-wrap"><a className="brand" href="/">FISH THE FIFTY</a><nav aria-label="Main navigation"><a href="/states">States</a><a href="/#challenges">Challenges</a><a href="/#progress">My Progress</a></nav></div></header>
    <div className="breadcrumb"><a href="/states">States</a><span aria-hidden="true"> / </span><span>Virginia</span></div>
    <section className="page-hero challenge-hero"><div className="page-hero-inner"><p className="eyebrow">VIRGINIA · FRESHWATER &amp; SALTWATER AWARDS</p><h1>Trophy catches.<br />Virginia recognition.</h1><p className="lead">Register a qualifying freshwater trophy with DWR, build your Master Angler species collection, or explore the separate Virginia Saltwater Fishing Tournament citation program.</p><div className="state-facts"><span>Freshwater length or weight</span><span>Master Angler I–VI</span><span>Separate marine citations</span></div><div className="actions"><a className="btn primary" href="#freshwater">Freshwater awards ↓</a><a className="btn secondary" href="#saltwater">Saltwater citations ↓</a></div></div></section>
    <section className="section challenge-layout" id="freshwater"><div><p className="eyebrow">DWR TROPHY FISH</p><h2>Document and register online.</h2><ol className="challenge-steps"><li><strong>Check the species standard.</strong><span>Use DWR's current trophy size chart and certification instructions for length or weight entries.</span></li><li><strong>Take a clear evidence photo.</strong><span>All applications require a fish photo. Length photos must show a readable ruler beside or beneath the fish; do not bend it over the fish. Weight photos must show the entire fish on the scale with a readable display.</span></li><li><strong>Use Go Outdoors Virginia.</strong><span>Sign in to your customer profile, choose Add Catch, enter the details and complete checkout. DWR no longer processes mailed applications.</span></li><li><strong>Print your citation.</strong><span>Accepted citations can be viewed and printed through your account; certificates are no longer mailed.</span></li></ol><a className="btn primary" href={trophy} target="_blank" rel="noreferrer">Official rules &amp; online submission ↗</a></div><aside className="challenge-side"><p className="eyebrow">EXPERT ANGLER</p><h2>Specialize in one species.</h2><p>Register ten trophy fish of the same species to earn lifetime Expert Angler recognition, a certificate and species patch. DWR tracks qualifying catches without a separate award application.</p><p>Crappie and sunfish have specific aggregation rules. Review these before planning an Expert collection.</p><a className="btn secondary" href={expert} target="_blank" rel="noreferrer">Expert Angler rules ↗</a></aside></section>
    <section className="section"><div className="section-heading"><p className="eyebrow">MASTER ANGLER LEVELS</p><h2>Build a collection of different species.</h2><p>DWR counts registered trophies automatically. Each level earns a certificate and patch. Level VI requires all 30 trophy species in the program; review the official treatment of crappie and sunfish categories.</p></div><div className="card-grid">{levels.map(([level,count]) => <article className="challenge-card" key={level}><span className="state-pill">MASTER ANGLER {level}</span><h3>{count} different species</h3><p>Register qualifying trophy catches across {count} different species.</p><a href={master} target="_blank" rel="noreferrer">Official level requirements ↗</a></article>)}</div></section>
    <section className="section qualification-section alabama-size-section"><div className="section-heading"><p className="eyebrow">SELECT FRESHWATER TROPHY SIZES</p><h2>Know the benchmark.</h2><p>These are selected DWR trophy minimums. Check the full chart and certification rules for the current standards and any water-specific eligibility notes.</p></div><div className="qualification-table-wrap alabama-table-wrap"><table><caption className="visually-hidden">Selected Virginia freshwater trophy weight and length standards</caption><thead><tr><th scope="col">Species</th><th scope="col">Weight</th><th scope="col">Length</th></tr></thead><tbody>{examples.map(([name,weight,length]) => <tr key={name}><th scope="row">{name}</th><td>{weight}</td><td>{length}</td></tr>)}</tbody></table></div><div className="actions"><a className="btn secondary" href={sizes} target="_blank" rel="noreferrer">All DWR trophy sizes ↗</a></div></section>
    <section className="section challenge-layout" id="saltwater"><div><p className="eyebrow">VMRC SALTWATER FISHING TOURNAMENT</p><h2>Explore marine citations.</h2><p>VMRC operates a separate saltwater recognition program. Its official tournament hub links citation sizes, rules, weigh stations, marine records and adult release-citation submission.</p><p>Use the current hub to verify the appropriate species, entry method and supporting evidence before your trip.</p><a className="btn primary" href={salt} target="_blank" rel="noreferrer">Saltwater citation program ↗</a></div><aside className="challenge-side"><p className="eyebrow">MORE OFFICIAL PATHS</p><h2>Records and junior anglers.</h2><p>DWR's freshwater trophy hub links the separate state record process. VMRC's tournament hub also provides marine state records and its Junior Angler program.</p><div className="actions"><a className="btn secondary" href={trophy} target="_blank" rel="noreferrer">Freshwater record resources ↗</a><a className="btn secondary" href={salt} target="_blank" rel="noreferrer">Marine records &amp; junior program ↗</a></div></aside></section>
    <section className="section final-cta challenge-final"><p className="eyebrow">READY TO START?</p><h2>Pick your Virginia trophy goal.</h2><p>Check the award standard and current fishing rules for your species and water, then prepare your measurement evidence.</p><div className="actions"><a className="btn primary" href={trophy} target="_blank" rel="noreferrer">Explore freshwater awards ↗</a><a className="btn secondary" href="/states">Back to all states</a></div></section>
    <footer><strong>FISH THE FIFTY</strong><span>Built for anglers who want to fish farther.</span></footer>
  </main>;
}
