import type { Metadata } from "next";
import { accessAreas, appleMapSearch, checkedDate, checkedLabel, googleMapSearch, sources } from "./guide-data";

export const metadata: Metadata = {
  title: "Great Salt Plains Lake Fishing Guide | Fish the Fifty",
  description: "Plan a Great Salt Plains Lake fishing trip near Jet, Oklahoma, with public access notes, seasonal refuge rules, maps, and official fishing resources.",
};

export default function GreatSaltPlainsPage() {
  return (
    <>
      <a className="skip-link" href="#guide-content">Skip to lake guide</a>
      <header className="nav-shell"><div className="nav-wrap"><a className="brand" href="/">FISH THE FIFTY</a><nav aria-label="Main navigation"><a href="/states">States</a><a href="/winter-trout">Winter Trout</a><a href="/#challenges">Challenges</a><a href="/#progress">My Progress</a></nav></div></header>
      <main id="guide-content" className="river-guide">
        <div className="breadcrumb"><a href="/states">States</a><span aria-hidden="true"> / </span><a href="/states/oklahoma">Oklahoma</a><span aria-hidden="true"> / </span><span>Great Salt Plains Lake</span></div>
        <section className="page-hero river-hero"><div className="page-hero-inner river-hero-grid"><div><p className="eyebrow">OKLAHOMA · WATER GUIDE 08</p><h1>Great Salt Plains Lake.</h1><p className="lead">A broad, shallow prairie reservoir near Jet with stocked channel catfish and saugeye, accessible bank-fishing spots, and extra seasonal rules where the lake meets Salt Plains National Wildlife Refuge.</p><div className="actions"><a className="btn primary" href="#access">Find access</a><a className="btn secondary" href="#rules">Check seasons & rules</a></div></div><aside className="river-brief" aria-label="Lake at a glance"><p className="eyebrow">AT A GLANCE</p><dl><div><dt>Where</dt><dd>About 8 miles northeast of Jet</dd></div><div><dt>Lake surface</dt><dd>About 8,690 acres</dd></div><div><dt>Maximum depth</dt><dd>About 16 feet</dd></div><div><dt>Focus species</dt><dd>Channel catfish & saugeye</dd></div></dl><a href={sources.odwcLake.url}>ODWC lake information <span aria-hidden="true">↗</span></a></aside></div></section>

        <div className="guide-shell">
          <aside className="stocking-notice" aria-labelledby="access-heading"><p className="eyebrow">ACCESS NOTE · <time dateTime={checkedDate}>{checkedLabel}</time></p><h2 id="access-heading">Check which agency manages your access point.</h2><p>Great Salt Plains Lake is operated by the U.S. Army Corps of Engineers, with Salt Plains State Park and the National Wildlife Refuge providing nearby recreation and fishing access. Refuge areas have extra rules and a seasonal fishing window. Use the map and agency links below to plan for the exact shoreline or ramp you intend to use.</p><a className="text-link" href={sources.usaceLake.url}>Review current USACE lake information <span aria-hidden="true">↗</span></a></aside>
          <nav className="guide-jump-links" aria-label="On this page"><a href="#access">Access & maps</a><a href="#fishing">Species & tactics</a><a href="#rules">Seasons & rules</a><a href="#conditions">Before you go</a><a href="#sources">Sources</a></nav>

          <section id="access" className="guide-section"><div className="guide-section-heading"><div><p className="eyebrow">01 / GET TO THE WATER</p><h2>Start with the shoreline and dam area.</h2></div><a className="text-link" href={sources.lakeMap.url}>Open the lake map (PDF) <span aria-hidden="true">↗</span></a></div><p className="guide-intro">ODWC highlights a few dependable public access options, including a fishing dock and ramp at Coon Hollow and a paved fishing area below the north-side spillway. The lake is shallow, so check recent conditions and launch information before choosing a boat-based plan.</p><div className="access-grid">{accessAreas.map((area, index) => <article className="access-card" key={area.id}><div className="access-card-top"><span className="state-pill">{area.type}</span><span className="access-number" aria-hidden="true">0{index + 1}</span></div><h3>{area.name}</h3><p>{area.description}</p><p className="access-note">{area.note}</p><div className="map-links"><a href={googleMapSearch(area.mapQuery)} aria-label={`Search Google Maps for ${area.name}`}>Google Maps <span aria-hidden="true">↗</span></a><a href={appleMapSearch(area.mapQuery)} aria-label={`Search Apple Maps for ${area.name}`}>Apple Maps <span aria-hidden="true">↗</span></a></div></article>)}</div><p className="source-note"><a href={sources.refugeBrochure.url}>Read the refuge fishing and boating brochure <span aria-hidden="true">↗</span></a></p></section>

          <section id="fishing" className="guide-section fishing-grid"><div><p className="eyebrow">02 / PLAN YOUR FISHING</p><h2>Make the shallow water work for you.</h2><p className="guide-intro">ODWC lists channel catfish and saugeye as stocked species at Great Salt Plains. The reservoir’s 16-foot maximum depth and the USACE note about its shallow character make access, wind, and recent water conditions important parts of the plan. Below the dam, USACE describes catfish and other species as a popular target.</p><div className="species-list">{["Channel catfish", "Saugeye"].map((fish) => <span key={fish}>{fish}</span>)}</div><p className="source-note"><a href={sources.odwcReports.url}>Check the latest ODWC fishing report <span aria-hidden="true">↗</span></a></p><div className="tackle-note"><h3>Fish the Fifty starting approach</h3><p>For saugeye, start with a compact jig or minnow-style presentation along channel edges and wind-affected points, then adjust depth based on the day’s conditions. For catfish, fish a stable bank or jetty near deeper current and carry bait suited to the rules for your chosen area. These are general starting ideas, not a current fishing report.</p><p className="source-note"><a href={sources.usaceLake.url}>See the USACE lake overview <span aria-hidden="true">↗</span></a></p></div><div className="tackle-note"><h3>Fly-fishing note</h3><p>The main lake is open and shallow, which can make wind and long casts a challenge. A 5-weight is a useful choice for smaller baitfish patterns in calm conditions; bring a heavier rod if wind or larger streamers are part of the plan. The spillway and accessible bank areas are easier places to test conditions before committing to a boat route.</p></div></div><div className="season-notes"><article><span className="eyebrow">SAUGEYE</span><h3>Keep the presentation compact</h3><p>Use the current ODWC report to choose depth and timing. Work methodically around channel edges, points, and other changes rather than covering featureless water at random.</p></article><article><span className="eyebrow">CHANNEL CATFISH</span><h3>Use easy public access</h3><p>The Coon Hollow dock and ramp and the paved north-side fishing area make practical bank options. Below the dam, follow posted boundaries and check current conditions.</p></article><article><span className="eyebrow">SHALLOW RESERVOIR</span><h3>Check water and wind</h3><p>USACE cautions that the lake’s shallowness can limit which boating and fishing activities suit the main body. Check the lake office before launching if conditions are uncertain.</p></article><div className="resource-links"><a href={sources.odwcLake.url}>ODWC lake page ↗</a><a href={sources.usaceLake.url}>USACE lake page ↗</a><a href={sources.odwcReports.url}>ODWC reports ↗</a></div></div></section>

          <section id="rules" className="guide-section"><p className="eyebrow">03 / SEASONS, LICENSES & RULES</p><h2>Refuge access has a seasonal fishing window.</h2><div className="rules-grid"><article className="rule-card special-rule"><span className="eyebrow">SALT PLAINS NATIONAL WILDLIFE REFUGE</span><h3>Fishing: April 1–October 15</h3><p>FWS lists Great Salt Plains Lake among refuge fishing areas open April 1 through October 15. Fishing trails are open only during the fishing season, and additional refuge regulations apply with Oklahoma rules. Check the refuge page before entering refuge-managed areas.</p><a className="text-link" href={sources.refugeFishing.url}>Read current refuge fishing rules ↗</a></article><article className="rule-card special-rule"><span className="eyebrow">SAUGEYE LIMIT</span><h3>Six combined per day</h3><p>ODWC’s Great Salt Plains page lists walleye, sauger, and saugeye at six combined per day with no size limit for the lake and tailwaters. Confirm the current rule before keeping fish.</p><a className="text-link" href={sources.odwcLake.url}>Verify the area-specific limit ↗</a></article><article className="rule-card"><h3>Carry a valid Oklahoma license</h3><p>Check whether you need an Oklahoma fishing license or qualify for an exemption before your trip.</p><a className="text-link" href={sources.stateLicense.url}>ODWC license portal ↗</a></article><article className="rule-card"><h3>Follow both sets of rules</h3><p>Oklahoma fishing regulations apply, with additional refuge regulations in Salt Plains National Wildlife Refuge. Follow posted access boundaries and seasonal closures.</p><div className="resource-links"><a href={sources.odwcRegs.url}>ODWC regulations ↗</a><a href={sources.refugeBrochure.url}>FWS fishing brochure ↗</a></div></article></div></section>

          <section id="conditions" className="guide-section conditions-section"><p className="eyebrow">04 / BEFORE YOU LEAVE</p><h2>Confirm access, wind, and the refuge season.</h2><p className="guide-intro">The lake is about eight miles northeast of Jet and twelve miles east of Cherokee. Conditions and open access can vary by agency and shoreline. Confirm current refuge access, lake conditions, weather, and regulations before leaving.</p><div className="condition-grid"><a className="condition-card" href={sources.odwcLake.url}><span>ACCESS & CONTACTS</span><h3>ODWC lake information <span aria-hidden="true">↗</span></h3><p>Review access notes, official contacts, stocked species, and area-specific regulations.</p></a><a className="condition-card" href={sources.refugeFishing.url}><span>SEASON & REFUGE RULES</span><h3>FWS fishing page <span aria-hidden="true">↗</span></h3><p>Confirm which refuge fishing areas and trails are open for your visit.</p></a><a className="condition-card" href={sources.odwcReports.url}><span>FISHING INFO</span><h3>ODWC reports <span aria-hidden="true">↗</span></h3><p>Use current reports to adjust species, depth, and timing.</p></a></div><p className="condition-footnote">ODWC lists the Great Salt Plains Lake office at (580) 626-4731.</p></section>

          <section id="sources" className="guide-section source-section"><div><p className="eyebrow">OFFICIAL SOURCES</p><h2>Plan with current information.</h2><p>Guide checked <time dateTime={checkedDate}>{checkedLabel}</time>. Fishing access, refuge seasons, lake conditions, and regulations can change. Tactics are general Fish the Fifty starting ideas, not a live fishing report.</p></div><ul>{[sources.odwcLake, sources.refugeFishing, sources.refugeBrochure, sources.usaceLake, sources.lakeMap, sources.stateLicense, sources.odwcRegs, sources.odwcReports].map((source) => <li key={source.url}><a href={source.url}>{source.label} <span aria-hidden="true">↗</span></a></li>)}</ul></section>
          <div className="guide-return"><a className="btn primary" href="/states/oklahoma">← Back to Oklahoma</a><a className="text-link" href="/states/oklahoma/challenge">Open the Oklahoma challenge tracker →</a></div>
        </div>
      </main>
      <footer><strong>FISH THE FIFTY</strong><span>Built for anglers who want to fish farther.</span></footer>
    </>
  );
}
