export const alabamaSpecies = [
  { slug: "alabama-bass", name: "Alabama Bass", masterWeight: "4 lb 0 oz", masterLength: "19.0 in", trophyWeight: "6 lb 0 oz", trophyLength: "21.5 in" },
  { slug: "black-crappie", name: "Black Crappie", masterWeight: "2 lb 8 oz", masterLength: "15.0 in", trophyWeight: "3 lb 8 oz", trophyLength: "16.5 in" },
  { slug: "blue-catfish", name: "Blue Catfish", masterWeight: "50 lb 0 oz", masterLength: "46.0 in", trophyWeight: "70 lb 0 oz", trophyLength: "51.0 in" },
  { slug: "bluegill-sunfish", name: "Bluegill Sunfish", masterWeight: "1 lb 0 oz", masterLength: "10.0 in", trophyWeight: "2 lb 0 oz", trophyLength: "12.5 in" },
  { slug: "channel-catfish", name: "Channel Catfish", masterWeight: "15 lb 0 oz", masterLength: "32.0 in", trophyWeight: "25 lb 0 oz", trophyLength: "37.5 in" },
  { slug: "flathead-catfish", name: "Flathead Catfish", masterWeight: "30 lb 0 oz", masterLength: "38.0 in", trophyWeight: "50 lb 0 oz", trophyLength: "44.5 in" },
  { slug: "hybrid-striped-bass", name: "Hybrid Striped Bass", masterWeight: "12 lb 0 oz", masterLength: "27.0 in", trophyWeight: "16 lb 0 oz", trophyLength: "29.5 in" },
  { slug: "largemouth-bass", name: "Largemouth Bass", masterWeight: "8 lb 0 oz", masterLength: "23.0 in", trophyWeight: "10 lb 0 oz", trophyLength: "25.0 in" },
  { slug: "redear-sunfish", name: "Redear Sunfish", masterWeight: "1 lb 0 oz", masterLength: "11.0 in", trophyWeight: "2 lb 0 oz", trophyLength: "13.5 in" },
  { slug: "redeye-bass", name: "Redeye Bass", masterWeight: "12 oz", masterLength: "11.5 in", trophyWeight: "1 lb 0 oz", trophyLength: "12.5 in" },
  { slug: "sauger", name: "Sauger", masterWeight: "2 lb 0 oz", masterLength: "17.0 in", trophyWeight: "3 lb 0 oz", trophyLength: "19.5 in" },
  { slug: "smallmouth-bass", name: "Smallmouth Bass", masterWeight: "5 lb 0 oz", masterLength: "20.0 in", trophyWeight: "7 lb 0 oz", trophyLength: "22.0 in" },
  { slug: "spotted-bass", name: "Spotted Bass", masterWeight: "4 lb 0 oz", masterLength: "19.0 in", trophyWeight: "5 lb 0 oz", trophyLength: "20.0 in" },
  { slug: "striped-bass", name: "Striped Bass", masterWeight: "25 lb 0 oz", masterLength: "37.0 in", trophyWeight: "35 lb 0 oz", trophyLength: "41.5 in" },
  { slug: "walleye", name: "Walleye", masterWeight: "5 lb 0 oz", masterLength: "22.5 in", trophyWeight: "8 lb 0 oz", trophyLength: "26.5 in" },
  { slug: "white-bass", name: "White Bass", masterWeight: "3 lb 0 oz", masterLength: "17.5 in", trophyWeight: "4 lb 0 oz", trophyLength: "19.0 in" },
  { slug: "white-crappie", name: "White Crappie", masterWeight: "2 lb 8 oz", masterLength: "15.5 in", trophyWeight: "3 lb 8 oz", trophyLength: "17.0 in" },
  { slug: "yellow-perch", name: "Yellow Perch", masterWeight: "1 lb 0 oz", masterLength: "12.0 in", trophyWeight: "1 lb 8 oz", trophyLength: "13.5 in" },
] as const;
