import type { Metadata } from "next";
import { accessAreas, appleMapSearch, checkedDate, checkedLabel, googleMapSearch, sources } from "./guide-data";

export const metadata: Metadata = {
  title: "Lake Carl Blackwell Fishing Guide | Fish the Fifty",
  description: "Plan a Lake Carl Blackwell fishing trip near Stillwater with OSU access, permits, maps, fishing rules, and a fly-fishing starting setup.",
};

export default function LakeCarlBlackwellPage() {
  return (
    <>
      <a className="skip-link" href="#guide-content">Skip to lake guide</a>
      <header className="nav-shell"><div className="nav-wrap"><a className="brand" href="/">FISH THE FIFTY</a><nav aria-label="Main navigation"><a href="/states">States</a><a href="/#challenges">Challenges</a><a href="/#progress">My Progress</a></nav></div></header>
      <main id="guide-content" className="river-guide">
        <div className="breadcrumb"><a href="/states">States</a><span aria-hidden="true"> / </span><a href="/states/oklahoma">Oklahoma</a><span aria-hidden="true"> / </span><span>Lake Carl Blackwell</span></div>
        <section className="page-hero river-hero"><div className="page-hero-inner river-hero-grid"><div><p className="eyebrow">OKLAHOMA · WATER GUIDE 07</p><h1>Lake Carl Blackwell.</h1><p className="lead">An OSU-operated Stillwater reservoir where north-end ramps, a Blackjack Cove launch, and open public recreational shoreline set up a flexible day of bass, sunfish, crappie, catfish, and saugeye hunting.</p><div className="actions"><a className="btn primary" href="#access">Find access</a><a className="btn secondary" href="#rules">Know the rules</a></div></div><aside className="river-brief" aria-label="Lake at a glance"><p className="eyebrow">AT A GLANCE</p><dl><div><dt>Where</dt><dd>West of Stillwater</dd></div><div><dt>Lake surface</dt><dd>About 3,350 acres</dd></div><div><dt>Operator</dt><dd>Oklahoma State University</dd></div><div><dt>Primary focus</dt><dd>Bass, panfish & saugeye</dd></div></dl><a href={sources.operator.url}>OSU Lake Carl Blackwell <span aria-hidden="true">↗</span></a></aside></div></section>

        <div className="guide-shell">
          <aside className="stocking-notice" aria-labelledby="permit-heading"><p className="eyebrow">OSU LAKE UPDATE · <time dateTime={checkedDate}>{checkedLabel}</time></p><h2>Buy the lake permit first.</h2><p>Lake Carl Blackwell requires a daily or annual use permit for recreation, including fishing. A current Oklahoma fishing license is also required unless you are exempt. Vehicle and watercraft permits are separate considerations, so check the current OSU permit page before you leave.</p><a className="text-link" href={sources.permits.url}>See current permit types and prices <span aria-hidden="true">↗</span></a></aside>
          <nav className="guide-jump-links" aria-label="On this page"><a href="#access">Access & maps</a><a href="#fishing">Species & tactics</a><a href="#rules">Licenses & rules</a><a href="#conditions">Before you go</a><a href="#sources">Sources</a></nav>

          <section id="access" className="guide-section"><div className="guide-section-heading"><div><p className="eyebrow">01 / GET TO THE WATER</p><h2>Start north, then move with the wind.</h2></div><a className="text-link" href={sources.generalMap.url}>Lake map (PDF) <span aria-hidden="true">↗</span></a></div><p className="guide-intro">The OSU FAQ calls out two popular Ski Point ramps at the north end and another ramp at Blackjack Cove. For a bank session, OSU regulations keep public recreational shoreline open; the map and posted signs decide where you can park and walk safely.</p><div className="access-grid">{accessAreas.map((area, index) => <article className="access-card" key={area.id}><div className="access-card-top"><span className="state-pill">{area.type}</span><span className="access-number" aria-hidden="true">0{index + 1}</span></div><h3>{area.name}</h3><p>{area.description}</p><p className="access-note">{area.note}</p><div className="map-links"><a href={googleMapSearch(area.mapQuery)} aria-label={`Search Google Maps for ${area.name}`}>Google Maps <span aria-hidden="true">↗</span></a><a href={appleMapSearch(area.mapQuery)} aria-label={`Search Apple Maps for ${area.name}`}>Apple Maps <span aria-hidden="true">↗</span></a></div></article>)}</div></section>

          <section id="fishing" className="guide-section fishing-grid"><div><p className="eyebrow">02 / PLAN YOUR FISHING</p><h2>Work the protected water first.</h2><p className="guide-intro">Carl Blackwell is a broad, recreational reservoir. For a fly angler, the highest-percentage first move is to get out of the open-water chop and probe protected coves, shoreline shade, points, and flooded cover. Largemouth and hybrid bass, bluegill and other sunfish, crappie, catfish, and saugeye are the practical Fish the Fifty target list; use the latest ODWC report to refine what is active.</p><div className="species-list">{["Largemouth bass", "Hybrid striped bass", "Saugeye", "Bluegill & sunfish", "Crappie", "Channel catfish", "Blue catfish", "Freshwater drum"].map((fish) => <span key={fish}>{fish}</span>)}</div><p className="source-note"><a href={sources.odwcReports.url}>Check the latest ODWC fishing report <span aria-hidden="true">↗</span></a></p><div className="tackle-note"><h3>Fish the Fifty starting setup</h3><p>Start with your Helios 4F 5-weight, a 7½–9-foot leader, small foam terrestrials or poppers for sunfish and bass, plus a Woolly Bugger or small baitfish streamer when the bank is quiet. Keep the Redington Big Game 8-weight ready for wind, larger bass, or deeper streamer work from a boat.</p><a className="text-link" href={sources.generalMap.url}>Use the OSU map to find coves and points <span aria-hidden="true">↗</span></a></div></div><div className="season-notes"><article><span className="eyebrow">SUNFISH & BASS</span><h3>Make the first cast small</h3><p>Start tight to shade, grass, laydowns, and protected pocket water with a popper or lightly weighted nymph. Let the fish tell you whether to stay shallow or switch to a streamer.</p></article><article><span className="eyebrow">OPEN WATER</span><h3>Let wind create the edge</h3><p>Wind can push bait and comfortable water against one bank. Follow that wind-protected or wind-affected edge rather than committing to the middle of the reservoir.</p></article><article><span className="eyebrow">SHARED LAKE</span><h3>Fish around recreation</h3><p>Boating, skiing, camping, hiking, and fishing all share the lake. Keep casts clear of courtesy docks, fuel facilities, ramps, and other users.</p></article><div className="resource-links"><a href={sources.generalMap.url}>OSU general map ↗</a><a href={sources.noWakeMap.url}>No-wake map ↗</a><a href={sources.odwcReports.url}>ODWC reports ↗</a></div></div></section>

          <section id="rules" className="guide-section"><p className="eyebrow">03 / LICENSES & RULES</p><h2>Carry the state license and OSU permit.</h2><div className="rules-grid"><article className="rule-card special-rule"><span className="eyebrow">PERMITS</span><h3>Daily or annual use permit</h3><p>OSU requires a permit for daily recreational use, including fishing. The current permit page lists vehicle, boat, PWC, and other permit types and prices.</p><div className="resource-links"><a href={sources.permits.url}>OSU permits ↗</a><a href={sources.operator.url}>Lake office ↗</a></div></article><article className="rule-card special-rule"><span className="eyebrow">STATE LICENSE</span><h3>Oklahoma fishing license</h3><p>OSU regulations require a current State of Oklahoma Fishing License before fishing unless the angler is exempt under ODWC rules.</p><a className="text-link" href={sources.stateLicense.url}>Buy or review a state license ↗</a></article><article className="rule-card"><h3>No noodling or nets</h3><p>OSU prohibits hand fishing or noodling, and also prohibits nets, traps, bow and arrow, or guns for taking fish from the lake.</p><a className="text-link" href={sources.regulations.url}>Read OSU fishing rules ↗</a></article><article className="rule-card"><h3>Respect the lake zones</h3><p>Water skiing and personal watercraft are limited to designated areas, and posted no-wake rules apply. Courtesy docks and the fuel dock are not fishing platforms.</p><div className="resource-links"><a href={sources.noWakeMap.url}>No-wake map ↗</a><a href={sources.regulations.url}>Full regulations ↗</a></div></article></div></section>

          <section id="conditions" className="guide-section conditions-section"><p className="eyebrow">04 / BEFORE YOU LEAVE</p><h2>Check permits, weather, and the latest report.</h2><p className="guide-intro">Lake Carl Blackwell is an OSU-operated recreation area, so access and permit details can change independently of statewide fishing regulations. Confirm the current lake map, permit page, posted signs, wind, and ODWC report before launching or walking a shoreline.</p><div className="condition-grid"><a className="condition-card" href={sources.permits.url}><span>ACCESS STATUS</span><h3>OSU permits <span aria-hidden="true">↗</span></h3><p>Confirm current daily and annual permit types, prices, and where to purchase them.</p></a><a className="condition-card" href={sources.faq.url}><span>LAKE DETAILS</span><h3>OSU FAQ <span aria-hidden="true">↗</span></h3><p>Review ramps, kayak information, passes, quiet hours, and visitor questions.</p></a><a className="condition-card" href={sources.odwcReports.url}><span>FISHING INFO</span><h3>ODWC reports <span aria-hidden="true">↗</span></h3><p>Use the latest statewide fishing report to adjust species, depth, and timing.</p></a></div><p className="condition-footnote">Lake office: (405) 372-5157 · 11000 W Hwy 51, Stillwater, OK 74074</p></section>

          <section id="sources" className="guide-section source-section"><div><p className="eyebrow">OFFICIAL SOURCES</p><h2>Plan with current information.</h2><p>Guide checked <time dateTime={checkedDate}>{checkedLabel}</time>. OSU permits, lake policies, state regulations, and fishing reports can change. The fly setup above is a Fish the Fifty starting point, not an official regulation.</p></div><ul>{[sources.operator, sources.permits, sources.regulations, sources.maps, sources.generalMap, sources.noWakeMap, sources.faq, sources.stateLicense, sources.odwcRegs, sources.odwcReports].map((source) => <li key={source.url}><a href={source.url}>{source.label} <span aria-hidden="true">↗</span></a></li>)}</ul></section>
          <div className="guide-return"><a className="btn primary" href="/states/oklahoma">← Back to Oklahoma</a><a className="text-link" href="/states">Explore all 50 states →</a></div>
        </div>
      </main>
      <footer><strong>FISH THE FIFTY</strong><span>Built for anglers who want to fish farther.</span></footer>
    </>
  );
}
