import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "New Hampshire Trophy & Record Fish | Fish the Fifty",
  description: "Compare New Hampshire Trophy Fish kept-weight and release-length standards, application rules, and state fish records.",
};

const program = "https://www.wildlife.nh.gov/fishing-new-hampshire/trophy-and-record-fish-program";
const form = "https://www.wildlife.nh.gov/sites/g/files/ehbemt746/files/documents/trophy-record-fish-app.pdf";
const records = "https://www.wildlife.nh.gov/fishing-new-hampshire/state-nh-record-fish";
const selected = [
  ["Black crappie", "2 lb", "14 in"],
  ["Brook trout", "2 lb", "16 in"],
  ["Brown trout", "5 lb", "25 in"],
  ["Lake trout", "10 lb", "30 in"],
  ["Largemouth bass", "5 lb", "20 in"],
  ["Smallmouth bass", "4 lb", "19 in"],
  ["Striped bass", "40 lb", "45 in"],
] as const;

export default function NewHampshireChallengePage() {
  return <main>
    <header className="nav-shell"><div className="nav-wrap"><a className="brand" href="/">FISH THE FIFTY</a><nav aria-label="Main navigation"><a href="/states">States</a><a href="/#challenges">Challenges</a><a href="/#progress">My Progress</a></nav></div></header>
    <div className="breadcrumb"><a href="/states">States</a><span aria-hidden="true"> / </span><span>New Hampshire</span></div>
    <section className="page-hero challenge-hero"><div className="page-hero-inner"><p className="eyebrow">NEW HAMPSHIRE · FISH AND GAME</p><h1>New Hampshire<br />Trophy Fish.</h1><p className="lead">A remarkable catch can earn a Trophy Fish patch. Compare the minimum weight for a kept fish or length for a released fish, then follow New Hampshire Fish and Game’s official entry rules.</p><div className="state-facts"><span>Kept · weight</span><span>Released · length</span><span>Apply within 30 days</span></div><div className="actions"><a className="btn primary" href="#standards">Compare standards ↓</a><a className="btn secondary" href={program} target="_blank" rel="noreferrer">Official Trophy Fish program ↗</a></div></div></section>
    <section className="section challenge-layout"><div><p className="eyebrow">TROPHY FISH PROGRAM</p><h2>Two ways to qualify.</h2><ol className="challenge-steps"><li><strong>Choose kept or released.</strong><span>Kept fish must meet the species minimum weight; released fish must meet the minimum length. Both freshwater and saltwater species appear on the official form.</span></li><li><strong>Record the evidence.</strong><span>Submit a clear side-view photo. Photograph a catch-and-release fish at the catch site, handle it properly, and return it safely.</span></li><li><strong>Complete the official form.</strong><span>Entries require original signatures and an attestation by a qualified officer. Mail the form within 30 days of landing the fish; email photos as instructed by Fish and Game.</span></li></ol><a className="btn primary" href={form} target="_blank" rel="noreferrer">Rules, standards, and entry form ↗</a></div><aside className="challenge-side"><p className="eyebrow">ANNUAL RECOGNITION</p><h2>A patch for qualifying catches.</h2><p>Qualifying entrants receive a Trophy Fish arm patch. At year’s end, the heaviest kept fish or longest released fish in each species category earns a special certificate.</p><p>The program runs January 1 through December 31. The official form limits an angler to three entries for a species in a program year: one kept and two catch-and-release.</p><a className="btn secondary" href={program} target="_blank" rel="noreferrer">View program and winners ↗</a></aside></section>
    <section className="section qualification-section alabama-size-section" id="standards"><div className="section-heading"><p className="eyebrow">SELECTED TROPHY MINIMUMS</p><h2>Compare your catch.</h2><p>These examples come from the New Hampshire Fish and Game entry form. Use the official form for the complete freshwater and saltwater species list and to confirm current standards before fishing.</p></div><div className="qualification-table-wrap alabama-table-wrap"><table><caption className="visually-hidden">Selected New Hampshire Trophy Fish minimum weights for kept fish and lengths for released fish</caption><thead><tr><th scope="col">Species</th><th scope="col">Kept minimum</th><th scope="col">Released minimum</th></tr></thead><tbody>{selected.map(([name, weight, length]) => <tr key={name}><th scope="row">{name}</th><td>{weight}</td><td>{length}</td></tr>)}</tbody></table></div><p className="alabama-threshold-note">Striped bass is a saltwater category. Legal size limits and seasons still apply; an award minimum does not authorize keeping an otherwise protected fish.</p><div className="actions"><a className="btn primary" href={form} target="_blank" rel="noreferrer">See all official minimums ↗</a></div></section>
    <section className="section"><div className="section-heading"><p className="eyebrow">POSSIBLE STATE RECORD</p><h2>Arrange a certified weight.</h2><p>New Hampshire’s State Record Fish program can consider any species. For a possible record, weigh the fish promptly on a scale certified by the New Hampshire Division of Weights and Measures. Two witnesses must sign the entry, and a printed weight slip must accompany it. Check the current record list before making a claim.</p></div><div className="card-grid"><article className="challenge-card"><span className="state-pill">1 · COMPARE</span><h3>Standing records</h3><p>Review verified New Hampshire records for the species, waterbody, and weight to understand the target.</p><a href={records} target="_blank" rel="noreferrer">Current state records ↗</a></article><article className="challenge-card"><span className="state-pill">2 · VERIFY</span><h3>Certified scale</h3><p>Plan for two witnesses, the certified scale, a printed weight slip, and a clear identification photo.</p><a href={form} target="_blank" rel="noreferrer">Official record rules ↗</a></article><article className="challenge-card"><span className="state-pill">3 · SUBMIT</span><h3>Signed original</h3><p>Have the statement attested by a qualified officer and mail the original signed form to Fish and Game Region 2.</p><a href={form} target="_blank" rel="noreferrer">Download entry form ↗</a></article></div></section>
    <section className="section final-cta challenge-final"><p className="eyebrow">READY TO PLAN?</p><h2>Check the official form first.</h2><p>Confirm the current threshold and fishing regulations. Complete applications must be received within 30 days of landing; prior-year entries are not accepted after January 30.</p><div className="actions"><a className="btn primary" href={form} target="_blank" rel="noreferrer">Get the Fish and Game form ↗</a><a className="btn secondary" href={records} target="_blank" rel="noreferrer">Explore state records ↗</a></div></section>
    <footer><strong>FISH THE FIFTY</strong><span>Built for anglers who want to fish farther.</span></footer>
  </main>;
}
