import type { Metadata } from "next";
import NevadaTracker from "./tracker";
import { nativeFish } from "./species";

export const metadata: Metadata = {
  title: "Nevada Native Fish-Slam & Angler Awards | Fish the Fifty",
  description: "Pursue Nevada's six native sport fish and explore NDOW's Trophy Fish and First Fish recognition programs.",
};

const official = "https://www.ndow.org/get-outside/angler-recognition-program/";

export default function NevadaChallengePage() {
  return <main>
    <header className="nav-shell"><div className="nav-wrap"><a className="brand" href="/">FISH THE FIFTY</a><nav aria-label="Main navigation"><a href="/states">States</a><a href="/#challenges">Challenges</a><a href="/#progress">My Progress</a></nav></div></header>
    <div className="breadcrumb"><a href="/states">States</a><span aria-hidden="true"> / </span><span>Nevada</span></div>
    <section className="page-hero challenge-hero"><div className="page-hero-inner"><p className="eyebrow">NEVADA · DEPARTMENT OF WILDLIFE</p><h1>Nevada Native<br />Fish-Slam.</h1><p className="lead">Catch six native sport fish across Nevada waters for an official certificate and custom medallion. Take your time, photograph each fish, and send each entry to NDOW within 60 days of the catch.</p><div className="state-facts"><span>6 native species</span><span>No completion deadline</span><span>60 days per entry</span></div><div className="actions"><a className="btn primary" href="#native-slam">Explore the six ↓</a><a className="btn secondary" href={official} target="_blank" rel="noreferrer">Official Nevada programs ↗</a></div></div></section>
    <section className="section" id="native-slam"><div className="section-heading"><p className="eyebrow">OFFICIAL NATIVE FISH-SLAM</p><h2>Six fish. One Nevada adventure.</h2><p>Legally catch and photograph each of these native sport fish in Nevada. NDOW does not require weight or length measurements for the Slam. Check current fishing rules, including harvest restrictions, and use NDOW’s FishNV tool to find waters.</p></div><div className="card-grid">{nativeFish.map((name, index) => <article className="challenge-card" key={name}><span className="state-pill">NATIVE FISH · {String(index + 1).padStart(2, "0")}</span><h3>{name}</h3><p>Confirm a suitable Nevada water and its current regulations before your trip. Save a photograph and catch details for the official entry.</p><a href={official} target="_blank" rel="noreferrer">NDOW Slam details ↗</a></article>)}</div><div className="actions"><a className="btn primary" href={official} target="_blank" rel="noreferrer">Find FishNV and entry form ↗</a></div></section>
    <section className="section challenge-layout"><div><p className="eyebrow">HOW TO ENTER</p><h2>Document each fish as you go.</h2><ol className="challenge-steps"><li><strong>Fish legally in Nevada.</strong><span>Identify the species and check the current rules for that water and fish before catching or handling it.</span></li><li><strong>Take a photograph.</strong><span>NDOW requires a photo of each of the six species. Weight and length are not required for the Native Fish-Slam.</span></li><li><strong>Send each entry within 60 days.</strong><span>There is no overall Slam deadline, but each fish’s entry form and photo must be submitted within 60 days of its catch. NDOW tracks your progress.</span></li></ol><a className="btn primary" href={official} target="_blank" rel="noreferrer">Official rules and form ↗</a></div><aside className="challenge-side"><p className="eyebrow">SIX APPROVED ENTRIES</p><h2>Earn the medallion.</h2><p>NDOW awards a certificate and custom medallion for an approved six-species Slam. A later Slam may also be completed, with its fish caught at least one month after the previous Slam was completed and awarded.</p><p>NDOW makes the final decision on entries. Keep the original photographs and catch information until your submissions are accepted.</p></aside></section>
    <section className="section" id="tracker"><div className="section-heading"><p className="eyebrow">PLAN YOUR SLAM</p><h2>Keep track of your six species.</h2><p>This private checklist is for planning. Send photographs and official entry forms directly to Nevada Department of Wildlife.</p></div><NevadaTracker /></section>
    <section className="section qualification-section"><div className="section-heading"><p className="eyebrow">MORE NEVADA RECOGNITION</p><h2>Big fish and first fish count, too.</h2><p>NDOW also offers weight-based Trophy Fish certificates, water record certificates, and a First Fish award. Each uses its own form; check the official program page for current minimum weights and rules.</p></div><div className="card-grid"><article className="challenge-card"><span className="state-pill">TROPHY FISH</span><h3>Meet the species minimum</h3><p>Weigh the whole fish before freezing, measure nose to tail, get two measurement witnesses (one unrelated), and provide an adequate identification photo. Submit within 60 days.</p><a href={official} target="_blank" rel="noreferrer">Trophy sizes and form ↗</a></article><article className="challenge-card"><span className="state-pill">WATER &amp; STATE RECORDS</span><h3>Challenge a standing catch</h3><p>A water record is the heaviest fish of its species from that water. A possible state record needs a certified scale and an NDOW employee witness.</p><a href={official} target="_blank" rel="noreferrer">Record rules ↗</a></article><article className="challenge-card"><span className="state-pill">FIRST FISH</span><h3>Celebrate a first catch</h3><p>For an angler’s first legally caught Nevada fish, NDOW offers a personalized certificate and enamel pin. Submit its form within 60 days; no size measurement is needed.</p><a href={official} target="_blank" rel="noreferrer">First Fish form ↗</a></article></div></section>
    <section className="section final-cta challenge-final"><p className="eyebrow">READY TO PLAN?</p><h2>Find your first native fish.</h2><p>Use NDOW’s current program page for the rules, forms, and FishNV waters. Your Slam has no overall deadline, but each catch has a 60-day entry window.</p><div className="actions"><a className="btn primary" href={official} target="_blank" rel="noreferrer">Nevada angler programs ↗</a><a className="btn secondary" href="/states">Back to all states</a></div></section>
    <footer><strong>FISH THE FIFTY</strong><span>Built for anglers who want to fish farther.</span></footer>
  </main>;
}
