import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Vermont Master Angler | Fish the Fifty",
  description: "Plan Vermont Trophy Angler and five-species Master Angler awards with adult and youth lengths, photo rules, and the January 15 deadline.",
};
const program = "https://vtfishandwildlife.com/fish/fishing-events-and-programs/master-angler-program";
const lengths = "https://www.vtfishandwildlife.com/fish/fishing-events-and-programs/master-angler-program/master-angler-qualifying-fish-list";
const entry = "https://anrweb.vt.gov/FWD/FW/MasterAnglerEntry.aspx";
const fishing = "https://vtfishandwildlife.com/fish";
const redhorse = "https://www.vtfishandwildlife.com/learn-more/vermont-critters/fish/redhorse-sucker";

export default function VermontChallengePage() {
  return <main>
    <header className="nav-shell"><div className="nav-wrap"><a className="brand" href="/">FISH THE FIFTY</a><nav aria-label="Main navigation"><a href="/states">States</a><a href="/#challenges">Challenges</a><a href="/members">My Progress</a></nav></div></header>
    <div className="breadcrumb"><a href="/states">States</a><span aria-hidden="true"> / </span><span>Vermont</span></div>
    <section className="page-hero challenge-hero"><div className="page-hero-inner"><p className="eyebrow">VERMONT · FISH &amp; WILDLIFE</p><h1>Five species.<br />One Master Angler year.</h1><p className="lead">Vermont recognizes exceptional fish by length. Start with a Trophy Angler catch, then pursue five different qualifying species in a calendar year to earn the Master Angler pin.</p><div className="state-facts"><span>Length-based recognition</span><span>Adult &amp; youth standards</span><span>Harvest or release</span></div><div className="actions"><a className="btn primary" href="#awards">Explore the awards ↓</a><a className="btn secondary" href={lengths} target="_blank" rel="noreferrer">Official qualifying lengths ↗</a></div></div></section>
    <section className="section challenge-layout" id="awards"><div><p className="eyebrow">TROPHY ANGLER</p><h2>Recognize one exceptional fish.</h2><p>A qualifying catch can earn a certificate and inclusion in Vermont's annual Trophy Fish Report. Compare your fish with the current adult or youth length standard and submit a clear photo.</p><a className="btn primary" href={lengths} target="_blank" rel="noreferrer">Species &amp; length standards ↗</a></div><aside className="challenge-side"><p className="eyebrow">MASTER ANGLER</p><h2>Five different species in one year.</h2><p>Catch at least five different species that qualify under the program's length rules within the same calendar year. Verified Master Anglers receive a commemorative lapel pin, issued after the year ends.</p><a className="btn secondary" href={program} target="_blank" rel="noreferrer">Official award rules ↗</a></aside></section>
    <section className="section challenge-layout"><div><p className="eyebrow">CATCH, MEASURE, SUBMIT</p><h2>Make the evidence count.</h2><ol className="challenge-steps"><li><strong>Choose eligible water.</strong><span>Fish legally during open season in water covered by a Vermont fishing license. Private and commercial waterbodies do not qualify.</span></li><li><strong>Use the correct length standard.</strong><span>Measure from snout to tail tip. Anglers under 15 at the time of the catch may use the lower youth requirements.</span></li><li><strong>Photograph the entire fish clearly.</strong><span>Show a side view including the tail, with a ruler or another object of known size. If holding the fish, keep at least one finger visible on it. Avoid photos that exaggerate size.</span></li><li><strong>Submit by January 15.</strong><span>Entries are due January 15 for the previous calendar year. The current form accepts 2026 catches through January 15, 2027.</span></li></ol><a className="btn primary" href={entry} target="_blank" rel="noreferrer">Submit an official entry ↗</a></div><aside className="challenge-side"><p className="eyebrow">AFTER THE PHOTO</p><h2>Release or legally harvest.</h2><p>Vermont accepts both released and harvested fish. After measurement and photography, release the fish where caught or retain it only if current harvest rules permit.</p><p>The department reviews entries and may request more information. Check the current official rules and qualifying list before your trip.</p><a className="btn secondary" href={fishing} target="_blank" rel="noreferrer">Fishing rules &amp; opportunities ↗</a></aside></section>
    <section className="section"><div className="section-heading"><p className="eyebrow">PLAN YOUR SPECIES COLLECTION</p><h2>Use the current qualifying list.</h2><p>Vermont publishes separate adult and youth length columns. Use the live table for your targets, then keep catch dates and species together so you can follow your progress toward five different species.</p></div><div className="card-grid"><article className="challenge-card"><span className="state-pill">ADULT &amp; YOUTH</span><h3>Length requirements</h3><p>Compare each target with its official benchmark. The age at the time of the catch determines whether youth standards apply.</p><a href={lengths} target="_blank" rel="noreferrer">Open qualifying fish list ↗</a></article><article className="challenge-card"><span className="state-pill">NEW IN 2026</span><h3>Three redhorse categories</h3><p>Identify shorthead, greater and silver redhorse separately for entries. Vermont provides an identification guide for these native fish.</p><a href={redhorse} target="_blank" rel="noreferrer">Redhorse identification ↗</a></article><article className="challenge-card"><span className="state-pill">OFFICIAL SUBMISSION</span><h3>Entry form</h3><p>Complete the catch details and include the required fish image. Submit each qualifying catch directly to Vermont Fish &amp; Wildlife.</p><a href={entry} target="_blank" rel="noreferrer">Enter your catch ↗</a></article></div></section>
    <section className="section final-cta challenge-final"><p className="eyebrow">READY TO START?</p><h2>Choose your first five targets.</h2><p>Review the current lengths, pack a measuring rule, and photograph each qualifying catch clearly.</p><div className="actions"><a className="btn primary" href={program} target="_blank" rel="noreferrer">Explore Vermont Master Angler ↗</a><a className="btn secondary" href="/states">Back to all states</a></div></section>
    <footer><strong>FISH THE FIFTY</strong><span>Built for anglers who want to fish farther.</span></footer>
  </main>;
}
