import type { Metadata } from "next";
export const metadata: Metadata = { title: "West Virginia Master Angler Slams | Fish the Fifty", description: "Plan all six West Virginia Master Angler slams with qualifying species, lengths, photo requirements and official applications." };
const rules = "https://wvdnr.gov/fishing/fishing-regulations/";
const application = "https://wvdnr.gov/wp-content/uploads/2025/05/2021.12.08-DNR-Master-Angler-Rules-Application-v2.pdf";
const records = "https://wvdnr.gov/fishing/state-records/";
const slams = [
  ["Black Bass", "Largemouth, smallmouth and spotted bass: 12 inches each."],
  ["Catfish", "Blue and flathead catfish: 20 inches each. Channel catfish: 16 inches."],
  ["Panfish", "Sunfish: 6 inches. Rock bass: 7 inches. Black or white crappie: 8 inches. Yellow perch: 8 inches."],
  ["Nongame", "Fallfish, bullhead and freshwater drum: 12 inches each. Common carp: 20 inches."],
  ["Predator", "Musky: 30 inches. Walleye: 15 inches. Hybrid striped bass or striped bass: 15 inches."],
  ["Trout", "Brook, brown, golden rainbow, rainbow and tiger trout: 12 inches each."],
] as const;
export default function WestVirginiaChallengePage() {
  return <main>
    <header className="nav-shell"><div className="nav-wrap"><a className="brand" href="/">FISH THE FIFTY</a><nav aria-label="Main navigation"><a href="/states">States</a><a href="/#challenges">Challenges</a><a href="/members">My Progress</a></nav></div></header>
    <div className="breadcrumb"><a href="/states">States</a><span aria-hidden="true"> / </span><span>West Virginia</span></div>
    <section className="page-hero challenge-hero"><div className="page-hero-inner"><p className="eyebrow">WEST VIRGINIA · WVDNR MASTER ANGLER</p><h1>Six slams.<br />One lifetime achievement.</h1><p className="lead">Explore West Virginia's bass, catfish, panfish, nongame, predator and trout slams. Complete all six to earn the lifetime West Virginia Master Angler Award.</p><div className="state-facts"><span>6 official slams</span><span>Each slam: one calendar year</span><span>Time-stamped catch photos</span></div><div className="actions"><a className="btn primary" href="#slams">Explore the slams ↓</a><a className="btn secondary" href={application} target="_blank" rel="noreferrer">Official rules &amp; application ↗</a></div></div></section>
    <section className="section" id="slams"><div className="section-heading"><p className="eyebrow">SPECIES AND MINIMUM LENGTHS</p><h2>Choose your first slam.</h2><p>Catch every required species for your chosen slam and meet or exceed its minimum length. Where the list says “or,” either listed option satisfies that requirement. Confirm current rules before fishing.</p></div><div className="card-grid">{slams.map(([name,detail]) => <article className="challenge-card" key={name}><span className="state-pill">MASTER ANGLER SLAM</span><h3>{name} Slam</h3><p>{detail}</p><a href={application} target="_blank" rel="noreferrer">Official checklist ↗</a></article>)}</div></section>
    <section className="section challenge-layout"><div><p className="eyebrow">COMPLETE AND APPLY</p><h2>Document every qualifying species.</h2><ol className="challenge-steps"><li><strong>Catch legally in West Virginia.</strong><span>Follow the current species and water regulations. Commercial pay lakes and ponds do not qualify.</span></li><li><strong>Measure each fish.</strong><span>Meet the minimum length for each required species in the slam.</span></li><li><strong>Take time-stamped photographs.</strong><span>The application requires photos of the angler holding each species. Keep catch evidence together for your slam.</span></li><li><strong>Complete the slam within a calendar year.</strong><span>Fill out the official application and mail it with the required photos to the address on the form. Fisheries biologists may determine final species verification.</span></li></ol><a className="btn primary" href={application} target="_blank" rel="noreferrer">Download Master Angler application ↗</a></div><aside className="challenge-side"><p className="eyebrow">LIFETIME MASTER ANGLER</p><h2>Complete all six across your fishing years.</h2><p>Each individual slam must fit within one calendar year. The overall Master Angler award does not need to be completed in a single year, so you can work through the six slams over time.</p><a className="btn secondary" href={rules} target="_blank" rel="noreferrer">Current fishing regulations ↗</a></aside></section>
    <section className="section"><div className="section-heading"><p className="eyebrow">OTHER RECOGNITION PATHS</p><h2>Trophy citations and state records.</h2></div><div className="card-grid"><article className="challenge-card"><span className="state-pill">TROPHY FISH</span><h3>Length-based citations</h3><p>The separate Trophy Fish Citation Program uses its own minimum lengths and measurement evidence. Open the current protocol and application from WVDNR's fishing forms before submitting.</p><a href={rules} target="_blank" rel="noreferrer">Trophy protocol &amp; form ↗</a></article><article className="challenge-card"><span className="state-pill">STATE RECORD</span><h3>Length and weight records</h3><p>WVDNR maintains records for the largest hook-and-line catches by length and weight. Compare current records and review verification instructions before retaining a possible record.</p><a href={records} target="_blank" rel="noreferrer">Current records &amp; applications ↗</a></article></div></section>
    <section className="section final-cta challenge-final"><p className="eyebrow">READY TO START?</p><h2>Pick a slam and plan the species.</h2><p>Check your water's rules, pack a measuring rule, and keep time-stamped photos of every qualifying catch.</p><div className="actions"><a className="btn primary" href={application} target="_blank" rel="noreferrer">Open the six-slam checklist ↗</a><a className="btn secondary" href="/states">Back to all states</a></div></section>
    <footer><strong>FISH THE FIFTY</strong><span>Built for anglers who want to fish farther.</span></footer>
  </main>;
}
