import type { Metadata } from "next";
import PennsylvaniaTracker from "./tracker";
import { awardSpecies, formatWeight } from "./qualifying-species";
export const metadata: Metadata = { title: "Pennsylvania Angler Award Challenge | Fish the Fifty", description: "Plan and track trophy catches for the Pennsylvania Fish and Boat Commission Angler Award Program." };
const links = { application: "https://www.pa.gov/content/dam/copapwp-pagov/en/fishandboat/documents/fishing/all-about-fish/awardapp.pdf", recordApply: "https://www.pa.gov/services/fishandboat/apply-for-pennsylvania-state-record-fish", license: "https://www.pa.gov/agencies/fishandboat/fishing/buy-fishing-license-permit", regulations: "https://www.pa.gov/agencies/fishandboat/fishing/regulations", fish: "https://www.pa.gov/agencies/fishandboat/fishing/all-about-fish/catch-pa-fish" };
export default function PennsylvaniaChallengePage() { return <main>
  <header className="nav-shell"><div className="nav-wrap"><a className="brand" href="/">FISH THE FIFTY</a><nav><a href="/states">States</a><a href="/#challenges">Challenges</a><a href="/#progress">My Progress</a></nav></div></header><div className="breadcrumb"><a href="/states">States</a><span> / </span><a href="/states/pennsylvania/challenge">Pennsylvania</a><span> / </span><span>Angler Awards</span></div>
  <section className="page-hero challenge-hero pa-hero"><div className="page-hero-inner"><p className="eyebrow">PENNSYLVANIA · OFFICIAL PFBC PROGRAM</p><h1>Catch big.<br />Earn recognition.</h1><p className="lead">Pursue Pennsylvania’s Senior, Junior or Catch-and-Release Angler Awards—or join the Husky Musky Club with a fish measuring at least 50 inches.</p><div className="state-facts"><span>32 eligible categories</span><span>Length or weight awards</span><span>Residents and visitors eligible</span><span>Certificate and patch</span></div><div className="actions"><a className="btn primary" href={links.application}>Official application and rules ↗</a><a className="btn secondary" href={links.regulations}>Pennsylvania regulations ↗</a></div></div></section>
  <section className="section challenge-layout"><div><PennsylvaniaTracker /><div className="challenge-note"><strong>Planning tool only.</strong><p>Your catches stay in this browser. Fish the Fifty does not verify fish or send applications. PFBC controls eligibility and awards.</p></div></div><aside className="challenge-side"><p className="eyebrow">HOW THE AWARD WORKS</p><h2>Choose the right category.</h2><ol className="challenge-steps"><li><strong>Select an award division.</strong><span>Senior and Junior awards use qualifying weight; Catch-and-Release awards use total length.</span></li><li><strong>Fish qualifying public water.</strong><span>The program is open to residents and non-residents, but most private, fee-fishing and club waters are excluded.</span></li><li><strong>Document correctly.</strong><span>Released fish require a witness and a clear side-view photograph taken at the catch site.</span></li><li><strong>Mail the application.</strong><span>Use the official PFBC form. Only one award patch is issued to each applicant annually.</span></li></ol><a className="btn primary" href={links.application}>Download official PFBC form ↗</a></aside></section>
  <section className="section pa-award-paths"><div className="section-heading"><p className="eyebrow">FIVE RECOGNITION PATHS</p><h2>There is an award for every stage.</h2></div><div className="card-grid">{[["AGE 16+","Senior Angler","Meet the adult qualifying weight."],["UNDER 16","Junior Angler","Meet the youth qualifying weight."],["LENGTH","Catch & Release","Meet the length standard, photograph at the water and obtain a witness."],["50 INCHES","Husky Musky Club","Land a musky or tiger musky measuring at least 50 inches."],["ANY SIZE","First Fish","Recognize a new angler’s first fish with a certificate."]].map(([pill,title,text]) => <article className="challenge-card compact" key={title}><span className="state-pill">{pill}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>
  <section className="section qualification-section"><div className="section-heading"><p className="eyebrow">PFBC QUALIFYING STANDARDS</p><h2>Length for release. Weight for kept fish.</h2><p>Confirm the current official form before submitting because PFBC may change program standards.</p></div><div className="qualification-table-wrap pa-table"><table><thead><tr><th>Species</th><th>Release</th><th>Senior</th><th>Junior</th></tr></thead><tbody>{awardSpecies.map(([name,length,senior,junior]) => <tr key={name}><th>{name}</th><td>{length}&quot;</td><td>{formatWeight(senior)}</td><td>{formatWeight(junior)}</td></tr>)}</tbody></table></div></section>
  <section className="section texas-side-program"><div className="texas-share-card"><div><p className="eyebrow">A SEPARATE PROGRAM</p><h2>Think you caught a state record?</h2><p>The State Record Fish Program has additional weighing, certification and application requirements. Review them immediately before altering a potential record fish.</p></div><a className="btn secondary" href={links.recordApply}>State-record instructions ↗</a></div></section>
  <section className="section final-cta challenge-final"><p className="eyebrow">READY TO START?</p><h2>Pick a species and find its water.</h2><p>Research habitat and tactics, then verify the season and water-specific regulations before traveling.</p><div className="actions"><a className="btn primary" href={links.fish}>Explore Pennsylvania fish ↗</a><a className="btn secondary" href={links.license}>Buy a fishing license ↗</a></div></section><footer><strong>FISH THE FIFTY</strong><span>Built for anglers who want to fish farther.</span></footer>
  </main>; }
