"use client";
import { useEffect, useMemo, useState } from "react";
import { awardSpecies, formatWeight } from "./qualifying-species";
type Division = "release" | "senior" | "junior";
type Catch = { division: Division; species: string; measurement: string; date: string; water: string; witness: string; submitted: boolean };
const STORAGE_KEY = "fish-the-fifty-pennsylvania-angler-awards-v1";
const emptyCatch = (): Catch => ({ division: "release", species: "", measurement: "", date: "", water: "", witness: "", submitted: false });
const initial = Array.from({ length: 5 }, emptyCatch);
export default function PennsylvaniaTracker() {
  const [catches, setCatches] = useState<Catch[]>(initial); const [saved, setSaved] = useState(false);
  const recorded = useMemo(() => catches.filter((item) => item.species && item.measurement).length, [catches]);
  useEffect(() => { try { const raw = localStorage.getItem(STORAGE_KEY); if (!raw) return; const value = JSON.parse(raw) as Catch[]; if (Array.isArray(value)) setCatches(Array.from({ length: 5 }, (_, i) => ({ ...emptyCatch(), ...(value[i] ?? {}) }))); } catch { /* Tracker remains usable. */ } }, []);
  function update(index: number, field: keyof Catch, value: string | boolean) { setSaved(false); setCatches((current) => current.map((item, i) => i === index ? { ...item, [field]: value } : item)); }
  function save() { try { localStorage.setItem(STORAGE_KEY, JSON.stringify(catches)); } catch { /* Continue without persistence. */ } setSaved(true); }
  function clear() { setCatches(Array.from({ length: 5 }, emptyCatch)); setSaved(false); try { localStorage.removeItem(STORAGE_KEY); } catch { /* Nothing to clear. */ } }
  return <div className="tracker-card texas-tracker pa-tracker"><div className="tracker-top"><div><p className="eyebrow">YOUR PRIVATE CATCH LOG</p><h3>Pennsylvania award catches</h3></div><strong>{recorded}</strong></div><div className="tracker-track"><span style={{ width: `${recorded * 20}%` }} /></div><p className="tracker-help">Choose an award division for each fish. Catch-and-release uses length; Senior and Junior awards use weight. This planning tool does not replace PFBC verification.</p><div className="texas-slots">{catches.map((item, index) => {
    const id = `pa-catch-${index + 1}`; const species = awardSpecies.find(([name]) => name === item.species); const target = species ? item.division === "release" ? species[1] : item.division === "senior" ? species[2] : species[3] : undefined; const measured = Number(item.measurement); const entered = item.division === "release" ? measured : measured * 16; const below = target !== undefined && measured > 0 && entered < target; const targetLabel = target === undefined ? "" : item.division === "release" ? `${target} inches` : formatWeight(target);
    return <section className="texas-slot" key={index}><div className="texas-slot-heading"><strong>Catch {index + 1}</strong>{item.submitted && <span>Application mailed</span>}</div><div className="pa-division"><label><input type="radio" name={`${id}-division`} checked={item.division === "release"} onChange={() => update(index,"division","release")} /> Catch & Release</label><label><input type="radio" name={`${id}-division`} checked={item.division === "senior"} onChange={() => update(index,"division","senior")} /> Senior 16+</label><label><input type="radio" name={`${id}-division`} checked={item.division === "junior"} onChange={() => update(index,"division","junior")} /> Junior under 16</label></div><label>Species<select value={item.species} onChange={(e) => update(index,"species",e.target.value)}><option value="">Choose a species…</option>{awardSpecies.map(([name]) => <option key={name}>{name}</option>)}</select></label><div className="texas-slot-fields"><label>{item.division === "release" ? "Length (inches)" : "Weight (pounds)"}<input type="number" min="0" step="0.01" value={item.measurement} onChange={(e) => update(index,"measurement",e.target.value)} placeholder={targetLabel ? `Minimum ${targetLabel}` : "Enter measurement"} /></label><label>Catch date<input type="date" value={item.date} onChange={(e) => update(index,"date",e.target.value)} /></label></div>{below && <p className="texas-below-minimum">Below the published {targetLabel} minimum for this division.</p>}<label>Pennsylvania water<input value={item.water} onChange={(e) => update(index,"water",e.target.value)} placeholder="Public lake, river, stream or creek" /></label><label>Witness<input value={item.witness} onChange={(e) => update(index,"witness",e.target.value)} placeholder="Required for released catches" /></label><label className="kansas-applied"><input type="checkbox" checked={item.submitted} onChange={(e) => update(index,"submitted",e.target.checked)} /> I mailed the official PFBC application</label></section>;
  })}</div><div className="tracker-actions"><button className="btn primary" type="button" onClick={save}>Save my catches</button><button className="tracker-clear" type="button" onClick={clear}>Clear catch log</button>{saved && <span className="tracker-saved">Saved in this browser.</span>}</div></div>;
}
