import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Michigan Master Angler Program | Fish the Fifty",
  description: "Explore Michigan DNR's Master Angler patch, species-specific minimum lengths, photo and online application requirements, and state record rules.",
};

const links = {
  program: "https://www.michigan.gov/dnr/things-to-do/fishing/master-angler",
  sizes: "https://www.michigan.gov/dnr/things-to-do/fishing/master-angler/minimum-entry-lengths-weights-and-current-state-records",
  regulations: "https://www.michigan.gov/dnr/things-to-do/fishing/fishing-regulations",
  where: "https://www.michigan.gov/dnr/things-to-do/fishing/where",
  records: "https://www.michigan.gov/dnr/things-to-do/fishing/master-angler/state-record",
};

const examples = [
  ["Largemouth bass", "21 in."], ["Smallmouth bass", "21 in."],
  ["White bass", "16 in."], ["Bluegill", "10 in."],
  ["Freshwater drum", "27 in."], ["Channel catfish", "30 in."],
  ["Brook trout", "14 in."], ["Brown trout", "24 in."],
  ["Rainbow trout (steelhead)", "32 in."], ["Walleye", "29 in."],
] as const;

export default function MichiganChallengePage() {
  return <main>
    <header className="nav-shell"><div className="nav-wrap"><a className="brand" href="/">FISH THE FIFTY</a><nav aria-label="Main navigation"><a href="/states">States</a><a href="/#challenges">Challenges</a><a href="/members">My Progress</a></nav></div></header>
    <div className="breadcrumb"><a href="/states">States</a><span aria-hidden="true"> / </span><span>Michigan</span></div>
    <section className="page-hero challenge-hero"><div className="page-hero-inner"><p className="eyebrow">MICHIGAN · DEPARTMENT OF NATURAL RESOURCES</p><h1>Michigan<br />Master Angler.</h1><p className="lead">Measure a Michigan fish against its species-specific trophy length and submit a clear photo through the DNR’s online application. Qualifying entries earn the annual Master Angler patch.</p><div className="state-facts"><span>45+ eligible species</span><span>Minimum length by species</span><span>2026 entries due Jan. 10, 2027</span></div><div className="actions"><a className="btn primary" href="#sizes">See trophy lengths ↓</a><a className="btn secondary" href={links.program} target="_blank" rel="noreferrer">Official Michigan program ↗</a></div></div></section>
    <section className="section challenge-layout"><div><p className="eyebrow">THE OFFICIAL PATH</p><h2>Catch. Measure. Apply online.</h2><ol className="challenge-steps"><li><strong>Choose a listed species.</strong><span>Compare its Master Angler minimum length and check Michigan’s current season and water-specific rules.</span></li><li><strong>Catch it legally in public-access Michigan water.</strong><span>DNR requires legal sportfishing methods during the open season. Check whether the fish may be kept or must be released at your chosen water.</span></li><li><strong>Measure in a straight line.</strong><span>Measure from the nose or lower jaw to the tail tip, not along the body curve, to the nearest one-eighth inch. Photograph the entire fish against a legible standard measuring device.</span></li><li><strong>Submit the online form.</strong><span>Use the DNR program page for the official application. Fish caught in 2026 can be entered through January 10, 2027.</span></li></ol><a className="btn primary" href={links.program} target="_blank" rel="noreferrer">Apply through Michigan DNR ↗</a></div><aside className="challenge-side"><p className="eyebrow">THE PATCH</p><h2>One patch per species.</h2><p>The DNR awards a Master Angler patch to qualifying entries. An angler can receive no more than one patch for a given species in a year, and duplicate entries for the same species at the same size are not accepted.</p><p>Master Angler is length-based. A potential state record follows a different process based on weight and DNR species verification.</p><a className="btn secondary" href={links.program} target="_blank" rel="noreferrer">Read all program rules ↗</a></aside></section>
    <section className="section qualification-section alabama-size-section" id="sizes"><div className="section-heading"><p className="eyebrow">SELECT MASTER ANGLER LENGTHS</p><h2>Pick your target fish.</h2><p>Examples from Michigan’s current DNR table. These are Master Angler entry lengths, not harvest minimums. Review the full list and the fishing regulations before your trip.</p></div><div className="qualification-table-wrap alabama-table-wrap"><table><caption className="visually-hidden">Selected Michigan Master Angler minimum lengths</caption><thead><tr><th scope="col">Species</th><th scope="col">Minimum length</th></tr></thead><tbody>{examples.map(([species, length]) => <tr key={species}><th scope="row">{species}</th><td>{length}</td></tr>)}</tbody></table></div><div className="actions"><a className="btn primary" href={links.sizes} target="_blank" rel="noreferrer">All Michigan trophy lengths ↗</a></div></section>
    <section className="section"><div className="section-heading"><p className="eyebrow">PLAN AND DOCUMENT</p><h2>Make the entry count.</h2><p>Michigan’s Master Angler map and annual reports show previous catches. Locations can be generalized, so confirm access and regulations at the actual water you choose.</p></div><div className="card-grid"><article className="challenge-card"><span className="state-pill">1 · PLAN</span><h3>Find your water</h3><p>Use Michigan DNR fishing resources and its Master Angler map to research species and public access.</p><a href={links.where} target="_blank" rel="noreferrer">Where to fish ↗</a></article><article className="challenge-card"><span className="state-pill">2 · CHECK</span><h3>Read current rules</h3><p>Review seasons, species provisions, and local water rules, including any recent updates to trout, salmon, or sturgeon regulations.</p><a href={links.regulations} target="_blank" rel="noreferrer">Michigan fishing regulations ↗</a></article><article className="challenge-card"><span className="state-pill">3 · ENTER</span><h3>Save the photo</h3><p>Keep a readable measurement photo showing the entire fish, then submit it through the official online form.</p><a href={links.program} target="_blank" rel="noreferrer">Master Angler entry ↗</a></article></div></section>
    <section className="section challenge-layout"><div><p className="eyebrow">A SEPARATE RECORD PATH</p><h2>Think it is a state record?</h2><p>Michigan recognizes state fish records by weight. A potential record must exceed the standing weight and be identified by a DNR fisheries biologist. Contact a biologist promptly, arrange weighing on a commercial scale, and follow the separate state record application process.</p><a className="btn primary" href={links.records} target="_blank" rel="noreferrer">Check Michigan state records ↗</a></div><aside className="challenge-side"><p className="eyebrow">2026 DEADLINE</p><h2>Mark January 10, 2027.</h2><p>The DNR is accepting Master Angler entries for fish caught January 1 through December 31, 2026, until January 10, 2027. Verify the live deadline if you are entering a catch from a different year.</p><a className="btn secondary" href={links.program} target="_blank" rel="noreferrer">Current DNR entry information ↗</a></aside></section>
    <section className="section final-cta challenge-final"><p className="eyebrow">READY TO START?</p><h2>Bring a ruler. Check the rules.</h2><p>Choose a species, compare its current entry length, photograph the full measurement, and use Michigan DNR’s online application.</p><div className="actions"><a className="btn primary" href={links.program} target="_blank" rel="noreferrer">Open Master Angler program ↗</a><a className="btn secondary" href="/states">Back to all states</a></div></section>
    <footer><strong>FISH THE FIFTY</strong><span>Built for anglers who want to fish farther.</span></footer>
  </main>;
}
