import type { Metadata } from "next";
import { accessAreas, appleMapSearch, checkedDate, checkedLabel, googleMapSearch, sources } from "./guide-data";

export const metadata: Metadata = {
  title: "Lake Texoma Fishing Guide | Fish the Fifty",
  description: "Plan a Lake Texoma striped bass trip with official Oklahoma access, current limits, state-boundary guidance, and USACE lake conditions.",
};

export default function LakeTexomaPage() {
  return (
    <>
      <a className="skip-link" href="#guide-content">Skip to lake guide</a>
      <header className="nav-shell"><div className="nav-wrap"><a className="brand" href="/">FISH THE FIFTY</a><nav aria-label="Main navigation"><a href="/states">States</a><a href="/#challenges">Challenges</a><a href="/#progress">My Progress</a></nav></div></header>
      <main id="guide-content" className="river-guide">
        <div className="breadcrumb"><a href="/states">States</a><span aria-hidden="true"> / </span><a href="/states/oklahoma">Oklahoma</a><span aria-hidden="true"> / </span><span>Lake Texoma</span></div>
        <section className="page-hero river-hero"><div className="page-hero-inner river-hero-grid"><div><p className="eyebrow">OKLAHOMA · WATER GUIDE 04</p><h1>Lake Texoma.</h1><p className="lead">An 88,000-acre border reservoir and one of the Southwest’s premier striped bass destinations, with public ramps, state-park access, and big-water conditions to plan around.</p><div className="actions"><a className="btn primary" href="#access">Find access</a><a className="btn secondary" href="#rules">Know the limits</a></div></div><aside className="river-brief" aria-label="Lake at a glance"><p className="eyebrow">AT A GLANCE</p><dl><div><dt>Where</dt><dd>Oklahoma–Texas border</dd></div><div><dt>Surface area</dt><dd>88,000 acres</dd></div><div><dt>Shoreline</dt><dd>592.7 miles</dd></div><div><dt>Primary focus</dt><dd>Striped bass & hybrids</dd></div></dl><a href={sources.area.url}>ODWC Texoma listing <span aria-hidden="true">↗</span></a></aside></div></section>

        <div className="guide-shell">
          <aside className="stocking-notice" aria-labelledby="boundary-heading"><p className="eyebrow">BORDER-WATER UPDATE · <time dateTime={checkedDate}>{checkedLabel}</time></p><h2 id="boundary-heading">Two states, one lake.</h2><p>Lake Texoma regulations can differ between the Oklahoma and Texas portions. Know which side you are fishing, carry the required license, and check both agencies before keeping fish or crossing the lake.</p><a className="text-link" href={sources.area.url}>Read the current ODWC Texoma rules <span aria-hidden="true">↗</span></a></aside>
          <nav className="guide-jump-links" aria-label="On this page"><a href="#access">Access & maps</a><a href="#species">Species & tactics</a><a href="#rules">Limits & licenses</a><a href="#conditions">Before you go</a><a href="#sources">Sources</a></nav>

          <section id="access" className="guide-section"><div className="guide-section-heading"><div><p className="eyebrow">01 / GET ON THE WATER</p><h2>Choose your access.</h2></div><a className="text-link" href={sources.lakeMap.url}>Lake map (PDF) <span aria-hidden="true">↗</span></a></div><p className="guide-intro">ODWC lists U.S. Army Corps of Engineers and Oklahoma State Parks facilities with campgrounds, boat ramps, and fishing docks. Map buttons search the named area; use the official map, park page, and posted signs to confirm the public entrance.</p><div className="access-grid">{accessAreas.map((area, index) => <article className="access-card" key={area.id}><div className="access-card-top"><span className="state-pill">{area.type}</span><span className="access-number" aria-hidden="true">0{index + 1}</span></div><h3>{area.name}</h3><p>{area.description}</p><p className="access-note">{area.note}</p><div className="map-links"><a href={googleMapSearch(area.mapQuery)} aria-label={`Search Google Maps for ${area.name}`}>Google Maps <span aria-hidden="true">↗</span></a><a href={appleMapSearch(area.mapQuery)} aria-label={`Search Apple Maps for ${area.name}`}>Apple Maps <span aria-hidden="true">↗</span></a></div></article>)}</div></section>

          <section id="species" className="guide-section fishing-grid"><div><p className="eyebrow">02 / PLAN YOUR FISHING</p><h2>Chase the striper school.</h2><p className="guide-intro">ODWC lists striped bass, white bass, blue and flathead catfish, largemouth, smallmouth and spotted bass, crappie, and alligator gar as species of interest. TravelOK highlights stripers, largemouth bass, catfish, and crappie for the lake’s south-central fishing loop.</p><div className="species-list">{["Striped bass", "White bass", "Largemouth bass", "Smallmouth bass", "Spotted bass", "Blue catfish", "Flathead catfish", "Black crappie", "White crappie", "Alligator gar"].map((fish) => <span key={fish}>{fish}</span>)}</div><p className="source-note"><a href={sources.area.url}>ODWC species & management notes <span aria-hidden="true">↗</span></a></p><div className="tackle-note"><h3>Fish the Fifty starting setup</h3><p>For a fly-focused search, bring the 8-weight you already trust, a sink or sink-tip line, and weighted baitfish patterns such as Clousers or half-and-halves. Wind, depth, and boat traffic matter on this reservoir; use the sounder, watch the surface, and keep a second setup ready for bass or crappie water.</p><a className="text-link" href={sources.fishingTrail.url}>TravelOK Texoma fishing notes <span aria-hidden="true">↗</span></a></div></div><div className="season-notes"><article><span className="eyebrow">STRIPED BASS</span><h3>Find bait and depth</h3><p>Start with the lake’s open-water baitfish and structure transitions, then adjust quickly as wind, current, and boat traffic move the school.</p></article><article><span className="eyebrow">BASS & CRAPPIE</span><h3>Use the map</h3><p>ODWC and TravelOK point to a broad mix of bass, crappie, and catfish. The official depth map is a better first step than guessing at a shoreline.</p></article><article><span className="eyebrow">BIG RESERVOIR</span><h3>Plan a weather window</h3><p>Texoma can fish like two different lakes in one day. Check wind, storms, lake level, and release information before committing to a long run.</p></article><div className="resource-links"><a href={sources.lakeMap.url}>OWRB Texoma map ↗</a><a href={sources.fishingTrail.url}>Oklahoma Fishing Trail ↗</a><a href={sources.park.url}>Lake Texoma State Park ↗</a></div></div></section>

          <section id="rules" className="guide-section"><p className="eyebrow">03 / LIMITS & LICENSES</p><h2>Keep the boundary rules close.</h2><div className="rules-grid"><article className="rule-card special-rule"><span className="eyebrow">STRIPED BASS & HYBRIDS</span><h3>10 combined per day</h3><p>On the Oklahoma listing, only two fish in the combined limit may be 20 inches or longer.</p><a className="text-link" href={sources.area.url}>Verify the current ODWC limit ↗</a></article><article className="rule-card special-rule"><span className="eyebrow">BASS</span><h3>5 combined per day</h3><p>Largemouth, smallmouth, and spotted bass are combined; the Oklahoma listing gives a 14-inch minimum for largemouth and smallmouth bass.</p><a className="text-link" href={sources.area.url}>Verify the current ODWC limit ↗</a></article><article className="rule-card"><h3>Other Oklahoma limits</h3><p>ODWC lists 25 white bass per day, 37 combined crappie per day with a 10-inch minimum, and five flathead catfish per day with a 20-inch minimum.</p><div className="resource-links"><a href={sources.area.url}>Texoma area rules ↗</a><a href={sources.regulations.url}>State regulations ↗</a></div></article><article className="rule-card"><h3>Choose the right license</h3><p>Fishing regulations may differ between the Oklahoma and Texas portions. Check the governing state before you fish, and review the Texas Outdoor Annual when launching or crossing on the Texas side.</p><div className="resource-links"><a href={sources.license.url}>Oklahoma license ↗</a><a href={sources.texasRules.url}>Texas Outdoor Annual ↗</a></div></article></div></section>

          <section id="conditions" className="guide-section conditions-section"><p className="eyebrow">04 / BEFORE YOU LEAVE</p><h2>Check the lake in real time.</h2><p className="guide-intro">USACE posts current Lake Texoma elevation, release, storage, and project links. The page warns that electronic readings can change and are not guaranteed, so use it as a pre-launch check—not a substitute for local judgment or life-jacket decisions.</p><div className="condition-grid"><a className="condition-card" href={sources.operator.url}><span>LIVE LAKE DATA</span><h3>USACE Texoma conditions <span aria-hidden="true">↗</span></h3><p>Review elevation, releases, storage, hourly data, and lake-level links.</p></a><a className="condition-card" href={sources.recreation.url}><span>RAMP STATUS</span><h3>USACE recreation <span aria-hidden="true">↗</span></h3><p>Check project recreation guidance, park closures, ramp status, and safety notices.</p></a><a className="condition-card" href={sources.park.url}><span>OKLAHOMA SHORE</span><h3>State park status <span aria-hidden="true">↗</span></h3><p>Confirm park office hours, access, fees, reservations, and current facilities.</p></a></div><p className="condition-footnote">ODWC Texoma contacts: lake office (903) 465-4990 · fisheries management (580) 924-4087 · regional wardens listed on the official area page.</p></section>

          <section id="sources" className="guide-section source-section"><div><p className="eyebrow">OFFICIAL SOURCES</p><h2>Plan with current information.</h2><p>Guide checked <time dateTime={checkedDate}>{checkedLabel}</time>. Regulations, ramp status, weather, and lake conditions can change. The fly setup above is a Fish the Fifty starting point, not an official regulation.</p></div><ul>{[sources.area, sources.regulations, sources.checkIn, sources.license, sources.texasRules, sources.lakeMap, sources.operator, sources.recreation, sources.park, sources.fishingTrail, sources.mesonet, sources.nws].map((source) => <li key={source.url}><a href={source.url}>{source.label} <span aria-hidden="true">↗</span></a></li>)}</ul></section>
          <div className="guide-return"><a className="btn primary" href="/states/oklahoma">← Back to Oklahoma</a><a className="text-link" href="/states">Explore all 50 states →</a></div>
        </div>
      </main>
      <footer><strong>FISH THE FIFTY</strong><span>Built for anglers who want to fish farther.</span></footer>
    </>
  );
}
