import type { Metadata } from "next";
import IllinoisTracker from "./tracker";

export const metadata: Metadata = { title: "Illinois Master Angler Challenge | Fish the Fifty", description: "Plan and track five different Illinois fish species for the IDNR Master Angler certificate." };
const links = { awards: "https://old.ifishillinois.org/awards/open_award.html", regulations: "https://www.ifishillinois.org/site-documents/FishingDigest.pdf", records: "https://old.ifishillinois.org/awards/hookline_staterecord.html", license: "https://dnr.illinois.gov/lpr/fishinglicensesfees.html", waters: "https://ifishillinois.org/" };

export default function IllinoisChallengePage() { return <main>
  <header className="nav-shell"><div className="nav-wrap"><a className="brand" href="/">FISH THE FIFTY</a><nav><a href="/states">States</a><a href="/#challenges">Challenges</a><a href="/#progress">My Progress</a></nav></div></header><div className="breadcrumb"><a href="/states">States</a><span> / </span><a href="/states/illinois/challenge">Illinois</a><span> / </span><span>Master Angler</span></div>
  <section className="page-hero challenge-hero illinois-hero"><div className="page-hero-inner"><p className="eyebrow">ILLINOIS · OFFICIAL IDNR RECOGNITION</p><h1>Five species.<br />One Illinois season.</h1><p className="lead">Catch five different fish species legally in Illinois waters and create the state’s personalized Master Angler certificate. Separate recognition is available for hook-and-line and bow-fishing accomplishments.</p><div className="state-facts"><span>Five different species</span><span>Hook-and-line path</span><span>Bow-fishing path</span><span>Personalized certificate</span></div><div className="actions"><a className="btn primary" href={links.awards}>Official awards and certificates ↗</a><a className="btn secondary" href={links.regulations}>2026 Illinois regulations ↗</a></div></div></section>
  <section className="section challenge-layout"><div><IllinoisTracker /><div className="challenge-note"><strong>Planning tool only.</strong><p>Your catch log stays in this browser. Fish the Fifty does not certify catches; Illinois IDNR controls its awards and records.</p></div></div><aside className="challenge-side"><p className="eyebrow">HOW TO COMPLETE IT</p><h2>Build a five-species season.</h2><ol className="challenge-steps"><li><strong>Choose your method.</strong><span>Track a hook-and-line or bow-fishing Master Angler path separately.</span></li><li><strong>Catch legally.</strong><span>Fish must come from Illinois waters using a legal method and comply with statewide and site-specific rules.</span></li><li><strong>Record five species.</strong><span>Each species counts once. Save the water, date and measurement while the details are fresh.</span></li><li><strong>Create the certificate.</strong><span>Use the official I Fish Illinois awards page to personalize and print your recognition.</span></li></ol><a className="btn primary" href={links.awards}>Open IDNR awards page ↗</a></aside></section>
  <section className="section illinois-awards"><div className="section-heading"><p className="eyebrow">ILLINOIS RECOGNITION PATHS</p><h2>More than one way to mark the catch.</h2></div><div className="card-grid">{[["FIRST CATCH","First Fish","Create a personalized certificate for an angler’s first Illinois fish."],["FIVE SPECIES","Master Angler","Recognize five different species caught using the same award method."],["MEMORABLE FISH","Big Fish","Create a personalized certificate commemorating a notable Illinois catch."],["RELEASED","Catch & Release","Recognize a legally caught fish returned to Illinois water."],["TOP WEIGHT","State Record","Potential records require certified weighing, witnesses, IDNR identification and an application."]].map(([pill,title,text]) => <article className="challenge-card compact" key={title}><span className="state-pill">{pill}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>
  <section className="section texas-side-program"><div className="texas-share-card"><div><p className="eyebrow">POSSIBLE STATE RECORD?</p><h2>Keep it intact and call IDNR.</h2><p>Do not clean or freeze a potential record. Keep it cool, contact a district fisheries biologist, and arrange a certified-scale weighing with two witnesses.</p></div><a className="btn secondary" href={links.records}>State-record instructions ↗</a></div></section>
  <section className="section final-cta challenge-final"><p className="eyebrow">READY TO START?</p><h2>Pick five species that fit your waters.</h2><p>A practical route could combine bluegill, crappie, largemouth bass, channel catfish and freshwater drum—but every catch must follow current water-specific regulations.</p><div className="actions"><a className="btn primary" href={links.waters}>Explore Illinois waters ↗</a><a className="btn secondary" href={links.license}>Buy an Illinois license ↗</a></div></section><footer><strong>FISH THE FIFTY</strong><span>Built for anglers who want to fish farther.</span></footer>
  </main>; }
