import type { Metadata } from "next";
export const metadata: Metadata = { title: "Wisconsin Anglers’ Club | Fish the Fifty", description: "Explore Hooked on Wisconsin Anglers’ Club: kept fish, live release and Mixed Bag awards, qualifying sizes and official applications." };
const club = "https://dnr.wisconsin.gov/topic/Fishing/anglersclub";
const kept = "https://dnr.wisconsin.gov/topic/fishing/anglersclub/keptfish.html";
const release = "https://dnr.wisconsin.gov/topic/fishing/anglersclub/liverelease.html";
const mixed = "https://dnr.wisconsin.gov/topic/fishing/anglersclub/mixedbag.html";
const records = "https://dnr.wisconsin.gov/topic/Fishing/recordfish";
const sizes = [
  ["Largemouth bass", "6 lb", "22 in"], ["Smallmouth bass", "5 lb", "20 in"],
  ["Brook trout — inland", "2 lb", "16 in"], ["Brown trout — inland", "6 lb", "24 in"],
  ["Rainbow trout — inland", "5 lb", "24 in"], ["Walleye", "10 lb", "29 in"],
  ["Northern pike", "18 lb", "40 in"], ["Muskellunge", "30 lb", "45 in"],
  ["Freshwater drum", "15 lb", "28 in"],
] as const;
export default function WisconsinChallengePage() {
  return <main>
    <header className="nav-shell"><div className="nav-wrap"><a className="brand" href="/">FISH THE FIFTY</a><nav aria-label="Main navigation"><a href="/states">States</a><a href="/#challenges">Challenges</a><a href="/#progress">My Progress</a></nav></div></header>
    <div className="breadcrumb"><a href="/states">States</a><span aria-hidden="true"> / </span><span>Wisconsin</span></div>
    <section className="page-hero challenge-hero"><div className="page-hero-inner"><p className="eyebrow">WISCONSIN · OFFICIAL ANGLER RECOGNITION</p><h1>Get hooked.<br />Build your Wisconsin collection.</h1><p className="lead">Pursue a trophy catch or discover ten different species. The Hooked on Wisconsin Anglers’ Club recognizes kept fish, live releases and a lifetime Mixed Bag of Wisconsin catches.</p><div className="state-facts"><span>3 award categories</span><span>Free membership</span><span>Residents &amp; visitors · all ages</span></div><div className="actions"><a className="btn primary" href="#categories">Choose your category ↓</a><a className="btn secondary" href={club} target="_blank" rel="noreferrer">Official club &amp; application ↗</a></div></div></section>
    <section className="section" id="categories"><div className="section-heading"><p className="eyebrow">THREE WAYS TO QUALIFY</p><h2>Big fish. More species. Your choice.</h2><p>Catch fish legally by pole and line in Wisconsin waters. Review the official category requirements before your trip.</p></div><div className="card-grid">
      <article className="challenge-card"><span className="state-pill">MINIMUM WEIGHT</span><h3>Kept Fish</h3><p>Meet the species’ weight threshold. Weigh the whole, unfrozen fish on a commercial scale to the nearest half ounce. Two witnesses must sign the application; include a clear side-view photograph.</p><a href={kept} target="_blank" rel="noreferrer">Weights &amp; kept-fish rules ↗</a></article>
      <article className="challenge-card"><span className="state-pill">MINIMUM LENGTH</span><h3>Live Release</h3><p>Meet the species’ length threshold. Have a witness measure from snout to tail to the nearest quarter inch and attest to the length and live release. Take the required side-view photo at the catch site.</p><a href={release} target="_blank" rel="noreferrer">Lengths &amp; release rules ↗</a></article>
      <article className="challenge-card"><span className="state-pill">LIFETIME SPECIES COLLECTION</span><h3>Mixed Bag</h3><p>Catch and release different species, regardless of size. Photograph each in a clear close-up side view for identification. Earn a patch for every ten species, accumulated over your lifetime.</p><a href={mixed} target="_blank" rel="noreferrer">Mixed Bag requirements ↗</a></article>
    </div></section>
    <section className="section qualification-section alabama-size-section"><div className="section-heading"><p className="eyebrow">SELECTED CLUB QUALIFYING SIZES</p><h2>Set a target for your next trip.</h2><p>These are selected Anglers’ Club minimums, not fishing possession limits. Great Lakes trout have different thresholds from inland trout. Check the complete official lists and current regulations.</p></div><div className="qualification-table-wrap alabama-table-wrap"><table><caption className="visually-hidden">Selected Wisconsin Anglers’ Club qualifying weights and lengths</caption><thead><tr><th scope="col">Species</th><th scope="col">Kept Fish weight</th><th scope="col">Live Release length</th></tr></thead><tbody>{sizes.map(([species,weight,length]) => <tr key={species}><th scope="row">{species}</th><td>{weight}</td><td>{length}</td></tr>)}</tbody></table></div></section>
    <section className="section challenge-layout"><div><p className="eyebrow">DOCUMENT AND SUBMIT</p><h2>Make your catch count.</h2><ol className="challenge-steps"><li><strong>Check your license and water’s rules.</strong><span>Follow Wisconsin’s current fishing regulations and the club’s license requirements.</span></li><li><strong>Capture the category’s evidence.</strong><span>Keep clear side-view photos and obtain the required measurements and witness signatures. Mixed Bag entries need photos that identify each species.</span></li><li><strong>Complete the official application.</strong><span>Use the form linked on the DNR club page and mail it with the required photographs to the address on the form.</span></li><li><strong>Meet the January 15 deadline.</strong><span>The membership year runs January 1–December 31. Entries must be received by January 15 of the following year.</span></li></ol><a className="btn primary" href={club} target="_blank" rel="noreferrer">Get the official application ↗</a></div><aside className="challenge-side"><p className="eyebrow">YOUR AWARD COLLECTION</p><h2>Patches, a certificate and club membership.</h2><p>The free club awards embroidered patches, a certificate and a membership card. Kept Fish and Live Release recognize qualifying species; Mixed Bag adds a patch at each ten-species milestone.</p><p>Submit the year’s Mixed Bag photos by the deadline while building toward your lifetime total.</p><a className="btn secondary" href="https://dnr.wisconsin.gov/topic/Fishing/regulations" target="_blank" rel="noreferrer">Current fishing regulations ↗</a></aside></section>
    <section className="section"><div className="section-heading"><p className="eyebrow">A SEPARATE RECORD PROGRAM</p><h2>Think you caught a state record?</h2><p>Wisconsin also maintains hook-and-line, alternate-method and live-release state records. These have their own applications and verification requirements.</p></div><div className="card-grid"><article className="challenge-card"><span className="state-pill">WEIGHT RECORDS</span><h3>Preserve the evidence.</h3><p>For a possible retained record, do not clean or freeze the fish. Keep it cool on ice, arrange a witnessed certified-scale weighing and contact DNR for species verification.</p><a href={records} target="_blank" rel="noreferrer">Record rules &amp; applications ↗</a></article><article className="challenge-card"><span className="state-pill">LENGTH RECORDS</span><h3>Document and release.</h3><p>The separate live-release record category requires measurement photographs, release in good condition into the same water and an application within 30 days of the catch. Review the complete protocol before targeting a record.</p><a href="https://dnr.wisconsin.gov/topic/Fishing/recordfish/LiveRelease" target="_blank" rel="noreferrer">Live-release record protocol ↗</a></article></div></section>
    <section className="section final-cta challenge-final"><p className="eyebrow">READY TO START?</p><h2>Choose a trophy or start with ten species.</h2><p>Pack your camera and measuring rule, check the official requirements, and plan your Wisconsin waters.</p><div className="actions"><a className="btn primary" href={club} target="_blank" rel="noreferrer">Explore the official club ↗</a><a className="btn secondary" href="/states">Back to all states</a></div></section>
    <footer><strong>FISH THE FIFTY</strong><span>Built for anglers who want to fish farther.</span></footer>
  </main>;
}
