import type { Metadata } from "next";
import { accessAreas, appleMapSearch, checkedDate, checkedLabel, googleMapSearch, sources } from "./guide-data";

export const metadata: Metadata = {
  title: "Sooner Lake Fishing Guide | Fish the Fifty",
  description: "Plan a Sooner Lake fishing trip with official access, boat-ramp, check-in, species, and area-specific regulation information.",
};

export default function SoonerLakePage() {
  return (
    <>
      <a className="skip-link" href="#guide-content">Skip to lake guide</a>
      <header className="nav-shell"><div className="nav-wrap"><a className="brand" href="/">FISH THE FIFTY</a><nav aria-label="Main navigation"><a href="/states">States</a><a href="/#challenges">Challenges</a><a href="/#progress">My Progress</a></nav></div></header>
      <main id="guide-content" className="river-guide">
        <div className="breadcrumb"><a href="/states">States</a><span aria-hidden="true"> / </span><a href="/states/oklahoma">Oklahoma</a><span aria-hidden="true"> / </span><span>Sooner Lake</span></div>
        <section className="page-hero river-hero"><div className="page-hero-inner river-hero-grid"><div><p className="eyebrow">OKLAHOMA · WATER GUIDE 03</p><h1>Sooner<br />Lake.</h1><p className="lead">A 5,400-acre reservoir between Stillwater and Ponca City, managed by OG&E and known for bass, hybrid bass, saugeye, catfish, and crappie.</p><div className="actions"><a className="btn primary" href="#access">Find access</a><a className="btn secondary" href="#rules">Know the rules</a></div></div><aside className="river-brief" aria-label="Lake at a glance"><p className="eyebrow">AT A GLANCE</p><dl><div><dt>Where</dt><dd>Noble & Pawnee counties</dd></div><div><dt>Location</dt><dd>25 mi north of Stillwater</dd></div><div><dt>Surface area</dt><dd>5,400 acres</dd></div><div><dt>Shoreline</dt><dd>51.8 miles</dd></div></dl><a href={sources.area.url}>ODWC lake listing <span aria-hidden="true">↗</span></a></aside></div></section>

        <div className="guide-shell">
          <aside className="stocking-notice" aria-labelledby="rules-heading"><p className="eyebrow">AREA RULES · <time dateTime={checkedDate}>{checkedLabel}</time></p><h2 id="rules-heading">Know the restricted zones.</h2><p>Fishing is prohibited from the dam, the fenced area below the dam, and the north bank of the intake channel. The buoy-marked intake channel, discharge channel, and spillway embankment are bank fishing only—no float tubes or wading.</p><a className="text-link" href={sources.area.url}>Read the complete ODWC listing <span aria-hidden="true">↗</span></a></aside>
          <nav className="guide-jump-links" aria-label="On this page"><a href="#access">Access & maps</a><a href="#species">Species & tactics</a><a href="#rules">Limits & zones</a><a href="#conditions">Before you go</a><a href="#sources">Sources</a></nav>

          <section id="access" className="guide-section"><div className="guide-section-heading"><div><p className="eyebrow">01 / GET ON THE LAKE</p><h2>Choose your access.</h2></div><a className="text-link" href={sources.lakeMap.url}>Lake map (PDF) <span aria-hidden="true">↗</span></a></div><p className="guide-intro">ODWC lists two OG&E-managed boat ramps and identifies specific bank-only zones. Map buttons search the named location; use the official lake map and posted signs to confirm the entrance.</p><div className="access-grid">{accessAreas.map((area, index) => <article className="access-card" key={area.id}><div className="access-card-top"><span className="state-pill">{area.type}</span><span className="access-number" aria-hidden="true">0{index + 1}</span></div><h3>{area.name}</h3><p>{area.description}</p><p className="access-note">{area.note}</p><div className="map-links"><a href={googleMapSearch(area.mapQuery)} aria-label={`Search Google Maps for ${area.name}`}>Google Maps <span aria-hidden="true">↗</span></a><a href={appleMapSearch(area.mapQuery)} aria-label={`Search Apple Maps for ${area.name}`}>Apple Maps <span aria-hidden="true">↗</span></a></div></article>)}</div></section>

          <section id="species" className="guide-section fishing-grid"><div><p className="eyebrow">02 / PLAN YOUR FISHING</p><h2>Warmwater variety.</h2><p className="guide-intro">ODWC lists largemouth bass, hybrid striped bass, saugeye, blue catfish, and black and white crappie as species of interest. Brush piles are used for fish habitat, and Florida-strain largemouth bass are stocked.</p><div className="species-list">{["Largemouth bass", "Hybrid striped bass", "Saugeye", "Blue catfish", "Black crappie", "White crappie"].map((fish) => <span key={fish}>{fish}</span>)}</div><p className="source-note"><a href={sources.area.url}>ODWC species & management notes <span aria-hidden="true">↗</span></a></p><div className="tackle-note"><h3>Fish the Fifty starting setup</h3><p>For a fly-focused search, try an 8-weight with a sink or sink-tip line, 6–8 feet of 12–16 lb fluorocarbon, and weighted Clousers, crayfish, Woolly Buggers, or sculpin patterns. Start around riprap, rocky structure, deeper flats, and warm-water discharge, then adjust to depth and wind.</p><a className="text-link" href={sources.fishingTrail.url}>TravelOK fishing trail notes <span aria-hidden="true">↗</span></a></div></div><div className="season-notes"><article><span className="eyebrow">BASS & HYBRIDS</span><h3>Work structure first</h3><p>Brush piles and rocky edges are logical starting points. Let the depth and wind determine whether you fish the bank, suspend, or work deeper water.</p></article><article><span className="eyebrow">SAUGEYE & WALLEYE FAMILY</span><h3>Check the limit</h3><p>ODWC lists a combined six-fish daily limit for walleye, sauger, and saugeye with an 18-inch minimum. Verify the current listing before keeping fish.</p></article><article><span className="eyebrow">CATFISH & CRAPPIE</span><h3>Read the lake map</h3><p>The official lake map and ramp information are the best starting points for locating legal access and planning a boat day.</p></article><div className="resource-links"><a href={sources.lakeMap.url}>OWRB Sooner Lake map ↗</a><a href={sources.fishingTrail.url}>Oklahoma Fishing Trail ↗</a></div></div></section>

          <section id="rules" className="guide-section"><p className="eyebrow">03 / LIMITS & ACCESS</p><h2>Keep the area rules close.</h2><div className="rules-grid"><article className="rule-card special-rule"><span className="eyebrow">STRIPED BASS</span><h3>5 per day</h3><p>Minimum length is 20 inches. Confirm the current regulation before keeping a fish.</p><a className="text-link" href={sources.area.url}>ODWC limits ↗</a></article><article className="rule-card special-rule"><span className="eyebrow">WALLEYE FAMILY</span><h3>6 combined per day</h3><p>Walleye, sauger, and saugeye share a six-fish combined daily limit with an 18-inch minimum length.</p><a className="text-link" href={sources.area.url}>ODWC limits ↗</a></article><article className="rule-card"><h3>Other species</h3><p>ODWC’s Sooner Lake listing says other fish must be returned to the water immediately. Check the current listing and statewide regulations before keeping a catch.</p><div className="resource-links"><a href={sources.area.url}>Area-specific regulations ↗</a><a href={sources.license.url}>Oklahoma fishing license ↗</a></div></article><article className="rule-card"><h3>Nonresident check-in</h3><p>Nonresidents must check in and out for certain public hunting and fishing areas. Confirm whether your planned Sooner Lake access requires the free process before you go.</p><a className="text-link" href={sources.checkIn.url}>Check-in instructions ↗</a></article></div></section>

          <section id="conditions" className="guide-section conditions-section"><p className="eyebrow">04 / BEFORE YOU GO</p><h2>Check the current status.</h2><p className="guide-intro">Sooner Lake is operated by OG&E, and access conditions, restrictions, and check-in requirements can change. Use the official links below before launching or fishing the bank.</p><div className="condition-grid"><a className="condition-card" href={sources.area.url}><span>CURRENT LISTING</span><h3>ODWC Sooner Lake <span aria-hidden="true">↗</span></h3><p>Review limits, restricted zones, contacts, ramps, and current catch uploads.</p></a><a className="condition-card" href={sources.checkIn.url}><span>NONRESIDENTS</span><h3>Public check-in <span aria-hidden="true">↗</span></h3><p>Use the free process when the area and your visit require it.</p></a><a className="condition-card" href={sources.operator.url}><span>LAKE OPERATOR</span><h3>OG&E <span aria-hidden="true">↗</span></h3><p>Check operator information and use the lake office contact listed by ODWC.</p></a></div><p className="condition-footnote">Lake office: (405) 553-2919 · Fisheries management: (580) 304-9243 · Pawnee warden: (918) 645-6116 · Noble warden: (580) 370-0700</p></section>

          <section id="sources" className="guide-section source-section"><div><p className="eyebrow">OFFICIAL SOURCES</p><h2>Plan with current information.</h2><p>Guide checked <time dateTime={checkedDate}>{checkedLabel}</time>. Regulations and access conditions can change; the linked agencies provide the latest information. The fly setup above is a Fish the Fifty starting point, not an official regulation.</p></div><ul>{[sources.area, sources.checkIn, sources.lakeMap, sources.fishingTrail, sources.license].map((source) => <li key={source.url}><a href={source.url}>{source.label} <span aria-hidden="true">↗</span></a></li>)}</ul></section>
          <div className="guide-return"><a className="btn primary" href="/states/oklahoma">← Back to Oklahoma</a><a className="text-link" href="/states">Explore all 50 states →</a></div>
        </div>
      </main>
      <footer><strong>FISH THE FIFTY</strong><span>Built for anglers who want to fish farther.</span></footer>
    </>
  );
}
