import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Massachusetts Freshwater Sportfishing Awards | Fish the Fifty",
  description: "Explore Massachusetts freshwater bronze and gold pin awards, release lengths, keep weights, submission deadlines, and its separate saltwater derby.",
};

const links = {
  freshwater: "https://www.mass.gov/guides/freshwater-sportfishing-awards-program",
  leaders: "https://www.mass.gov/info-details/sportfishing-awards-current-leaders",
  saltwater: "https://www.mass.gov/saltwater-fishing-derby",
  derbyRules: "https://www.mass.gov/info-details/saltwater-fishing-derby-information-and-rules",
};

const examples = [
  ["Brook trout", "16 in.", "14 in.", "2 lb.", "1 lb."],
  ["Brown trout", "22 in.", "18 in.", "4 lb.", "2 lb."],
  ["Rainbow trout", "20 in.", "16 in.", "3 lb.", "2 lb."],
  ["Largemouth bass", "21 in.", "18 in.", "7 lb.", "4 lb."],
  ["Smallmouth bass", "20 in.", "17 in.", "4 lb. 8 oz.", "3 lb."],
  ["Crappie", "14 in.", "11 in.", "1 lb. 8 oz.", "1 lb."],
  ["Sunfish", "10 in.", "8 in.", "12 oz.", "8 oz."],
  ["Walleye", "24 in.", "18 in.", "4 lb.", "2 lb."],
] as const;

export default function MassachusettsChallengePage() {
  return <main>
    <header className="nav-shell"><div className="nav-wrap"><a className="brand" href="/">FISH THE FIFTY</a><nav aria-label="Main navigation"><a href="/states">States</a><a href="/#challenges">Challenges</a><a href="/members">My Progress</a></nav></div></header>
    <div className="breadcrumb"><a href="/states">States</a><span aria-hidden="true"> / </span><span>Massachusetts</span></div>
    <section className="page-hero challenge-hero"><div className="page-hero-inner"><p className="eyebrow">MASSACHUSETTS · MASSWILDLIFE</p><h1>Freshwater<br />Sportfishing Awards.</h1><p className="lead">Catch an eligible trophy fish in public-access Massachusetts water. Meet a species’ release length or harvested weight for a bronze pin, or lead a category at year’s end for a gold pin and plaque.</p><div className="state-facts"><span>Release or keep</span><span>Bronze and gold pins</span><span>30 days to enter</span></div><div className="actions"><a className="btn primary" href="#sizes">Compare trophy sizes ↓</a><a className="btn secondary" href={links.freshwater} target="_blank" rel="noreferrer">Official freshwater awards ↗</a></div></div></section>
    <section className="section challenge-layout"><div><p className="eyebrow">CATCH AND RELEASE</p><h2>Measure at the water.</h2><ol className="challenge-steps"><li><strong>Choose a species and legal water.</strong><span>MassWildlife requires a hook-and-line catch from eligible Massachusetts public-access water or an eligible interstate pond. Check your license and current local rules.</span></li><li><strong>Photograph the length.</strong><span>At the capture site, take a clear side-view photo of the entire fish against a flat, labeled measuring device so the measurement is readable.</span></li><li><strong>Release immediately and enter.</strong><span>Return the fish at the same location, then complete the catch-and-release affidavit within 30 days. December entries are due by January 10 of the following year.</span></li></ol><a className="btn primary" href={links.freshwater} target="_blank" rel="noreferrer">Read release rules and apply ↗</a></div><aside className="challenge-side"><p className="eyebrow">CATCH AND KEEP</p><h2>Weigh on a certified scale.</h2><p>For the keep category, the fish must meet the species’ minimum weight. Follow MassWildlife’s photo and certified-scale rules, then complete the catch-and-keep affidavit on time.</p><p>Adult and youth thresholds differ. Youth anglers are 17 or younger; ages 15–17 need a fishing license. Review the official rules before retaining a fish.</p><a className="btn secondary" href={links.freshwater} target="_blank" rel="noreferrer">Read keep rules and apply ↗</a></aside></section>
    <section className="section qualification-section alabama-size-section" id="sizes"><div className="section-heading"><p className="eyebrow">SELECT FRESHWATER MINIMUMS</p><h2>Compare both award paths.</h2><p>Release lengths and keep weights are separate standards. These are selected species; check MassWildlife’s complete current tables before entering.</p></div><div className="qualification-table-wrap alabama-table-wrap" style={{ overflowX: "auto" }}><table style={{ minWidth: "680px" }}><caption className="visually-hidden">Selected Massachusetts freshwater sportfishing award sizes by age and category</caption><thead><tr><th scope="col">Species</th><th scope="col">Adult release</th><th scope="col">Youth release</th><th scope="col">Adult keep</th><th scope="col">Youth keep</th></tr></thead><tbody>{examples.map(([species, adultLength, youthLength, adultWeight, youthWeight]) => <tr key={species}><th scope="row">{species}</th><td>{adultLength}</td><td>{youthLength}</td><td>{adultWeight}</td><td>{youthWeight}</td></tr>)}</tbody></table></div><div className="actions"><a className="btn primary" href={links.freshwater} target="_blank" rel="noreferrer">All current award sizes ↗</a></div></section>
    <section className="section"><div className="section-heading"><p className="eyebrow">WHAT THE AWARDS MEAN</p><h2>A pin now. A leaderboard all year.</h2><p>The program runs by calendar year. MassWildlife recognizes qualifying fish with bronze pins and category leaders with gold pins and plaques. Angler of the Year awards recognize anglers who submit the greatest variety of eligible trophy species.</p></div><div className="card-grid"><article className="challenge-card"><span className="state-pill">BRONZE</span><h3>Meet a minimum</h3><p>Submit an eligible species at its release length or keep weight to earn its bronze pin.</p><a href={links.freshwater} target="_blank" rel="noreferrer">Award details ↗</a></article><article className="challenge-card"><span className="state-pill">GOLD</span><h3>Lead a species</h3><p>The largest or longest qualifying fish in an eligible category earns a gold pin and plaque.</p><a href={links.leaders} target="_blank" rel="noreferrer">Current leaders ↗</a></article><article className="challenge-card"><span className="state-pill">ANGLER OF THE YEAR</span><h3>Seek variety</h3><p>Pursue qualifying catches across different species during the calendar year.</p><a href={links.freshwater} target="_blank" rel="noreferrer">Program overview ↗</a></article></div></section>
    <section className="section challenge-layout"><div><p className="eyebrow">SALTWATER CHALLENGE</p><h2>Explore the separate derby.</h2><p>Massachusetts’ Division of Marine Fisheries runs a Saltwater Fishing Derby with weigh-in and catch-and-release divisions, species-specific minimums, pins, trophies, and Angler of the Year recognition. It has separate rules and entry procedures from MassWildlife’s freshwater awards.</p><a className="btn primary" href={links.saltwater} target="_blank" rel="noreferrer">Explore saltwater derby ↗</a></div><aside className="challenge-side"><p className="eyebrow">CHECK BEFORE FISHING</p><h2>Different water, different rules.</h2><p>Read the derby’s current eligibility, species, and permit requirements for coastal fishing. Use the freshwater award page for inland size standards and affidavits.</p><a className="btn secondary" href={links.derbyRules} target="_blank" rel="noreferrer">Saltwater derby rules ↗</a></aside></section>
    <section className="section final-cta challenge-final"><p className="eyebrow">READY TO START?</p><h2>Pick a fish and an award path.</h2><p>Review the current MassWildlife tables and affidavits, then photograph and submit a qualifying catch within the program deadline.</p><div className="actions"><a className="btn primary" href={links.freshwater} target="_blank" rel="noreferrer">Open freshwater awards ↗</a><a className="btn secondary" href="/states">Back to all states</a></div></section>
    <footer><strong>FISH THE FIFTY</strong><span>Built for anglers who want to fish farther.</span></footer>
  </main>;
}
