import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Minnesota State Record Fish | Fish the Fifty",
  description: "Explore Minnesota DNR catch-and-release length and certified-weight fish record programs, rules, evidence, and applications.",
};

const links = {
  overview: "https://www.dnr.state.mn.us/fishing/staterecords.html",
  release: "https://www.dnr.state.mn.us/fishing/catch-and-release.html",
  weight: "https://www.dnr.state.mn.us/fishing/certified-weight.html",
  regulations: "https://www.dnr.state.mn.us/regulations/fishing/index.html",
};

const newRecordMinimums = [
  ["Freshwater drum", "31 in."], ["Brook trout", "18 in."],
  ["Brown trout", "24 in."], ["Rainbow trout", "23 in."],
  ["Walleye", "32 in."], ["Channel catfish", "38 in."],
  ["Largemouth bass", "22 in."], ["Smallmouth bass", "22 in."],
] as const;

export default function MinnesotaChallengePage() {
  return <main>
    <header className="nav-shell"><div className="nav-wrap"><a className="brand" href="/">FISH THE FIFTY</a><nav aria-label="Main navigation"><a href="/states">States</a><a href="/#challenges">Challenges</a><a href="/members">My Progress</a></nav></div></header>
    <div className="breadcrumb"><a href="/states">States</a><span aria-hidden="true"> / </span><span>Minnesota</span></div>
    <section className="page-hero challenge-hero"><div className="page-hero-inner"><p className="eyebrow">MINNESOTA · DEPARTMENT OF NATURAL RESOURCES</p><h1>Minnesota<br />State Record Fish.</h1><p className="lead">Challenge a standing Minnesota record by measuring and releasing a fish, or by weighing an eligible catch on a certified scale. The DNR maintains separate rules and applications for each path.</p><div className="state-facts"><span>2 record paths</span><span>Public-access water</span><span>Apply within 90 days</span></div><div className="actions"><a className="btn primary" href="#record-paths">Compare record paths ↓</a><a className="btn secondary" href={links.overview} target="_blank" rel="noreferrer">Official Minnesota records ↗</a></div></div></section>
    <section className="section challenge-layout" id="record-paths"><div><p className="eyebrow">CATCH AND RELEASE</p><h2>Measure a contender and let it swim.</h2><ol className="challenge-steps"><li><strong>Check the current record.</strong><span>For a species with a standing release record, your fish must be at least one-quarter inch longer. If the category has no record, use DNR’s minimum length for a new submission.</span></li><li><strong>Document with a witness.</strong><span>Follow DNR’s photo and measurement instructions. An observer must witness both the catch and release and sign and date the application; girth is desired but optional.</span></li><li><strong>Release and submit.</strong><span>Release the fish in good condition. Complete the catch-and-release application and send its evidence within 90 days of the catch.</span></li></ol><a className="btn primary" href={links.release} target="_blank" rel="noreferrer">Release records and application ↗</a></div><aside className="challenge-side"><p className="eyebrow">CERTIFIED WEIGHT</p><h2>Verify a heavier fish.</h2><p>Compare the current weight record, or check the special benchmark for one of the reopened or newly established categories. Download the certified-weight form before weighing so a witness can sign it.</p><p>Use a state-certified scale, document the weight, and bring the fish and application to a DNR area fisheries office for positive species identification by biologists. Submit the completed materials within 90 days.</p><a className="btn secondary" href={links.weight} target="_blank" rel="noreferrer">Weight records and application ↗</a></aside></section>
    <section className="section qualification-section alabama-size-section"><div className="section-heading"><p className="eyebrow">NEW RELEASE RECORD BENCHMARKS</p><h2>Minimums for a new category.</h2><p>These are DNR’s minimum lengths for a catch-and-release category without a standing record. If a record already exists, the fish must instead exceed the live record by at least one-quarter inch. Check the current DNR list before targeting a species.</p></div><div className="qualification-table-wrap alabama-table-wrap"><table><caption className="visually-hidden">Selected Minnesota minimum lengths for new catch-and-release record submissions</caption><thead><tr><th scope="col">Species</th><th scope="col">New record minimum</th></tr></thead><tbody>{newRecordMinimums.map(([species, length]) => <tr key={species}><th scope="row">{species}</th><td>{length}</td></tr>)}</tbody></table></div><div className="actions"><a className="btn primary" href={links.release} target="_blank" rel="noreferrer">Check standing release records ↗</a></div></section>
    <section className="section"><div className="section-heading"><p className="eyebrow">BOTH RECORD PATHS</p><h2>Start with an eligible catch.</h2><p>Minnesota DNR requires fish to be taken by legal angling during an open season and hours in qualifying Minnesota waters. Fish from hatcheries or waters without public access do not qualify. Confirm license and boundary-water provisions before fishing.</p></div><div className="card-grid"><article className="challenge-card"><span className="state-pill">1 · COMPARE</span><h3>Standing record</h3><p>Use the live DNR lists to see whether your species has a record and which category applies.</p><a href={links.overview} target="_blank" rel="noreferrer">Two DNR programs ↗</a></article><article className="challenge-card"><span className="state-pill">2 · DOCUMENT</span><h3>Witness and evidence</h3><p>Plan for a witness, required measurements or certified weight, photos, and the correct application.</p><a href={links.release} target="_blank" rel="noreferrer">Release instructions ↗</a></article><article className="challenge-card"><span className="state-pill">3 · SUBMIT</span><h3>Within 90 days</h3><p>Send the completed category-specific application and supporting materials by the DNR deadline.</p><a href={links.weight} target="_blank" rel="noreferrer">Weight instructions ↗</a></article></div></section>
    <section className="section final-cta challenge-final"><p className="eyebrow">READY TO PLAN?</p><h2>Check the record. Choose the path.</h2><p>Read Minnesota’s current fishing regulations and the appropriate DNR record application before your next trip.</p><div className="actions"><a className="btn primary" href={links.overview} target="_blank" rel="noreferrer">Minnesota record programs ↗</a><a className="btn secondary" href={links.regulations} target="_blank" rel="noreferrer">Fishing regulations ↗</a></div></section>
    <footer><strong>FISH THE FIFTY</strong><span>Built for anglers who want to fish farther.</span></footer>
  </main>;
}
