import type { Metadata } from "next";
import { accessAreas, appleMapSearch, checkedDate, checkedLabel, googleMapSearch, sources } from "./guide-data";

export const metadata: Metadata = {
  title: "Lake Hefner Fishing Guide | Fish the Fifty",
  description: "Plan a Lake Hefner fishing trip in Oklahoma City with official access, city and state license guidance, species information, and current water resources.",
};

export default function LakeHefnerPage() {
  return (
    <>
      <a className="skip-link" href="#guide-content">Skip to lake guide</a>
      <header className="nav-shell"><div className="nav-wrap"><a className="brand" href="/">FISH THE FIFTY</a><nav aria-label="Main navigation"><a href="/states">States</a><a href="/winter-trout">Winter Trout</a><a href="/#challenges">Challenges</a><a href="/#progress">My Progress</a></nav></div></header>
      <main id="guide-content" className="river-guide">
        <div className="breadcrumb"><a href="/states">States</a><span aria-hidden="true"> / </span><a href="/states/oklahoma">Oklahoma</a><span aria-hidden="true"> / </span><span>Lake Hefner</span></div>
        <section className="page-hero river-hero"><div className="page-hero-inner river-hero-grid"><div><p className="eyebrow">OKLAHOMA · WATER GUIDE 06</p><h1>Lake Hefner.</h1><p className="lead">An urban Oklahoma City lake where drive-up shoreline access, docks, a lighted pier, and a heated fishing dock make a serious fishing session easy to reach.</p><div className="actions"><a className="btn primary" href="#access">Find access</a><a className="btn secondary" href="#rules">Know the rules</a></div></div><aside className="river-brief" aria-label="Lake at a glance"><p className="eyebrow">AT A GLANCE</p><dl><div><dt>Where</dt><dd>Oklahoma City</dd></div><div><dt>Surface area</dt><dd>2,500 acres</dd></div><div><dt>Shoreline</dt><dd>16.4 miles</dd></div><div><dt>Primary focus</dt><dd>Walleye & hybrid bass</dd></div></dl><a href={sources.area.url}>ODWC Hefner listing <span aria-hidden="true">↗</span></a></aside></div></section>

        <div className="guide-shell">
          <aside className="stocking-notice" aria-labelledby="permit-heading"><p className="eyebrow">CITY-WATER UPDATE · <time dateTime={checkedDate}>{checkedLabel}</time></p><h2 id="permit-heading">Bring both licenses.</h2><p>ODWC says a City of Oklahoma City fishing license is required in addition to an Oklahoma state fishing license, unless exempt. Confirm current city rules before fishing, boating, or using a special dock.</p><a className="text-link" href={sources.area.url}>Read the current ODWC Hefner listing <span aria-hidden="true">↗</span></a></aside>
          <nav className="guide-jump-links" aria-label="On this page"><a href="#access">Access & maps</a><a href="#fishing">Species & tactics</a><a href="#rules">Licenses & rules</a><a href="#conditions">Before you go</a><a href="#sources">Sources</a></nav>

          <section id="access" className="guide-section"><div className="guide-section-heading"><div><p className="eyebrow">01 / GET TO THE WATER</p><h2>Choose your access.</h2></div><a className="text-link" href={sources.lakeMap.url}>Lake map (PDF) <span aria-hidden="true">↗</span></a></div><p className="guide-intro">ODWC lists gentle drive-up access on the eastern shoreline, a boat launch and dock, one lighted fishing pier, and an enclosed heated dock. Map buttons search the named access; use the city map and posted signs to confirm entrances and current availability.</p><div className="access-grid">{accessAreas.map((area, index) => <article className="access-card" key={area.id}><div className="access-card-top"><span className="state-pill">{area.type}</span><span className="access-number" aria-hidden="true">0{index + 1}</span></div><h3>{area.name}</h3><p>{area.description}</p><p className="access-note">{area.note}</p><div className="map-links"><a href={googleMapSearch(area.mapQuery)} aria-label={`Search Google Maps for ${area.name}`}>Google Maps <span aria-hidden="true">↗</span></a><a href={appleMapSearch(area.mapQuery)} aria-label={`Search Apple Maps for ${area.name}`}>Apple Maps <span aria-hidden="true">↗</span></a></div></article>)}</div></section>

          <section id="fishing" className="guide-section fishing-grid"><div><p className="eyebrow">02 / PLAN YOUR FISHING</p><h2>Urban water, real variety.</h2><p className="guide-intro">ODWC lists walleye, hybrid striped bass, blue, flathead and channel catfish, white bass, white crappie, bluegill, green sunfish, and largemouth bass as species of interest. The lake is annually stocked with walleye and hybrid striped bass, with occasional channel catfish stocking.</p><div className="species-list">{["Walleye", "Hybrid striped bass", "Blue catfish", "Flathead catfish", "Channel catfish", "White bass", "White crappie", "Bluegill", "Green sunfish", "Largemouth bass"].map((fish) => <span key={fish}>{fish}</span>)}</div><p className="source-note"><a href={sources.area.url}>ODWC species & management notes <span aria-hidden="true">↗</span></a></p><div className="tackle-note"><h3>Fish the Fifty starting setup</h3><p>For shoreline bass, bluegill, and sunfish, start with your Helios 4F 5-weight, a 7½–9-foot leader, foam poppers, small streamers, and a Hare’s Ear or Woolly Bugger. When hybrid bass or walleye push deeper, the Redington Big Game 8-weight with a sink-tip line gives you more authority over weighted baitfish patterns and wind.</p><a className="text-link" href={sources.fishingTrail.url}>TravelOK central fishing trail <span aria-hidden="true">↗</span></a></div></div><div className="season-notes"><article><span className="eyebrow">WALLEYE & HYBRIDS</span><h3>Use depth and wind</h3><p>Annual walleye and hybrid-bass stocking makes Hefner worth checking, but open water and wind can change the fishable zone quickly. Use the OWRB map as a planning reference, not a navigation chart.</p></article><article><span className="eyebrow">SHORELINE SESSION</span><h3>Fish the access windows</h3><p>The drive-up shoreline, pier, and docks make it easy to fish a short window around low light, weather changes, or a quick after-work outing.</p></article><article><span className="eyebrow">CITY LAKE</span><h3>Respect shared use</h3><p>Hefner is also a trail, boating, sailing, and park destination. Keep casts controlled around docks, boat traffic, walkers, and other anglers.</p></article><div className="resource-links"><a href={sources.lakeMap.url}>OWRB Hefner map ↗</a><a href={sources.fishingTrail.url}>Oklahoma Fishing Trail ↗</a><a href={sources.parksMap.url}>OKC parks map ↗</a></div></div></section>

          <section id="rules" className="guide-section"><p className="eyebrow">03 / LICENSES & RULES</p><h2>Know the city-water rules.</h2><div className="rules-grid"><article className="rule-card special-rule"><span className="eyebrow">LICENSES</span><h3>City + state</h3><p>ODWC requires the Oklahoma City fishing license in addition to an Oklahoma state fishing license unless exempt.</p><div className="resource-links"><a href={sources.okcLicense.url}>OKC fishing license ↗</a><a href={sources.stateLicense.url}>State license ↗</a></div></article><article className="rule-card special-rule"><span className="eyebrow">RODS & HOOKS</span><h3>Up to 3 rods</h3><p>ODWC lists up to three rods and reels per person, with no more than three hooks per line. Treble hooks count as one hook.</p><a className="text-link" href={sources.area.url}>Verify current methods ↗</a></article><article className="rule-card"><h3>Bowfishing</h3><p>Bowfishing is listed as daylight-only. Check the city’s special regulations before using a bow, boat, or any method outside ordinary rod-and-reel fishing.</p><a className="text-link" href={sources.okcRules.url}>OKC fishing regulations ↗</a></article><article className="rule-card"><h3>Hours & check-in</h3><p>OKC Parks lists public lake hours of 5 a.m. to 11 p.m.; permitted fishing or boating may operate outside those hours. Nonresidents should also review ODWC’s free public check-in process.</p><div className="resource-links"><a href={sources.okcParks.url}>OKC Parks hours ↗</a><a href={sources.checkIn.url}>Public check-in ↗</a></div></article></div></section>

          <section id="conditions" className="guide-section conditions-section"><p className="eyebrow">04 / BEFORE YOU LEAVE</p><h2>Check the lake and the city.</h2><p className="guide-intro">Lake Hefner is a working municipal water and recreation area. Use the official pages below for current lake data, city rules, access, and shared-use conditions. The OWRB map is not intended to be used as a navigational chart.</p><div className="condition-grid"><a className="condition-card" href={sources.usgs.url}><span>WATER DATA</span><h3>USGS Lake Hefner <span aria-hidden="true">↗</span></h3><p>Review the official Oklahoma City monitoring location and available data.</p></a><a className="condition-card" href={sources.okcParks.url}><span>CITY STATUS</span><h3>OKC Parks <span aria-hidden="true">↗</span></h3><p>Check lake hours, permits, facilities, trails, and current city information.</p></a><a className="condition-card" href={sources.area.url}><span>FISHING INFO</span><h3>ODWC Hefner <span aria-hidden="true">↗</span></h3><p>Review species, stocking, access, licenses, methods, and agency contacts.</p></a></div><p className="condition-footnote">Lake office: (405) 297-2211 · Fisheries management: (405) 325-7288 · Oklahoma City Lakes: (405) 755-4014</p></section>

          <section id="sources" className="guide-section source-section"><div><p className="eyebrow">OFFICIAL SOURCES</p><h2>Plan with current information.</h2><p>Guide checked <time dateTime={checkedDate}>{checkedLabel}</time>. City rules, access, water data, and fishing regulations can change. The fly setup above is a Fish the Fifty starting point, not an official regulation.</p></div><ul>{[sources.area, sources.okcParks, sources.okcRules, sources.okcLicense, sources.stateLicense, sources.checkIn, sources.lakeMap, sources.fishingTrail, sources.usgs, sources.parksMap].map((source) => <li key={source.url}><a href={source.url}>{source.label} <span aria-hidden="true">↗</span></a></li>)}</ul></section>
          <div className="guide-return"><a className="btn primary" href="/states/oklahoma">← Back to Oklahoma</a><a className="text-link" href="/states">Explore all 50 states →</a></div>
        </div>
      </main>
      <footer><strong>FISH THE FIFTY</strong><span>Built for anglers who want to fish farther.</span></footer>
    </>
  );
}
