import type { Metadata } from "next";
import IndianaTracker from "./tracker";

export const metadata: Metadata = { title: "Indiana Fish of the Year & State Records | Fish the Fifty", description: "Plan Indiana's Fish of the Year and State Record Fish entries with official measurement and submission rules." };
const base = "https://www.in.gov/dnr/fish-and-wildlife/fishing/indiana-record-fish-program/";
const winners = `${base}fish-of-the-year-winners`;
const records = `${base}records/`;
export default function IndianaChallengePage() {
  return <main>
    <header className="nav-shell"><div className="nav-wrap"><a className="brand" href="/">FISH THE FIFTY</a><nav aria-label="Main navigation"><a href="/states">States</a><a href="/#challenges">Challenges</a><a href="/members">My Progress</a></nav></div></header>
    <div className="breadcrumb"><a href="/states">States</a><span aria-hidden="true"> / </span><span>Indiana</span></div>
    <section className="page-hero challenge-hero"><div className="page-hero-inner"><p className="eyebrow">INDIANA · DEPARTMENT OF NATURAL RESOURCES</p><h1>Indiana Record<br />Fish Program.</h1><p className="lead">Pursue the longest eligible fish of the year or challenge an all-time state record by certified weight. Indiana DNR recognizes winning anglers with a certificate and jacket patch.</p><div className="state-facts"><span>Fish of the Year · length</span><span>State record · weight</span><span>Free to enter</span></div><div className="actions"><a className="btn primary" href="#paths">Compare the two paths ↓</a><a className="btn secondary" href={base} target="_blank" rel="noreferrer">Official Indiana rules ↗</a></div></div></section>
    <section className="section challenge-layout" id="paths"><div><p className="eyebrow">FISH OF THE YEAR</p><h2>Go for length this year.</h2><ol className="challenge-steps"><li><strong>Catch an eligible species legally.</strong><span>Fish must be taken by hook and line from qualifying Indiana waters. Private waters can qualify if there is no fee for the fish taken.</span></li><li><strong>Measure and photograph.</strong><span>Use total length, except fork length for shovelnose sturgeon. Take a clear full side-view photo on a measuring board or beside a tape.</span></li><li><strong>Have a witness.</strong><span>Provide one non-relative witness who observed the length measurement and a license copy if required.</span></li><li><strong>Enter by December 15.</strong><span>Submit online or email the form in the calendar year of the catch. Indiana DNR says late entries are eligible for the following year.</span></li></ol><a className="btn primary" href={base} target="_blank" rel="noreferrer">Submit Fish of the Year ↗</a></div><aside className="challenge-side"><p className="eyebrow">STATE RECORD FISH</p><h2>Challenge the all-time mark.</h2><p>Both weight and length are required. Weigh the fish before freezing on an Indiana-certified scale accurate to one ounce, retain its scale inspection report, and keep the fish available for possible biologist identification.</p><p>Two non-relative witnesses must sign the form. Provide side-view photos, scale details, and a license copy if required.</p><a className="btn secondary" href={records} target="_blank" rel="noreferrer">See standing state records ↗</a></aside></section>
    <section className="section"><div className="section-heading"><p className="eyebrow">PLAN YOUR ENTRY</p><h2>Compare before you cast.</h2><p>Fish of the Year is decided by length for each recognized species category. State records use weight first, then length. Check the current lists because the marks can change.</p></div><div className="card-grid"><article className="challenge-card"><span className="state-pill">CURRENT YEAR</span><h3>Fish of the Year winners</h3><p>Browse the latest published winning lengths for ideas and species categories.</p><a href={winners} target="_blank" rel="noreferrer">View winners ↗</a></article><article className="challenge-card"><span className="state-pill">ALL-TIME</span><h3>State record list</h3><p>Compare your potential catch with Indiana’s current official record weights.</p><a href={records} target="_blank" rel="noreferrer">View records ↗</a></article><article className="challenge-card"><span className="state-pill">OFFICIAL ENTRY</span><h3>Rules and forms</h3><p>Use DNR’s current instructions for photos, witnesses, licenses, and submission.</p><a href={base} target="_blank" rel="noreferrer">Open entry page ↗</a></article></div></section>
    <section className="section" id="tracker"><div className="section-heading"><p className="eyebrow">YOUR PRIVATE WATCH LIST</p><h2>Choose your target fish.</h2><p>Keep a local list of species to research. Use Indiana’s current program page to confirm each species is eligible.</p></div><IndianaTracker /></section>
    <section className="section challenge-layout"><div><p className="eyebrow">COMMON ELIGIBILITY RULES</p><h2>Document the catch clearly.</h2><p>Indiana requires legal hook-and-line catches and a good side-view photograph. Fish from waters with artificial feeding programs do not qualify. A copy of the angler’s license must accompany an entry when a license was required.</p><p>Fish caught on the specified Indiana border reaches of the Ohio or Wabash rivers can be considered when the angler held an Indiana fishing license at the time.</p><a className="btn primary" href={base} target="_blank" rel="noreferrer">Read full eligibility rules ↗</a></div><aside className="challenge-side"><p className="eyebrow">BIG FISH IN HAND?</p><h2>Preserve a possible record.</h2><p>Contact a District Fisheries office before weighing if you can. Indiana DNR says its district offices have certified scales and asks anglers to arrange an appointment with a biologist. Keep the fish intact for possible verification.</p><a className="btn secondary" href={base} target="_blank" rel="noreferrer">State record instructions ↗</a></aside></section>
    <section className="section final-cta challenge-final"><p className="eyebrow">READY TO START?</p><h2>Pick a species and check the current mark.</h2><p>Plan a legal Indiana trip, keep the measurement evidence, and use the official DNR entry form.</p><div className="actions"><a className="btn primary" href={base} target="_blank" rel="noreferrer">Open Indiana Record Fish Program ↗</a><a className="btn secondary" href="/states">Back to all states</a></div></section>
    <footer><strong>FISH THE FIFTY</strong><span>Built for anglers who want to fish farther.</span></footer>
  </main>;
}
