import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Louisiana Fish Records | Fish the Fifty",
  description: "Explore Louisiana Outdoor Writers Association Top Ten fish records, rod and reel and fly rod rules, documentation, and official Louisiana fishing regulations.",
};

const links = {
  records: "https://louisianaoutdoorwriters.com/awards-records/fish-hunt-records/",
  regulations: "https://www.wlf.louisiana.gov/page/seasons-and-regulations",
  licenses: "https://www.wlf.louisiana.gov/page/recreational-fishing-licenses-and-permits",
  waters: "https://www.wlf.louisiana.gov/go-fishing",
};

export default function LouisianaChallengePage() {
  return <main>
    <header className="nav-shell"><div className="nav-wrap"><a className="brand" href="/">FISH THE FIFTY</a><nav aria-label="Main navigation"><a href="/states">States</a><a href="/#challenges">Challenges</a><a href="/members">My Progress</a></nav></div></header>
    <div className="breadcrumb"><a href="/states">States</a><span aria-hidden="true"> / </span><span>Louisiana</span></div>
    <section className="page-hero challenge-hero"><div className="page-hero-inner"><p className="eyebrow">LOUISIANA · FISH RECORDS</p><h1>Make the<br />Top Ten.</h1><p className="lead">The Louisiana Outdoor Writers Association (LOWA) maintains freshwater and saltwater fish records for rod and reel and fly rod catches. A qualifying Top Ten catch can earn a LOWA certificate and eligibility for its Fish of the Year award.</p><div className="state-facts"><span>Freshwater + saltwater</span><span>Rod and reel + fly rod</span><span>Submit within 60 days</span></div><div className="actions"><a className="btn primary" href="#record-paths">Explore record paths ↓</a><a className="btn secondary" href={links.records} target="_blank" rel="noreferrer">Current LOWA records ↗</a></div></div></section>
    <section className="section challenge-layout" id="record-paths"><div><p className="eyebrow">ROD AND REEL</p><h2>Find a place in the record book.</h2><ol className="challenge-steps"><li><strong>Check a listed species and standing weights.</strong><span>LOWA accepts eligible species in its current records and ranks the Top Ten by weight.</span></li><li><strong>Catch the fish legally in eligible water.</strong><span>LOWA requires public-access Louisiana waters and a sporting catch hooked by the mouth. Its offshore and border-water provisions have additional details.</span></li><li><strong>Verify weight, species, and evidence.</strong><span>Use a qualifying inspected scale, arrange a biologist or recognized authority to identify the fish, and collect the required photos and witness signatures.</span></li><li><strong>Apply within 60 days.</strong><span>Use LOWA’s current application, rules checkoff, photographs, and processing fee.</span></li></ol><a className="btn primary" href={links.records} target="_blank" rel="noreferrer">Read LOWA rules and application ↗</a></div><aside className="challenge-side"><p className="eyebrow">FLY ROD DIVISION</p><h2>Bring your fly and leader.</h2><p>LOWA also keeps a separate fly fishing record division. Its fly rod rules specify class tippet and shock leader limits and require the leader, tippet, and fly with an application. The fly is not returned.</p><p>Read the complete fly rod rules before fishing: the same species, weighing, identification, photo, witness, fee, and 60-day submission requirements also matter.</p><a className="btn secondary" href={links.records} target="_blank" rel="noreferrer">View fly rod requirements ↗</a></aside></section>
    <section className="section"><div className="section-heading"><p className="eyebrow">RECORD EVIDENCE</p><h2>Prepare before the catch.</h2><p>LOWA’s requirements are detailed. Use its current forms as your checklist; a potential first-place fish needs a physical identification at a Louisiana Department of Wildlife and Fisheries location.</p></div><div className="card-grid"><article className="challenge-card"><span className="state-pill">1 · IDENTIFY</span><h3>Species confirmation</h3><p>Arrange identification by an LDWF fish biologist or another qualifying biologist or recognized authority. First place requires physical examination.</p><a href={links.records} target="_blank" rel="noreferrer">LOWA identification rules ↗</a></article><article className="challenge-card"><span className="state-pill">2 · DOCUMENT</span><h3>Scale and photos</h3><p>Keep the fractional weight from an eligible inspected scale, a clear side photo of the fish, and a photo with the angler and tackle.</p><a href={links.records} target="_blank" rel="noreferrer">LOWA evidence rules ↗</a></article><article className="challenge-card"><span className="state-pill">3 · APPLY</span><h3>Sign and submit</h3><p>The angler and two witnesses to the weighing sign the application. Submit the required materials and fee within 60 days of the catch.</p><a href={links.records} target="_blank" rel="noreferrer">Download LOWA forms ↗</a></article></div></section>
    <section className="section challenge-layout"><div><p className="eyebrow">WHO RUNS THE RECORDS?</p><h2>LOWA administers this program.</h2><p>The Louisiana Outdoor Writers Association maintains the fish record lists, reviews applications, and issues Top Ten certificates. LDWF supplies fishing rules and may help verify species, but the fish record application goes to LOWA.</p><a className="btn primary" href={links.records} target="_blank" rel="noreferrer">Visit LOWA records ↗</a></div><aside className="challenge-side"><p className="eyebrow">PLAN A LEGAL TRIP</p><h2>Check the current rules.</h2><p>Review LDWF’s fishing seasons, size and possession limits, and license requirements before your trip. Saltwater fishing may require a Saltwater License in addition to the Basic Fishing License; other permits can apply.</p><a className="btn secondary" href={links.regulations} target="_blank" rel="noreferrer">LDWF seasons and regulations ↗</a><p><a href={links.licenses} target="_blank" rel="noreferrer">Check licenses and permits ↗</a></p></aside></section>
    <section className="section final-cta challenge-final"><p className="eyebrow">READY TO PLAN?</p><h2>Compare the records. Choose your water.</h2><p>Start with LOWA’s live record list and application, then use LDWF’s current fishing resources for legal places, seasons, and permits.</p><div className="actions"><a className="btn primary" href={links.records} target="_blank" rel="noreferrer">Explore Louisiana records ↗</a><a className="btn secondary" href={links.waters} target="_blank" rel="noreferrer">Plan with LDWF ↗</a></div></section>
    <footer><strong>FISH THE FIFTY</strong><span>Built for anglers who want to fish farther.</span></footer>
  </main>;
}
