import type { Metadata } from "next";
import OhioTracker from "./tracker";
import { ohioSpecies } from "./qualifying-species";

export const metadata: Metadata = { title: "Ohio Fish Ohio Challenge | Fish the Fifty", description: "Plan and track qualifying catches for Ohio's Fish Ohio and Master Angler recognition program." };
const links = { apply: "https://apps.ohiodnr.gov/wildlife/FishOhio/User/login.aspx", rules: "https://dam.assets.ohio.gov/image/upload/ohiodnr.gov/documents/wildlife/laws-regs-licenses/OhioFishingRegs_English", license: "https://oh-web.s3licensing.com/", maps: "https://ohiodnr.gov/discover-and-learn/safety-conservation/about-odnr/wildlife/fishing-forecasts-and-reports" };

export default function OhioChallengePage() { return <main>
  <header className="nav-shell"><div className="nav-wrap"><a className="brand" href="/">FISH THE FIFTY</a><nav><a href="/states">States</a><a href="/#challenges">Challenges</a><a href="/#progress">My Progress</a></nav></div></header><div className="breadcrumb"><a href="/states">States</a><span> / </span><a href="/states/ohio/challenge">Ohio</a><span> / </span><span>Fish Ohio</span></div>
  <section className="page-hero challenge-hero ohio-hero"><div className="page-hero-inner"><p className="eyebrow">OHIO · OFFICIAL ODNR PROGRAM</p><h1>One trophy catch.<br />Four for Master Angler.</h1><p className="lead">Catch any Fish Ohio species at or above its qualifying length for annual recognition. Record four different qualifying species in one year to earn Master Angler recognition.</p><div className="state-facts"><span>26 eligible species</span><span>Length-based recognition</span><span>Four species for Master Angler</span><span>Online submission</span></div><div className="actions"><a className="btn primary" href={links.apply}>Submit at Fish Ohio ↗</a><a className="btn secondary" href={links.rules}>Official rules and sizes ↗</a></div></div></section>
  <section className="section challenge-layout"><div><OhioTracker /><div className="challenge-note"><strong>Planning tool only.</strong><p>Your catches remain in this browser. Fish the Fifty does not verify eligibility or submit entries. ODNR’s current rules control.</p></div></div><aside className="challenge-side"><p className="eyebrow">HOW IT WORKS</p><h2>Measure, record, submit.</h2><ol className="challenge-steps"><li><strong>Catch a listed species.</strong><span>The fish must be taken by legal angling in eligible Ohio water—not a pay lake.</span></li><li><strong>Measure total length.</strong><span>Measure in a straight line from the closed snout to the compressed tail’s farthest end.</span></li><li><strong>Check the correct water table.</strong><span>Lake Erie and its tributaries use different standards for several species.</span></li><li><strong>Submit by December 31.</strong><span>Enter qualifying catches online. Four different species categories in one year earn Master Angler.</span></li></ol><a className="btn primary" href={links.apply}>Open official application ↗</a></aside></section>
  <section className="section qualification-section"><div className="section-heading"><p className="eyebrow">2026–27 QUALIFYING LENGTHS</p><h2>Know the number before you fish.</h2><p>“All waters” standards apply statewide. Lake Erie standards include its tributaries; inland standards cover the Ohio River, inland rivers and streams, reservoirs, lakes and private ponds.</p></div><div className="qualification-table-wrap ohio-table"><table><thead><tr><th>Species</th><th>All waters</th><th>Lake Erie</th><th>Inland waters</th></tr></thead><tbody>{ohioSpecies.map((fish) => <tr key={fish.name}><th>{fish.name}</th><td>{fish.allWaters ? `${fish.allWaters}"` : "—"}</td><td>{fish.lakeErie ? `${fish.lakeErie}"` : fish.allWaters ? "Same" : "—"}</td><td>{fish.inland ? `${fish.inland}"` : fish.allWaters ? "Same" : "—"}</td></tr>)}</tbody></table></div></section>
  <section className="section texas-side-program"><div className="texas-share-card"><div><p className="eyebrow">THE MASTER ANGLER PATH</p><h2>Build a four-species season.</h2><p>Mix accessible targets such as sunfish, rock bass and crappie with a larger-water goal. Each species counts once, so plan for variety rather than repeats.</p></div><a className="btn secondary" href={links.maps}>Ohio fishing forecasts ↗</a></div></section>
  <section className="section final-cta challenge-final"><p className="eyebrow">READY TO START?</p><h2>Choose species one—and its water.</h2><p>Verify seasons, limits and water-specific regulations before every trip, then submit qualifying catches directly to ODNR.</p><div className="actions"><a className="btn primary" href={links.apply}>Log a Fish Ohio catch ↗</a><a className="btn secondary" href={links.license}>Buy an Ohio license ↗</a></div></section><footer><strong>FISH THE FIFTY</strong><span>Built for anglers who want to fish farther.</span></footer>
  </main>; }
