import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Mississippi State Fishing Records | Fish the Fifty",
  description: "Explore Mississippi freshwater and saltwater fishing records, categories, evidence, and official applications.",
};

const freshwater = "https://www.mdwfp.com/fishing-boating/state-fishing-records";
const saltwater = "https://dmr.ms.gov/state-saltwater-records/";

export default function MississippiChallengePage() {
  return <main>
    <header className="nav-shell"><div className="nav-wrap"><a className="brand" href="/">FISH THE FIFTY</a><nav aria-label="Main navigation"><a href="/states">States</a><a href="/#challenges">Challenges</a><a href="/members">My Progress</a></nav></div></header>
    <div className="breadcrumb"><a href="/states">States</a><span aria-hidden="true"> / </span><span>Mississippi</span></div>
    <section className="page-hero challenge-hero"><div className="page-hero-inner"><p className="eyebrow">MISSISSIPPI · TWO RECORD PROGRAMS</p><h1>Mississippi<br />State Fishing Records.</h1><p className="lead">From inland lakes to the Gulf Coast, a record catch starts with the right agency. Explore freshwater records with MDWFP or saltwater records with MDMR, then check the live list and application before fishing.</p><div className="state-facts"><span>Freshwater · MDWFP</span><span>Saltwater · MDMR</span><span>Separate applications</span></div><div className="actions"><a className="btn primary" href="#record-paths">Choose your water ↓</a><a className="btn secondary" href={saltwater} target="_blank" rel="noreferrer">Official saltwater records ↗</a></div></div></section>
    <section className="section challenge-layout" id="record-paths"><div><p className="eyebrow">INLAND WATERS · MDWFP</p><h2>Find a freshwater record.</h2><p>Mississippi Department of Wildlife, Fisheries, and Parks maintains freshwater record catches in Rod and Reel, Fly Fishing, and Trophy categories. The Trophy category covers other legal sport methods. Each category has its own record list and application.</p><ol className="challenge-steps"><li><strong>Compare the standing catch.</strong><span>Look up your species in the appropriate category before targeting a record.</span></li><li><strong>Read the category application.</strong><span>Use the MDWFP form and its current instructions to plan how you will weigh, identify, document, and submit the fish.</span></li><li><strong>Keep your evidence together.</strong><span>Record the catch details and follow the agency’s application requirements promptly.</span></li></ol><a className="btn primary" href={freshwater} target="_blank" rel="noreferrer">Freshwater records and forms ↗</a></div><aside className="challenge-side"><p className="eyebrow">COASTAL WATERS · MDMR</p><h2>Choose a saltwater division.</h2><p>Mississippi Department of Marine Resources publishes All-Tackle, Conventional Tackle, and Fly Fishing records, plus separate youth Conventional and Fly divisions. Check the live species list and the record rules for your division.</p><p>For a potential saltwater record, MDMR requires a complete official application and supporting evidence. Its rules set a seven-day window for weighing on an approved certified scale and a 30-day application deadline after capture.</p><a className="btn secondary" href={saltwater} target="_blank" rel="noreferrer">Saltwater records and rules ↗</a></aside></section>
    <section className="section"><div className="section-heading"><p className="eyebrow">SALTWATER SUBMISSION</p><h2>Plan the proof before the trip.</h2><p>MDMR’s rules are specific. Review them in full, including the legal method, species identification, license, and vessel requirements, before attempting a record.</p></div><div className="card-grid"><article className="challenge-card"><span className="state-pill">1 · PHOTOGRAPH</span><h3>Show the fish clearly</h3><p>Submit two color photos: one of the angler with the fish and a clear close-up side view of the fish.</p><a href={saltwater} target="_blank" rel="noreferrer">Photo rules ↗</a></article><article className="challenge-card"><span className="state-pill">2 · WEIGH</span><h3>Use a certified scale</h3><p>Weigh within seven days with two weight witnesses other than the applicant. The catch and weight witnesses must be different people.</p><a href={saltwater} target="_blank" rel="noreferrer">Weighing rules ↗</a></article><article className="challenge-card"><span className="state-pill">3 · APPLY</span><h3>Submit within 30 days</h3><p>Complete MDMR’s official application within 30 days of capture. A fly-fishing entry must include the fly, which becomes MDMR property.</p><a href={saltwater} target="_blank" rel="noreferrer">Application rules ↗</a></article></div></section>
    <section className="section qualification-section"><div className="section-heading"><p className="eyebrow">YOUTH SALTWATER</p><h2>A separate path for anglers under 16.</h2><p>MDMR has youth Conventional and Fly Fishing divisions. The youth rules say the fish must weigh at least 50% of the current state record body weight. The seven-day weighing and 30-day application windows also apply; review the youth rules before the catch.</p></div><div className="actions"><a className="btn primary" href={saltwater} target="_blank" rel="noreferrer">Read youth record rules ↗</a></div></section>
    <section className="section final-cta challenge-final"><p className="eyebrow">READY TO PLAN?</p><h2>Choose the record book first.</h2><p>Freshwater and saltwater entries go to different Mississippi agencies. Start with the official current record and category form for the water you will fish.</p><div className="actions"><a className="btn primary" href={freshwater} target="_blank" rel="noreferrer">MDWFP freshwater ↗</a><a className="btn secondary" href={saltwater} target="_blank" rel="noreferrer">MDMR saltwater ↗</a></div></section>
    <footer><strong>FISH THE FIFTY</strong><span>Built for anglers who want to fish farther.</span></footer>
  </main>;
}
