import type { Metadata } from "next";
export const metadata: Metadata = { title: "Washington Trout Derby & Fish Records | Fish the Fifty", description: "Plan Washington's 2026 statewide Trout Derby, find participating lakes, claim tagged trout prizes, and explore official sport fish records." };
const derby = "https://wdfw.wa.gov/fishing/contests/trout-derby";
const lakes = "https://wdfw.wa.gov/fishing/contests/trout-derby/lakes";
const records = "https://wdfw.wa.gov/fishing/basics/records";
const rules = "https://wdfw.wa.gov/fishing/regulations";
const licenses = "https://wdfw.wa.gov/licenses/fishing/types-fees";
export default function WashingtonChallengePage() {
  return <main>
    <header className="nav-shell"><div className="nav-wrap"><a className="brand" href="/">FISH THE FIFTY</a><nav aria-label="Main navigation"><a href="/states">States</a><a href="/#challenges">Challenges</a><a href="/#progress">My Progress</a></nav></div></header>
    <div className="breadcrumb"><a href="/states">States</a><span aria-hidden="true"> / </span><span>Washington</span></div>
    <section className="page-hero challenge-hero"><div className="page-hero-inner"><p className="eyebrow">WASHINGTON · WDFW STATEWIDE TROUT DERBY</p><h1>Find a tagged trout.<br />Claim a derby prize.</h1><p className="lead">Explore participating stocked lakes in Washington's statewide Trout Derby, or set your sights on an official freshwater or saltwater sport fish record.</p><div className="state-facts"><span>2026: April 25–October 31</span><span>No derby entry fee</span><span>Participating stocked lakes</span></div><div className="actions"><a className="btn primary" href="#derby">Plan a derby trip ↓</a><a className="btn secondary" href={lakes} target="_blank" rel="noreferrer">Official derby lakes ↗</a></div></div></section>
    <section className="section challenge-layout" id="derby"><div><p className="eyebrow">STATEWIDE TROUT DERBY</p><h2>Choose a lake. Watch for a tag.</h2><ol className="challenge-steps"><li><strong>Check the participating lake list.</strong><span>Use WDFW's current derby lake directory to choose a water and review its fishing information.</span></li><li><strong>Confirm your license and the lake's rules.</strong><span>No derby registration or extra entry fee is required. Follow the current fishing license requirements, seasons, gear restrictions and harvest limits.</span></li><li><strong>Catch a derby-tagged trout.</strong><span>Keep the tag number and catch details. Follow WDFW's current instructions for identifying a winning tag.</span></li><li><strong>Claim through WDFW.</strong><span>Use the official derby page's prize-claim instructions and deadlines. Prizes are supplied by participating businesses.</span></li></ol><a className="btn primary" href={derby} target="_blank" rel="noreferrer">Derby rules &amp; prize instructions ↗</a></div><aside className="challenge-side"><p className="eyebrow">2026 DERBY SEASON</p><h2>April 25 through October 31.</h2><p>The derby runs across participating stocked lakes. A derby listing does not change a lake's fishing season or regulations; check the exact water before you travel.</p><div className="actions"><a className="btn secondary" href={lakes} target="_blank" rel="noreferrer">Find derby lakes ↗</a><a className="btn secondary" href={rules} target="_blank" rel="noreferrer">Fishing regulations ↗</a></div></aside></section>
    <section className="section"><div className="section-heading"><p className="eyebrow">OFFICIAL PLANNING RESOURCES</p><h2>Build your Washington trip.</h2></div><div className="card-grid"><article className="challenge-card"><span className="state-pill">DERBY</span><h3>Participating waters</h3><p>Start with the live lake list, then use each WDFW lake page to research fishing and access.</p><a href={lakes} target="_blank" rel="noreferrer">Browse derby lakes ↗</a></article><article className="challenge-card"><span className="state-pill">LICENSE</span><h3>Fishing requirements</h3><p>Review freshwater and combination license options, exemptions and any species-specific requirements.</p><a href={licenses} target="_blank" rel="noreferrer">License information ↗</a></article><article className="challenge-card"><span className="state-pill">CURRENT RULES</span><h3>Water-specific regulations</h3><p>WDFW provides current regulations and Fish Washington app information. Check for changes before fishing.</p><a href={rules} target="_blank" rel="noreferrer">Rules and updates ↗</a></article></div></section>
    <section className="section challenge-layout"><div><p className="eyebrow">STATE SPORT FISH RECORDS</p><h2>Think you caught the biggest?</h2><p>WDFW maintains freshwater and saltwater sport fish records. Compare your species with the live record table and review the official application before pursuing a record.</p><p>WDFW says the first important step is to weigh the fish promptly on a certified scale, then take it to a WDFW office for verification. Contact the Sport Fish Record Coordinator for assistance.</p><a className="btn primary" href={records} target="_blank" rel="noreferrer">Records &amp; verification process ↗</a></div><aside className="challenge-side"><p className="eyebrow">BEFORE RETAINING A FISH</p><h2>Check eligibility and handling.</h2><p>Only fish that may legally be taken and harvested can qualify. Read WDFW's current record instructions, including preservation and verification requirements, before retaining a potential record.</p><a className="btn secondary" href={records} target="_blank" rel="noreferrer">Official record instructions ↗</a></aside></section>
    <section className="section final-cta challenge-final"><p className="eyebrow">READY TO GO?</p><h2>Start with a derby lake.</h2><p>Choose a participating water, check today's rules, and keep the official prize instructions handy.</p><div className="actions"><a className="btn primary" href={derby} target="_blank" rel="noreferrer">Explore Washington Trout Derby ↗</a><a className="btn secondary" href="/states">Back to all states</a></div></section>
    <footer><strong>FISH THE FIFTY</strong><span>Built for anglers who want to fish farther.</span></footer>
  </main>;
}
