import type { Metadata } from "next";
import IdahoTracker from "./tracker";

export const metadata: Metadata = { title: "Idaho State Record Fish & Native Trout | Fish the Fifty", description: "Explore Idaho's certified-weight and catch-and-release records, application rules, and native trout targets." };
const links = {
  rules: "https://idfg.idaho.gov/fish/record/guidelines",
  apply: "https://idfg.idaho.gov/fish/record/apply",
  records: "https://idfg.idaho.gov/fish/record",
  length: "https://idfg.idaho.gov/fish/record/catch-and-release",
  weight: "https://idfg.idaho.gov/fish/record/certified-weight",
  trout: "https://idfg.idaho.gov/article/summertime-trout-slam",
  planner: "https://idfg.idaho.gov/ifwis/fishingplanner/",
};
export default function IdahoChallengePage() {
  return <main>
    <header className="nav-shell"><div className="nav-wrap"><a className="brand" href="/">FISH THE FIFTY</a><nav aria-label="Main navigation"><a href="/states">States</a><a href="/#challenges">Challenges</a><a href="/members">My Progress</a></nav></div></header>
    <div className="breadcrumb"><a href="/states">States</a><span aria-hidden="true"> / </span><span>Idaho</span></div>
    <section className="page-hero challenge-hero"><div className="page-hero-inner"><p className="eyebrow">IDAHO · FISH AND GAME</p><h1>Idaho State<br />Record Fish.</h1><p className="lead">Aim for an Idaho record by certified weight or catch-and-release length. Compare the current standing record, document your fish carefully, and submit the official application within 30 days.</p><div className="state-facts"><span>2 record categories</span><span>Publicly accessible waters</span><span>Apply within 30 days</span></div><div className="actions"><a className="btn primary" href="#record-paths">Choose a record path ↓</a><a className="btn secondary" href={links.records} target="_blank" rel="noreferrer">Current Idaho records ↗</a></div></div></section>
    <section className="section challenge-layout" id="record-paths"><div><p className="eyebrow">CERTIFIED WEIGHT</p><h2>For a legally harvested fish.</h2><ol className="challenge-steps"><li><strong>Check the standing record and open season.</strong><span>Fish must come from publicly accessible water by a legal method; hold a valid Idaho fishing license.</span></li><li><strong>Keep the fish for verification.</strong><span>An Idaho Fish and Game employee must certify the species in person.</span></li><li><strong>Use a certified scale.</strong><span>Have a witness observe the weighing and keep the certified scale receipt.</span></li><li><strong>Apply within 30 days.</strong><span>Send the official application, receipt, and photos of the fish and angler.</span></li></ol><a className="btn primary" href={links.weight} target="_blank" rel="noreferrer">Check certified-weight records ↗</a></div><aside className="challenge-side"><p className="eyebrow">CATCH AND RELEASE</p><h2>For a longer fish released alive.</h2><p>Measure total length beside a ruler or tape, photograph the species and measurement clearly, take an angler photo, and release the fish promptly. Submit the official application within 30 days.</p><p>A new record generally must exceed the current length by at least half an inch. White sturgeon require two inches and must be measured in the water. Read the full IDFG rules for tie and handling details.</p><a className="btn secondary" href={links.length} target="_blank" rel="noreferrer">Check release records ↗</a></aside></section>
    <section className="section"><div className="section-heading"><p className="eyebrow">RECORD APPLICATION</p><h2>Make the evidence count.</h2><p>IDFG requires the official form and photos. The certified-weight path also needs the scale receipt, witness, and in-person species verification. Record values can change, so use the live lists before claiming a fish.</p></div><div className="card-grid"><article className="challenge-card"><span className="state-pill">1 · VERIFY</span><h3>Current record</h3><p>Compare your species and category with the current Idaho record list.</p><a href={links.records} target="_blank" rel="noreferrer">View records ↗</a></article><article className="challenge-card"><span className="state-pill">2 · DOCUMENT</span><h3>Photos and measurements</h3><p>Capture a clear side view with a visible measure for released fish, plus a photograph with the angler.</p><a href={links.rules} target="_blank" rel="noreferrer">Read evidence rules ↗</a></article><article className="challenge-card"><span className="state-pill">3 · SUBMIT</span><h3>Official application</h3><p>Send the completed form and required evidence to Idaho Fish and Game within 30 days.</p><a href={links.apply} target="_blank" rel="noreferrer">How to apply ↗</a></article></div></section>
    <section className="section challenge-layout"><div><p className="eyebrow">PROTECTED FISH</p><h2>Some records can only be released.</h2><p>IDFG lists white sturgeon, bull trout, wild steelhead, and wild ocean-run Chinook salmon as catch-and-release-only record candidates because they cannot be harvested. Check the exact water’s season and handling rules before targeting any of them.</p><a className="btn primary" href={links.rules} target="_blank" rel="noreferrer">Read eligibility rules ↗</a></div><aside className="challenge-side"><p className="eyebrow">TRIP PLANNING</p><h2>Find the right water.</h2><p>Use Idaho’s Fishing Planner to research waters, species, access, and current fishing regulations. Record eligibility still depends on the official IDFG program rules.</p><a className="btn secondary" href={links.planner} target="_blank" rel="noreferrer">Open Idaho Fishing Planner ↗</a></aside></section>
    <section className="section" id="native-trout"><div className="section-heading"><p className="eyebrow">MULTI-STATE BONUS CHALLENGE</p><h2>Idaho’s native trout contribution.</h2><p>Idaho Fish and Game highlights five Idaho trout eligible for the Western Native Trout Challenge. That separate program spans western states; catching Idaho fish alone does not complete its multi-state requirements. Confirm its registration, native-range rules, and documentation before starting.</p></div><IdahoTracker /><div className="actions" style={{ marginTop: "24px" }}><a className="btn primary" href={links.trout} target="_blank" rel="noreferrer">IDFG native trout guide ↗</a></div></section>
    <section className="section final-cta challenge-final"><p className="eyebrow">READY TO PLAN?</p><h2>Pick a species. Check the standing record.</h2><p>Review the current Idaho record list and local fishing rules before you travel, then use IDFG’s official application for a qualifying catch.</p><div className="actions"><a className="btn primary" href={links.apply} target="_blank" rel="noreferrer">Apply for an Idaho record ↗</a><a className="btn secondary" href="/states">Back to all states</a></div></section>
    <footer><strong>FISH THE FIFTY</strong><span>Built for anglers who want to fish farther.</span></footer>
  </main>;
}
