import type { Metadata } from "next";
import ConnecticutTracker from "./tracker";
import { freshwater } from "./species";

export const metadata: Metadata = {
  title: "Connecticut Trophy Fish Awards | Fish the Fifty",
  description: "Connecticut DEEP's freshwater trophy thresholds, catch-and-release rules, youth Fishing Challenge, and private checklist.",
};
const official = "https://portal.ct.gov/DEEP-Trophy-Fish-Awards";
const youth = "https://portal.ct.gov/deep/fishing/care/fishing-challenge";

export default function ConnecticutChallengePage() {
  return <main>
    <header className="nav-shell"><div className="nav-wrap"><a className="brand" href="/">FISH THE FIFTY</a><nav aria-label="Main navigation"><a href="/states">States</a><a href="/#challenges">Challenges</a><a href="/members">My Progress</a></nav></div></header>
    <div className="breadcrumb"><a href="/states">States</a><span aria-hidden="true"> / </span><span>Connecticut</span></div>
    <section className="page-hero challenge-hero"><div className="page-hero-inner"><p className="eyebrow">CONNECTICUT · DEPARTMENT OF ENERGY &amp; ENVIRONMENTAL PROTECTION</p><h1>Connecticut<br />Trophy Fish Awards.</h1><p className="lead">Compare DEEP’s freshwater trophy standards for harvested fish by weight or released fish by length. Document the catch and apply through Connecticut’s official angler recognition portal.</p><div className="state-facts"><span>{freshwater.length} freshwater criteria</span><span>Harvest and release categories</span><span>Enter within 30 days</span></div><div className="actions"><a className="btn primary" href="#criteria">See qualifying sizes ↓</a><a className="btn secondary" href={official} target="_blank" rel="noreferrer">Official DEEP program ↗</a></div></div></section>
    <section className="section challenge-layout"><div><p className="eyebrow">HOW THE AWARD WORKS</p><h2>Measure, photograph, submit.</h2><ol className="challenge-steps"><li><strong>Fish legally.</strong><span>One angler must catch the fish by a legal method during the open season.</span></li><li><strong>Choose the correct category.</strong><span>Harvest awards use the species’ minimum weight; catch-and-release awards use its minimum length. Length does not substitute for weight in the harvest category.</span></li><li><strong>Document the fish.</strong><span>Submit a clear, original, unaltered photograph. For a released fish, have a witness present for measurement and photograph it with the angler and measuring device at the catch site.</span></li><li><strong>Enter within 30 days.</strong><span>Use DEEP’s online angler recognition portal, linked from the official program page. Potential harvest records require a certified scale printout.</span></li></ol><a className="btn primary" href={official} target="_blank" rel="noreferrer">Rules and submission portal ↗</a></div><aside className="challenge-side"><p className="eyebrow">RECOGNITION</p><h2>Build toward a pin.</h2><p>DEEP awards a certificate of merit, a bronze pin for a first fish of merit, a silver pin for a fifth, and a gold pin for a tenth or a new state record.</p><p>The program also recognizes annual Top Anglers and Anglers of the Year. Its portal accepts State Record Fish, My First Fish, My Personal Best, and Youth Fishing Passport Challenge entries.</p><p>DEEP prohibits AI use and altered or enhanced entry photos. Keep your original catch photos.</p></aside></section>
    <section className="section qualification-section alabama-size-section" id="criteria"><div className="section-heading"><p className="eyebrow">OFFICIAL FRESHWATER CRITERIA</p><h2>Find your species’ mark.</h2><p>Weight applies to harvested fish; length applies to catch-and-release fish. Check DEEP’s current table before fishing or submitting.</p></div><div className="qualification-table-wrap alabama-table-wrap"><table><caption className="visually-hidden">Connecticut DEEP freshwater Trophy Fish minimum harvest weights and release lengths</caption><thead><tr><th scope="col">Species</th><th scope="col">Harvest · minimum weight</th><th scope="col">Release · minimum length</th></tr></thead><tbody>{freshwater.map(([name, weight, length]) => <tr key={name}><th scope="row">{name}</th><td>{weight}</td><td>{length}</td></tr>)}</tbody></table></div><p className="alabama-threshold-note">* DEEP does not recognize “sea-run” trout records in the catch-and-release category. Species not listed may be reviewed by Fisheries staff. See the official page for the complete marine table, special measurement rules, and exclusions.</p><div className="actions"><a className="btn primary" href={official} target="_blank" rel="noreferrer">Full freshwater and marine criteria ↗</a></div></section>
    <section className="section" id="tracker"><div className="section-heading"><p className="eyebrow">YOUR PRIVATE CHECKLIST</p><h2>Keep your freshwater targets organized.</h2><p>Track potential catches here, then use DEEP’s portal and required evidence for official review.</p></div><ConnecticutTracker /></section>
    <section className="section challenge-layout"><div><p className="eyebrow">YOUTH FISHING PASSPORT</p><h2>Try the Fishing Challenge.</h2><p>Young anglers can work through DEEP’s species scorecard during a year-long Fishing Challenge. Photograph the youth angler with each catch and submit it through the angler recognition portal using “fishing challenge” as the recognition type.</p><a className="btn primary" href={youth} target="_blank" rel="noreferrer">Youth scorecard and details ↗</a></div><aside className="challenge-side"><p className="eyebrow">SALTWATER ANGLERS</p><h2>Marine trophies count, too.</h2><p>DEEP publishes separate minimum weights and lengths for marine species, including striped bass, bluefish, black sea bass, tautog, scup, and fluke. Review its full table and current saltwater rules before planning a catch.</p><a className="btn secondary" href={official} target="_blank" rel="noreferrer">See marine criteria ↗</a></aside></section>
    <section className="section final-cta challenge-final"><p className="eyebrow">READY TO FISH?</p><h2>Pick a species and check its rules.</h2><p>Confirm the current season, legal methods, and measurement instructions with Connecticut DEEP before you go.</p><div className="actions"><a className="btn primary" href={official} target="_blank" rel="noreferrer">Open official awards page ↗</a><a className="btn secondary" href="/states">Back to all states</a></div></section>
    <footer><strong>FISH THE FIFTY</strong><span>Built for anglers who want to fish farther.</span></footer>
  </main>;
}
