// Connecticut DEEP Trophy Fish Award freshwater criteria, reviewed September 2026.
export const freshwater = [
  ["American Eel", "3 pounds", "35 inches"],
  ["American Shad", "5 pounds", "25 inches"],
  ["Atlantic Salmon", "15 pounds", "31 inches"],
  ["Bluegill", "12 ounces", "10 inches"],
  ["Bowfin", "7 pounds", "24 inches"],
  ["Brook Trout", "2 pounds", "17 inches*"],
  ["Brown Bullhead", "2 pounds", "15 inches"],
  ["Brown Trout", "5 pounds", "22 inches*"],
  ["Calico Bass (Black Crappie)", "2 pounds", "15 inches"],
  ["Common Carp", "20 pounds", "34 inches"],
  ["Chain Pickerel", "5 pounds", "27 inches"],
  ["Channel Catfish", "4 pounds", "22 inches"],
  ["Fallfish", "1.5 pounds", "14 inches"],
  ["Kokanee", "1.75 pounds", "16 inches"],
  ["Lake Trout", "14 pounds", "32 inches"],
  ["Largemouth Bass", "6 pounds", "22 inches"],
  ["Northern Pike", "10 pounds", "35 inches"],
  ["Pumpkinseed", "8 ounces", "9 inches"],
  ["Rainbow Trout (including Golden Rainbow Trout)", "4 pounds", "21 inches*"],
  ["Redbreast Sunfish", "8 ounces", "9 inches"],
  ["Rock Bass", "12 ounces", "11 inches"],
  ["Smallmouth Bass", "4 pounds", "21 inches"],
  ["Sunfish Hybrids", "12 ounces", "10 inches"],
  ["Tench", "4 pounds", "18 inches"],
  ["Tiger Musky", "12 pounds", "40 inches"],
  ["Tiger Trout", "2 pounds", "17 inches*"],
  ["Walleye", "5 pounds", "23 inches"],
  ["White Catfish", "4 pounds", "20 inches"],
  ["White Perch", "1.5 pounds", "14 inches"],
  ["White Sucker", "3 pounds", "15 inches"],
  ["Yellow Bullhead", "2 pounds", "15 inches"],
  ["Yellow Perch", "1 pound", "13 inches"],
] as const;
