import type { Metadata } from "next";
import KentuckyTracker from "./tracker";
import { species } from "./species";
export const metadata: Metadata = { title: "Kentucky Trophy Fish & Master Angler | Fish the Fifty", description: "Kentucky's Trophy Fish minimum lengths, three-species Master Angler path, application requirements, and private checklist." };
const official = "https://fw.ky.gov/Fish/Pages/Trophy-Fish-Program---Master-Angler-Award.aspx";
export default function KentuckyChallengePage() {
  return <main><header className="nav-shell"><div className="nav-wrap"><a className="brand" href="/">FISH THE FIFTY</a><nav aria-label="Main navigation"><a href="/states">States</a><a href="/#challenges">Challenges</a><a href="/members">My Progress</a></nav></div></header>
    <div className="breadcrumb"><a href="/states">States</a><span aria-hidden="true"> / </span><span>Kentucky</span></div>
    <section className="page-hero challenge-hero"><div className="page-hero-inner"><p className="eyebrow">KENTUCKY · FISH AND WILDLIFE RESOURCES</p><h1>Kentucky Trophy Fish<br />&amp; Master Angler.</h1><p className="lead">Catch one eligible fish at its trophy length to start. Document and register three different qualifying species, then request Kentucky’s Master Angler Award.</p><div className="state-facts"><span>{species.length} eligible species</span><span>3 species for Master Angler</span><span>60 days to apply per catch</span></div><div className="actions"><a className="btn primary" href="#sizes">See qualifying lengths ↓</a><a className="btn secondary" href={official} target="_blank" rel="noreferrer">Official Kentucky program ↗</a></div></div></section>
    <section className="section challenge-layout"><div><p className="eyebrow">THE OFFICIAL PATH</p><h2>One trophy, then three species.</h2><ol className="challenge-steps"><li><strong>Catch by handheld pole and line.</strong><span>Meet the minimum length for an eligible Kentucky species and follow all fishing rules. Pay-lake, hatchery, and commercial-propagation fish do not qualify.</span></li><li><strong>Submit each trophy within 60 days.</strong><span>Upload a clear side-view photograph through Kentucky Fish and Wildlife’s My Profile. Hold a valid Kentucky fishing license or follow the agency’s stated exemption process.</span></li><li><strong>Collect three different approved species.</strong><span>There is no overall time limit for the three species, but each must be documented and registered as a Trophy Fish catch.</span></li><li><strong>Request Master Angler.</strong><span>After the third species is approved, use the Master Angler section in My Profile to choose the three qualifying catches and request the award.</span></li></ol><a className="btn primary" href={official} target="_blank" rel="noreferrer">Application steps and rules ↗</a></div><aside className="challenge-side"><p className="eyebrow">WHAT YOU EARN</p><h2>Catch a trophy. Keep the story.</h2><p>The first approved fish brings a Trophy Fish patch and sticker plus a species patch and sticker. Additional different species can earn their own species patches and stickers. Approved entries also have a printable certificate.</p><p>The Master Angler Award adds its own patch, sticker, and printable certificate. Repeat catches of one species can receive certificates, but not additional species patches.</p><a className="btn secondary" href={official} target="_blank" rel="noreferrer">See award details ↗</a></aside></section>
    <section className="section qualification-section alabama-size-section" id="sizes"><div className="section-heading"><p className="eyebrow">OFFICIAL MINIMUM TROPHY LENGTHS</p><h2>Compare all {species.length} species.</h2><p>These lengths are in inches. Confirm Kentucky’s current table and fishing regulations before applying.</p></div><div className="qualification-table-wrap alabama-table-wrap"><table><caption className="visually-hidden">Kentucky Trophy Fish minimum length by species</caption><thead><tr><th scope="col">Species</th><th scope="col">Minimum length</th></tr></thead><tbody>{species.map(([name, inches]) => <tr key={name}><th scope="row">{name}</th><td>{inches} inches</td></tr>)}</tbody></table></div><div className="actions"><a className="btn primary" href={official} target="_blank" rel="noreferrer">Check Kentucky’s current list ↗</a></div></section>
    <section className="section" id="tracker"><div className="section-heading"><p className="eyebrow">YOUR PRIVATE CHECKLIST</p><h2>Track your three-species goal.</h2><p>Mark potential qualifying catches here and submit each fish separately to Kentucky for review.</p></div><KentuckyTracker /></section>
    <section className="section final-cta challenge-final"><p className="eyebrow">READY TO START?</p><h2>Pick a species and measure carefully.</h2><p>Keep a clear side-view photo, apply within 60 days, and use the official My Profile process for an approved award.</p><div className="actions"><a className="btn primary" href={official} target="_blank" rel="noreferrer">Open Kentucky’s application guide ↗</a><a className="btn secondary" href="/states">Back to all states</a></div></section><footer><strong>FISH THE FIFTY</strong><span>Built for anglers who want to fish farther.</span></footer>
  </main>;
}
