import type { Metadata } from "next";
import WyomingTracker from "./tracker";
import { cutthroats, masterSpecies } from "./species";
export const metadata: Metadata = { title: "Wyoming Cutt-Slam & Master Angler | Fish the Fifty", description: "Catch Wyoming's four native cutthroat subspecies and explore all 24 Master Angler qualifying lengths." };
const cutt = "https://wgfd.wyo.gov/fishing-boating/fishing-challenges/wyoming-cutt-slam";
const master = "https://wgfd.wyo.gov/fishing-boating/fishing-challenges/master-angler";
export default function WyomingChallengePage() {
  return <main><header className="nav-shell"><div className="nav-wrap"><a className="brand" href="/">FISH THE FIFTY</a><nav aria-label="Main navigation"><a href="/states">States</a><a href="/#challenges">Challenges</a><a href="/#progress">My Progress</a></nav></div></header>
    <div className="breadcrumb"><a href="/states">States</a><span aria-hidden="true"> / </span><span>Wyoming</span></div>
    <section className="page-hero challenge-hero"><div className="page-hero-inner"><p className="eyebrow">WYOMING · GAME &amp; FISH DEPARTMENT</p><h1>Wyoming Cutt-Slam<br />&amp; Master Angler.</h1><p className="lead">Find four native cutthroat trout in their Wyoming ranges, or pursue trophy-sized fish across Wyoming waters. Track both official challenges as you plan.</p><div className="state-facts"><span>4 native cutthroat subspecies</span><span>24 Master Angler species</span><span>No Cutt-Slam deadline</span></div><div className="actions"><a className="btn primary" href="#cutt-slam">Explore Cutt-Slam ↓</a><a className="btn secondary" href="#master-angler">See Master Angler ↓</a></div></div></section>
    <section className="section" id="cutt-slam"><div className="section-heading"><p className="eyebrow">OFFICIAL WYOMING CUTT-SLAM</p><h2>Four cutthroats. Four native ranges.</h2><p>Catch and photograph each subspecies in its native Wyoming range. Record the date and location, then submit all four through Wyoming Game and Fish’s online application. Participation is free and there is no time limit.</p></div><div className="card-grid">{cutthroats.map(t => <article className="challenge-card" key={t.name}><span className="state-pill">NATIVE-RANGE TARGET</span><h3>{t.name} cutthroat</h3><p>{t.range}</p><a href={cutt} target="_blank" rel="noreferrer">Official waters and guide ↗</a></article>)}</div><p className="alabama-threshold-note">These are examples from the agency’s guide, not a complete or guaranteed location list. Confirm the exact water, native range, access, and current regulations before fishing. Westslope cutthroat is not part of the Wyoming Cutt-Slam.</p><div className="actions"><a className="btn primary" href={cutt} target="_blank" rel="noreferrer">Cutt-Slam map and application ↗</a></div></section>
    <section className="section challenge-layout"><div><p className="eyebrow">DOCUMENT YOUR SLAM</p><h2>Keep four clear catch records.</h2><ol className="challenge-steps"><li><strong>Identify the subspecies and native drainage.</strong><span>Use Wyoming’s interactive guide and ask regional fisheries staff when a location is uncertain.</span></li><li><strong>Photograph every fish.</strong><span>Keep a clear photo of the subspecies and record the date and catch location.</span></li><li><strong>Submit all four online.</strong><span>Wyoming Game and Fish reviews the documentation. Its first approved Cutt-Slam earns a personalized certificate, medallion, and vehicle decal.</span></li></ol><a className="btn primary" href={cutt} target="_blank" rel="noreferrer">Official Cutt-Slam details ↗</a></div><aside className="challenge-side"><p className="eyebrow">TAKE YOUR TIME</p><h2>A lifetime or a day.</h2><p>There is no completion deadline. Wyoming encourages additional Cutt-Slam submissions, though the medallion and certificate are provided only for the first submission.</p><p>Check each water’s season and restrictions before traveling.</p></aside></section>
    <section className="section qualification-section alabama-size-section" id="master-angler"><div className="section-heading"><p className="eyebrow">WYOMING MASTER ANGLER</p><h2>One fish starts it. Ten species reach Ultimate.</h2><p>Catch one fish at its qualifying length for Master Angler, five different species for Trophy Angler, or ten for Ultimate Angler. Residents and nonresidents may enter. Fish must be caught legally during open seasons in Wyoming.</p></div><div className="qualification-table-wrap alabama-table-wrap"><table><caption className="visually-hidden">Wyoming Master Angler minimum total length by species</caption><thead><tr><th scope="col">Species</th><th scope="col">Minimum total length</th></tr></thead><tbody>{masterSpecies.map(([name, inches]) => <tr key={name}><th scope="row">{name}</th><td>{inches} inches</td></tr>)}</tbody></table></div><p className="alabama-threshold-note">WGFD measures total length to the nearest half inch from snout to pinched tail. Each entry needs a side-view photo that helps verify length. One Master Angler entry per species is allowed per calendar year; Trophy and Ultimate progress have no overall time limit. Fish caught after June 1, 2019, may be entered.</p><div className="actions"><a className="btn primary" href={master} target="_blank" rel="noreferrer">Official sizes and catch submission ↗</a></div></section>
    <section className="section" id="tracker"><div className="section-heading"><p className="eyebrow">YOUR PRIVATE CHECKLIST</p><h2>Track both Wyoming goals.</h2><p>This browser checklist helps with trip planning. Photos and catches must go through Wyoming Game and Fish for official recognition.</p></div><WyomingTracker /></section>
    <section className="section final-cta challenge-final"><p className="eyebrow">READY TO START?</p><h2>Choose a drainage or a trophy species.</h2><p>Confirm access and current regulations, document your catch, and submit it through the official challenge page.</p><div className="actions"><a className="btn primary" href={cutt} target="_blank" rel="noreferrer">Plan the Cutt-Slam ↗</a><a className="btn secondary" href={master} target="_blank" rel="noreferrer">Explore Master Angler ↗</a><a className="btn secondary" href="/states">Back to all states</a></div></section><footer><strong>FISH THE FIFTY</strong><span>Built for anglers who want to fish farther.</span></footer>
  </main>;
}
