import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "South Dakota Proud Angler | Fish the Fifty",
  description: "Explore South Dakota Proud Angler trophy fish recognition, release-length and weight standards, and the state record application process.",
};

const proud = "https://gfp.sd.gov/proud-angler/";
const records = "https://gfp.sd.gov/state-record-fish/";
const fishing = "https://gfp.sd.gov/fish/";
const handbook = "https://gfp.sd.gov/UserDocs/nav/FishingHandbook_2026.pdf";
const examples = [
  ["Walleye", "8 lb", "27 in", "https://gfp.sd.gov/walleye/"],
  ["Smallmouth bass", "3 lb", "18 in", "https://gfp.sd.gov/smallmouth-bass/"],
  ["Northern pike", "15 lb", "38 in", "https://gfp.sd.gov/northern-pike/"],
] as const;

export default function SouthDakotaChallengePage() {
  return <main>
    <header className="nav-shell"><div className="nav-wrap"><a className="brand" href="/">FISH THE FIFTY</a><nav aria-label="Main navigation"><a href="/states">States</a><a href="/#challenges">Challenges</a><a href="/members">My Progress</a></nav></div></header>
    <div className="breadcrumb"><a href="/states">States</a><span aria-hidden="true"> / </span><span>South Dakota</span></div>
    <section className="page-hero challenge-hero"><div className="page-hero-inner"><p className="eyebrow">SOUTH DAKOTA · GAME, FISH AND PARKS</p><h1>South Dakota<br />Proud Angler.</h1><p className="lead">Turn a trophy catch into official recognition. South Dakota's Proud Angler program includes catch-and-release awards and encourages anglers to let large fish swim again.</p><div className="state-facts"><span>Trophy fish recognition</span><span>Release-length standards</span><span>Official online application</span></div><div className="actions"><a className="btn primary" href="#sizes">Compare trophy sizes ↓</a><a className="btn secondary" href={proud} target="_blank" rel="noreferrer">Official Proud Angler program ↗</a></div></div></section>
    <section className="section challenge-layout"><div><p className="eyebrow">YOUR PROUD ANGLER PATH</p><h2>Choose a target. Document the catch.</h2><ol className="challenge-steps"><li><strong>Check the current standard.</strong><span>Review GFP's qualifying species information and the official application before your trip.</span></li><li><strong>Fish legally and measure carefully.</strong><span>Compare your catch with the applicable weight or released-fish length. Keep the catch date, water, species, measurement and supporting photos ready for the application.</span></li><li><strong>Consider catch and release.</strong><span>GFP encourages release of trophy fish. Length qualifications shown here apply to released fish only.</span></li><li><strong>Apply through GFP.</strong><span>The Proud Angler page links to the official application and previous recognized catches. Follow its current evidence and submission instructions.</span></li></ol><a className="btn primary" href={proud} target="_blank" rel="noreferrer">Apply for Proud Angler ↗</a></div><aside className="challenge-side"><p className="eyebrow">BEFORE YOU CAST</p><h2>Check the exact water.</h2><p>Licenses, size limits, harvest rules and border-water regulations can vary. Review South Dakota's current fishing handbook and GFP's fishing resources before planning your catch.</p><div className="actions"><a className="btn secondary" href={handbook} target="_blank" rel="noreferrer">Fishing handbook ↗</a><a className="btn secondary" href={fishing} target="_blank" rel="noreferrer">Waters, access &amp; rules ↗</a></div></aside></section>
    <section className="section qualification-section alabama-size-section" id="sizes"><div className="section-heading"><p className="eyebrow">SELECT PROUD ANGLER QUALIFICATIONS</p><h2>Three trophy goals to start with.</h2><p>These examples come from GFP's species pages. Released-fish length and weight are separate qualifications; confirm the current standard and application requirements before submitting.</p></div><div className="qualification-table-wrap alabama-table-wrap"><table><caption className="visually-hidden">Selected South Dakota Proud Angler trophy qualifications</caption><thead><tr><th scope="col">Species</th><th scope="col">Weight</th><th scope="col">Released length</th><th scope="col">Official source</th></tr></thead><tbody>{examples.map(([species, weight, length, url]) => <tr key={species}><th scope="row">{species}</th><td>{weight}</td><td>{length}</td><td><a href={url} target="_blank" rel="noreferrer">GFP species page ↗</a></td></tr>)}</tbody></table></div></section>
    <section className="section challenge-layout"><div><p className="eyebrow">STATE RECORD PATH</p><h2>A separate benchmark and application.</h2><p>GFP maintains hook-and-line and unrestricted record categories. Potential records need identification by a qualified ichthyologist or fisheries biologist and weighing on a state-certified legal-for-trade scale.</p><p>Two witnesses other than the angler must attend the weighing, or one GFP fisheries or law enforcement employee. Their signatures belong on the application.</p><a className="btn primary" href={records} target="_blank" rel="noreferrer">Record rules, application &amp; records ↗</a></div><aside className="challenge-side"><p className="eyebrow">RECORD WEIGHT RULES</p><h2>Round down to the ounce.</h2><p>A record fish must weigh at least one pound. Weight is rounded down to the nearest ounce, and a new record must exceed the existing record by at least one ounce.</p><p>Protected species that cannot legally be harvested are not eligible. Check the full official rules and species list before retaining a potential record.</p></aside></section>
    <section className="section final-cta challenge-final"><p className="eyebrow">READY TO PLAN?</p><h2>Start with your Proud Angler target.</h2><p>Choose a species, check its standard, and open the official application before fishing.</p><div className="actions"><a className="btn primary" href={proud} target="_blank" rel="noreferrer">Explore Proud Angler ↗</a><a className="btn secondary" href="/states">Back to all states</a></div></section>
    <footer><strong>FISH THE FIFTY</strong><span>Built for anglers who want to fish farther.</span></footer>
  </main>;
}
