import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "North Carolina Angler Recognition | Fish the Fifty",
  description: "Explore North Carolina freshwater Angler Recognition, six-certificate Master Angler, and saltwater tournament citations.",
};

const freshwater = "https://www.ncwildlife.gov/fishing/state-fishing-records/nc-angler-recognition-program";
const records = "https://www.ncwildlife.gov/fishing/state-fishing-records";
const saltwater = "https://www.deq.nc.gov/about/divisions/marine-fisheries/public-information-and-education/coastal-fishing-information/nc-saltwater-fishing-tournament";
const saltForm = "https://www.deq.nc.gov/about/divisions/marine-fisheries/public-information-and-education/coastal-fishing-information/nc-saltwater-fishing-tournament/2026-north-carolina-saltwater-fishing-tournament-citation-application";
const inlandExamples = [
  ["Largemouth bass", "8 lb", "24 in"],
  ["Smallmouth bass", "3 lb", "19 in"],
  ["Crappie (black or white)", "2 lb", "16 in"],
  ["Freshwater drum", "12 lb", "28 in"],
  ["Brook trout", "2 lb", "16 in"],
  ["Walleye", "5 lb", "23 in"],
] as const;
const coastalExamples = [
  ["Red drum", "Release only", "43 in"],
  ["Flounder", "6 lb", "24 in"],
  ["Spotted seatrout", "6 lb", "26 in"],
  ["Black sea bass", "4 lb", "18 in"],
] as const;

export default function NorthCarolinaChallengePage() {
  return <main>
    <header className="nav-shell"><div className="nav-wrap"><a className="brand" href="/">FISH THE FIFTY</a><nav aria-label="Main navigation"><a href="/states">States</a><a href="/#challenges">Challenges</a><a href="/members">My Progress</a></nav></div></header>
    <div className="breadcrumb"><a href="/states">States</a><span aria-hidden="true"> / </span><span>North Carolina</span></div>
    <section className="page-hero challenge-hero"><div className="page-hero-inner"><p className="eyebrow">NORTH CAROLINA · TWO ANGLER PROGRAMS</p><h1>North Carolina<br />Angler Recognition.</h1><p className="lead">Earn a freshwater certificate for a qualifying catch and collect six unique certificates for Master Angler. Along the coast, the Division of Marine Fisheries runs a separate saltwater citation tournament.</p><div className="state-facts"><span>Freshwater · NC Wildlife</span><span>6 certificates · Master</span><span>Saltwater · NC DEQ</span></div><div className="actions"><a className="btn primary" href="#freshwater">Explore freshwater ↓</a><a className="btn secondary" href="#saltwater">Explore saltwater ↓</a></div></div></section>
    <section className="section challenge-layout" id="freshwater"><div><p className="eyebrow">FRESHWATER · ANGLER RECOGNITION</p><h2>Make a memorable catch count.</h2><ol className="challenge-steps"><li><strong>Check either minimum.</strong><span>A freshwater fish qualifies by meeting or exceeding the listed weight or length. Catch-and-release and catch-and-keep entries are both welcome.</span></li><li><strong>Photograph the catch.</strong><span>NC Wildlife invites a photo of the fish and angler through its online form.</span></li><li><strong>Get a free certificate.</strong><span>Complete the official online form to receive a downloadable species certificate. Anglers 15 and younger may receive one without meeting a minimum size.</span></li><li><strong>Collect six unique certificates.</strong><span>Six different Angler Recognition Program certificates earn a special Master Angler certificate and patch, mailed once per angler.</span></li></ol><a className="btn primary" href={freshwater} target="_blank" rel="noreferrer">Official sizes and certificate form ↗</a></div><aside className="challenge-side"><p className="eyebrow">FRESHWATER STATE RECORDS</p><h2>A separate record path.</h2><p>A trophy catch may also challenge the state record. NC Wildlife keeps its freshwater state record rules and application separate from the Angler Recognition certificate.</p><p>Check the official standing record and verification steps before handling a possible record fish.</p><a className="btn secondary" href={records} target="_blank" rel="noreferrer">Freshwater record program ↗</a></aside></section>
    <section className="section qualification-section alabama-size-section"><div className="section-heading"><p className="eyebrow">FRESHWATER EXAMPLES</p><h2>Meet weight or length.</h2><p>Selected NC Wildlife Angler Recognition minimums are below. A fish needs to meet either column; check the agency’s complete live table and current fishing regulations before your trip.</p></div><div className="qualification-table-wrap alabama-table-wrap"><table><caption className="visually-hidden">Selected North Carolina freshwater Angler Recognition weight or length minimums</caption><thead><tr><th scope="col">Species</th><th scope="col">Weight</th><th scope="col">Length</th></tr></thead><tbody>{inlandExamples.map(([name, weight, length]) => <tr key={name}><th scope="row">{name}</th><td>{weight}</td><td>{length}</td></tr>)}</tbody></table></div><div className="actions"><a className="btn primary" href={freshwater} target="_blank" rel="noreferrer">All freshwater minimums ↗</a></div></section>
    <section className="section challenge-layout" id="saltwater"><div><p className="eyebrow">SALTWATER · CITATION TOURNAMENT</p><h2>Follow the coastal rules.</h2><p>North Carolina Division of Marine Fisheries recognizes exceptional hook-and-line catches with saltwater citations. The annual tournament runs January 1 through December 31. Qualifying harvested fish can meet the listed minimum weight or length; released fish must meet the release length, with certain species designated release only.</p><ol className="challenge-steps"><li><strong>Check the species and legal season.</strong><span>Confirm the current citation requirement and all applicable state and federal limits. Red drum is release only for this citation program.</span></li><li><strong>Document through the correct path.</strong><span>Harvested entries use an official weigh station and signed application. For release entries, an angler or mate must touch the fish or leader and a witness must sign; the program offers an online release application.</span></li><li><strong>Apply by January 15.</strong><span>The agency must receive a citation application by January 15 of the year after the catch.</span></li></ol><a className="btn primary" href={saltwater} target="_blank" rel="noreferrer">Saltwater citation rules ↗</a></div><aside className="challenge-side"><p className="eyebrow">COASTAL EXAMPLES</p><h2>Know the target.</h2><div className="qualification-table-wrap"><table><caption className="visually-hidden">Selected North Carolina saltwater citation requirements</caption><thead><tr><th scope="col">Species</th><th scope="col">Weight</th><th scope="col">Length</th></tr></thead><tbody>{coastalExamples.map(([name, weight, length]) => <tr key={name}><th scope="row">{name}</th><td>{weight}</td><td>{length}</td></tr>)}</tbody></table></div><p>These are citation standards, not harvest limits. Check seasonal proclamations before keeping fish.</p><a className="btn secondary" href={saltForm} target="_blank" rel="noreferrer">2026 citation application ↗</a></aside></section>
    <section className="section final-cta challenge-final"><p className="eyebrow">READY TO FISH?</p><h2>Choose the right agency.</h2><p>Use NC Wildlife’s online form for freshwater certificates and NC DEQ’s tournament rules for saltwater citations. Each program also has a separate state record process.</p><div className="actions"><a className="btn primary" href={freshwater} target="_blank" rel="noreferrer">Freshwater recognition ↗</a><a className="btn secondary" href={saltwater} target="_blank" rel="noreferrer">Saltwater citations ↗</a></div></section>
    <footer><strong>FISH THE FIFTY</strong><span>Built for anglers who want to fish farther.</span></footer>
  </main>;
}
