import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Rhode Island Game Fish Awards | Fish the Fifty",
  description: "Plan a Rhode Island Game Fish Award catch, review freshwater and saltwater minimums, and learn the state record and First Fish paths.",
};

const awards = "https://dem.ri.gov/natural-resources-bureau/natural-resources-divisions/fish-wildlife/freshwater-fishing/game-fish";
const programs = "https://dem.ri.gov/natural-resources-bureau/fish-wildlife/freshwater-fishing/fishing-award-programs";
const records = "https://dem.ri.gov/natural-resources-bureau/fish-wildlife/reports-publications/sportfish-records";
const freshwater = "https://dem.ri.gov/natural-resources-bureau/fish-wildlife/freshwater-fishing/freshwater-fishing-faqs";

export default function RhodeIslandChallengePage() {
  return <main>
    <header className="nav-shell"><div className="nav-wrap"><a className="brand" href="/">FISH THE FIFTY</a><nav aria-label="Main navigation"><a href="/states">States</a><a href="/#challenges">Challenges</a><a href="/#progress">My Progress</a></nav></div></header>
    <div className="breadcrumb"><a href="/states">States</a><span aria-hidden="true"> / </span><span>Rhode Island</span></div>
    <section className="page-hero challenge-hero"><div className="page-hero-inner"><p className="eyebrow">RHODE ISLAND · DEM GAME FISH AWARDS</p><h1>A memorable catch.<br />Official recognition.</h1><p className="lead">Rhode Island recognizes notable freshwater and saltwater game fish each year. Choose an eligible species, meet its published minimum, document the catch, and apply through the Department of Environmental Management.</p><div className="state-facts"><span>Freshwater &amp; saltwater</span><span>Harvest or release</span><span>One award per angler per year</span></div><div className="actions"><a className="btn primary" href="#award-path">Plan an award catch ↓</a><a className="btn secondary" href={awards} target="_blank" rel="noreferrer">Official award minimums ↗</a></div></div></section>
    <section className="section challenge-layout" id="award-path"><div><p className="eyebrow">GAME FISH AWARD PATH</p><h2>Check, catch, document, apply.</h2><ol className="challenge-steps"><li><strong>Pick an eligible species.</strong><span>Compare your target with DEM's current freshwater or saltwater minimum size table.</span></li><li><strong>Fish qualifying public water.</strong><span>The catch must be taken legally in Rhode Island water open to the public without a fee, special permission, or membership.</span></li><li><strong>Document the fish.</strong><span>For a released catch, photograph the fish with a hand scale and/or ruler; a retained fish may be brought to an official weigh station. DEM measures total length from snout to tail tip.</span></li><li><strong>Send the signed application.</strong><span>Use DEM's Game Fish Award form and submission instructions. Awards are mailed the following spring, with one award per person per year.</span></li></ol><a className="btn primary" href={awards} target="_blank" rel="noreferrer">Official rules, sizes &amp; application ↗</a></div><aside className="challenge-side"><p className="eyebrow">KNOW THE WATER</p><h2>Check current fishing rules.</h2><p>Freshwater and marine fishing have different licenses, seasons, size limits, and reporting rules. Review the exact water and species before fishing; stocked trout waters may have seasonal closures.</p><a className="btn secondary" href={freshwater} target="_blank" rel="noreferrer">DEM fishing updates ↗</a></aside></section>
    <section className="section"><div className="section-heading"><p className="eyebrow">MORE WAYS TO BE RECOGNIZED</p><h2>Records and first catches.</h2></div><div className="card-grid"><article className="challenge-card"><span className="state-pill">STATE RECORD</span><h3>Freshwater records</h3><p>Compare DEM's current records. A potential record must be weighed and measured at an official station using a digital scale; call ahead.</p><a href={records} target="_blank" rel="noreferrer">Record rules and stations ↗</a></article><article className="challenge-card"><span className="state-pill">STATE RECORD</span><h3>Saltwater records</h3><p>DEM maintains a separate saltwater record list and identifies other notable marine catches that receive recognition outside the award species list.</p><a href={records} target="_blank" rel="noreferrer">Saltwater records ↗</a></article><article className="challenge-card"><span className="state-pill">YOUTH AWARD</span><h3>Children's First Fish</h3><p>A child's first fish can earn a certificate and gift through DEM's application program.</p><a href={programs} target="_blank" rel="noreferrer">First Fish application ↗</a></article></div></section>
    <section className="section final-cta challenge-final"><p className="eyebrow">READY TO START?</p><h2>Choose your qualifying fish.</h2><p>Check DEM's live minimum size tables, take a clear measurement photo, and keep the award form handy.</p><div className="actions"><a className="btn primary" href={awards} target="_blank" rel="noreferrer">Open Game Fish Awards ↗</a><a className="btn secondary" href="/states">Back to all states</a></div></section>
    <footer><strong>FISH THE FIFTY</strong><span>Built for anglers who want to fish farther.</span></footer>
  </main>;
}
