import type { Metadata } from "next";
import ArkansasTracker from "./tracker";
import { arkansasCategories, arkansasFish } from "./qualifying-species";

export const metadata: Metadata = { title: "Arkansas Master Angler Challenge | Fish the Fifty", description: "Track Arkansas Master Angler trophy catches and the 2026 Arkansas Grand Slam." };
const links = { master: "https://www.agfc.com/education/master-angler-program/", grandSlam: "https://www.agfc.com/education/arkansas-grand-slam/", regulations: "https://www.agfc.com/regulations/general-fishing-regulations/", license: "https://ar-licensing.s3licensing.com/", waters: "https://www.agfc.com/fishing/where-to-fish/", lunker: "https://www.agfc.com/fishing/black-bass/arkansas-legacy-lunker-program/" };

export default function ArkansasChallengePage() { return <main>
  <header className="nav-shell"><div className="nav-wrap"><a className="brand" href="/">FISH THE FIFTY</a><nav><a href="/states">States</a><a href="/#challenges">Challenges</a><a href="/#progress">My Progress</a></nav></div></header><div className="breadcrumb"><a href="/states">States</a><span> / </span><a href="/states/arkansas/challenge">Arkansas</a><span> / </span><span>Master Angler</span></div>
  <section className="page-hero challenge-hero arkansas-hero"><div className="page-hero-inner"><p className="eyebrow">ARKANSAS · OFFICIAL AGFC PROGRAMS</p><h1>Four trophy categories.<br />Earn Master Angler.</h1><p className="lead">Land qualifying trophy fish from four of Arkansas’s eight categories to become a certified Master Angler. The catches can be completed across multiple years.</p><div className="state-facts"><span>31 qualifying species</span><span>Eight trophy categories</span><span>Four categories to certify</span><span>Residents and visitors eligible</span></div><div className="actions"><a className="btn primary" href={links.master}>Official Master Angler program ↗</a><a className="btn secondary" href={links.regulations}>2026–27 fishing regulations ↗</a></div></div></section>
  <section className="section arkansas-tracker-section"><ArkansasTracker /><div className="challenge-note"><strong>Planning tools only.</strong><p>Your progress remains in this browser. Fish the Fifty does not verify weights, photos, legality or eligibility; AGFC’s rules and application decisions control.</p></div></section>
  <section className="section challenge-layout"><div><p className="eyebrow">HOW MASTER ANGLER WORKS</p><h2>One trophy starts the journey.</h2><ol className="challenge-steps"><li><strong>Catch by rod and reel.</strong><span>The fish must be legally caught in Arkansas waters.</span></li><li><strong>Meet the published weight.</strong><span>Each eligible species has a minimum trophy weight.</span></li><li><strong>Document and apply.</strong><span>Use AGFC’s online form for each qualifying catch.</span></li><li><strong>Complete four categories.</strong><span>The four catches may occur in different years and must span four of the eight program categories.</span></li></ol><a className="btn primary" href={links.master}>Apply for an AGFC pin ↗</a></div><aside className="challenge-side"><p className="eyebrow">WHAT YOU EARN</p><h2>Pins, certificate and coin.</h2><p>A qualifying fish earns a category pin and recognition letter. Certification in four categories earns a frameable Master Angler certificate and commemorative coin.</p><a className="btn secondary" href={links.grandSlam}>Official Grand Slam page ↗</a></aside></section>
  <section className="section qualification-section"><div className="section-heading"><p className="eyebrow">OFFICIAL MINIMUM WEIGHTS</p><h2>Thirty-one trophy targets.</h2><p>Weights are pounds. Confirm the current AGFC page before traveling or submitting a catch.</p></div><div className="arkansas-category-grid">{arkansasCategories.map((category) => <article className="challenge-card compact" key={category}><span className="state-pill">{category}</span>{arkansasFish.filter((fish) => fish.category === category).map((fish) => <div className="arkansas-fish-row" key={fish.species}><span>{fish.species}</span><strong>{fish.pounds} lb</strong></div>)}</article>)}</div></section>
  <section className="section texas-side-program"><div className="texas-share-card"><div><p className="eyebrow">2026 LIMITED-YEAR CHALLENGE</p><h2>Arkansas Grand Slam</h2><p>Catch a catfish, bass, crappie, bream and trout from January 1 through December 31, 2026. No minimum size applies; submit catch photos and details for an official sticker.</p></div><a className="btn secondary" href={links.grandSlam}>Grand Slam rules and form ↗</a></div></section>
  <section className="section texas-side-program"><div className="texas-share-card arkansas-lunker"><div><p className="eyebrow">TEN-POUND BASS · JANUARY–MARCH</p><h2>Arkansas Legacy Lunker</h2><p>A live largemouth bass weighing at least 10 pounds from eligible public water may qualify for the state’s donation and breeding program. Call 833-948-BASS immediately after the catch.</p></div><a className="btn secondary" href={links.lunker}>Legacy Lunker rules ↗</a></div></section>
  <section className="section final-cta challenge-final"><p className="eyebrow">READY TO START?</p><h2>Choose the first category.</h2><p>Review the water-specific rules, target a qualifying fish, and document the catch carefully.</p><div className="actions"><a className="btn primary" href={links.waters}>Find Arkansas fishing waters ↗</a><a className="btn secondary" href={links.license}>Buy an Arkansas license ↗</a></div></section><footer><strong>FISH THE FIFTY</strong><span>Built for anglers who want to fish farther.</span></footer>
  </main>; }
