"use client";

import { useEffect, useMemo, useState } from "react";
import { arkansasCategories, arkansasFish, grandSlamFish } from "./qualifying-species";

type MasterCatch = { category: string; species: string; weight: string; date: string; water: string; applied: boolean };
type SlamCatch = { caught: boolean; date: string; water: string; photo: boolean };
const STORAGE_KEY = "fish-the-fifty-arkansas-challenges-v1";
const emptyMaster = (): MasterCatch => ({ category: "", species: "", weight: "", date: "", water: "", applied: false });
const emptySlam = (): Record<string, SlamCatch> => Object.fromEntries(grandSlamFish.map((fish) => [fish, { caught: false, date: "", water: "", photo: false }]));

export default function ArkansasTracker() {
  const [master, setMaster] = useState<MasterCatch[]>(Array.from({ length: 4 }, emptyMaster));
  const [slam, setSlam] = useState<Record<string, SlamCatch>>(emptySlam);
  const [saved, setSaved] = useState(false);
  useEffect(() => { try { const raw = localStorage.getItem(STORAGE_KEY); if (!raw) return; const value = JSON.parse(raw) as { master?: MasterCatch[]; slam?: Record<string, SlamCatch> }; if (Array.isArray(value.master)) setMaster(Array.from({ length: 4 }, (_, i) => ({ ...emptyMaster(), ...(value.master?.[i] ?? {}) }))); if (value.slam) setSlam({ ...emptySlam(), ...value.slam }); } catch { /* Keep trackers usable. */ } }, []);
  const masterCount = useMemo(() => master.filter((item, index) => { const fish = arkansasFish.find((candidate) => candidate.species === item.species); return Boolean(fish && Number(item.weight) >= fish.pounds && item.category && master.findIndex((other) => other.category === item.category) === index); }).length, [master]);
  const slamCount = grandSlamFish.filter((fish) => slam[fish]?.caught).length;
  function updateMaster(index: number, field: keyof MasterCatch, value: string | boolean) { setSaved(false); setMaster((current) => current.map((item, i) => i === index ? { ...item, [field]: value, ...(field === "category" ? { species: "" } : {}) } : item)); }
  function updateSlam(fish: string, field: keyof SlamCatch, value: string | boolean) { setSaved(false); setSlam((current) => ({ ...current, [fish]: { ...current[fish], [field]: value } })); }
  function save() { try { localStorage.setItem(STORAGE_KEY, JSON.stringify({ master, slam })); } catch { /* Continue without persistence. */ } setSaved(true); }
  function clear() { setMaster(Array.from({ length: 4 }, emptyMaster)); setSlam(emptySlam()); setSaved(false); try { localStorage.removeItem(STORAGE_KEY); } catch { /* Nothing to clear. */ } }
  return <div className="arkansas-trackers"><div className="tracker-card texas-tracker arkansas-tracker"><div className="tracker-top"><div><p className="eyebrow">MASTER ANGLER TRACKER</p><h3>Four trophy categories</h3></div><strong>{masterCount} / 4</strong></div><div className="tracker-track"><span style={{ width: `${masterCount * 25}%` }} /></div><p className="tracker-help">Qualifying catches may be collected across multiple years. Each completed slot must represent a different category and meet its official minimum weight.</p><div className="texas-slots">{master.map((item, index) => { const fish = arkansasFish.find((candidate) => candidate.species === item.species); const below = Boolean(fish && Number(item.weight) > 0 && Number(item.weight) < fish.pounds); const duplicate = Boolean(item.category && master.findIndex((other) => other.category === item.category) !== index); return <section className="texas-slot" key={index}><div className="texas-slot-heading"><strong>Category {index + 1}</strong>{item.applied && <span>Applied</span>}</div><label>Category<select value={item.category} onChange={(e) => updateMaster(index, "category", e.target.value)}><option value="">Choose a category…</option>{arkansasCategories.map((category) => <option key={category}>{category}</option>)}</select></label><label>Species<select value={item.species} disabled={!item.category} onChange={(e) => updateMaster(index, "species", e.target.value)}><option value="">Choose a species…</option>{arkansasFish.filter((candidate) => candidate.category === item.category).map((candidate) => <option key={candidate.species}>{candidate.species}</option>)}</select></label><div className="texas-slot-fields"><label>Weight (pounds)<input type="number" min="0" step="0.01" value={item.weight} onChange={(e) => updateMaster(index, "weight", e.target.value)} placeholder={fish ? `Minimum ${fish.pounds}` : "Official weight"} /></label><label>Catch date<input type="date" value={item.date} onChange={(e) => updateMaster(index, "date", e.target.value)} /></label></div>{below && <p className="texas-below-minimum">Below the {fish?.pounds}-pound minimum for {item.species}.</p>}{duplicate && <p className="texas-below-minimum">Certified Master Angler status requires four different categories.</p>}<label>Arkansas water<input value={item.water} onChange={(e) => updateMaster(index, "water", e.target.value)} placeholder="Lake, river or stream" /></label><label className="kansas-applied"><input type="checkbox" checked={item.applied} onChange={(e) => updateMaster(index, "applied", e.target.checked)} /> I submitted the official AGFC application</label></section>; })}</div></div>
  <div className="tracker-card arkansas-slam"><div className="tracker-top"><div><p className="eyebrow">2026 ARKANSAS GRAND SLAM</p><h3>Five fish families</h3></div><strong>{slamCount} / 5</strong></div><div className="tracker-track"><span style={{ width: `${slamCount * 20}%` }} /></div><p className="tracker-help">Catch one catfish, bass, crappie, bream and trout between January 1 and December 31, 2026. There is no minimum size.</p><div className="arkansas-slam-list">{grandSlamFish.map((fish) => <section key={fish}><label className="slam-check"><input type="checkbox" checked={slam[fish].caught} onChange={(e) => updateSlam(fish, "caught", e.target.checked)} /><strong>{fish}</strong></label><div><input aria-label={`${fish} date`} type="date" value={slam[fish].date} onChange={(e) => updateSlam(fish, "date", e.target.value)} /><input aria-label={`${fish} water`} value={slam[fish].water} onChange={(e) => updateSlam(fish, "water", e.target.value)} placeholder="Arkansas water" /></div><label className="slam-photo"><input type="checkbox" checked={slam[fish].photo} onChange={(e) => updateSlam(fish, "photo", e.target.checked)} /> Photo ready</label></section>)}</div></div>
  <div className="tracker-actions arkansas-save"><button className="btn primary" type="button" onClick={save}>Save both trackers</button><button className="tracker-clear" type="button" onClick={clear}>Clear Arkansas progress</button>{saved && <span className="tracker-saved">Saved in this browser.</span>}</div></div>;
}
